#!/usr/bin/env python3
"""Render the owner report from the frozen, de-identified evidence package."""
import pathlib,json,csv,collections as co,subprocess,datetime as dt,re
P=pathlib.Path(__file__).parent; ROOT=pathlib.Path.cwd();D=P.name
load=lambda n:json.loads((P/(n+'.json')).read_text())
S=load('summary');T=load('tables');U=load('supplement');plans=load('plans');rows=list(csv.DictReader((P/'scenarios.csv').open()));real=[x for x in rows if x['family']!='stand-aside']; pos=load('position-cohort')['eligible']
parts=[]
def p(s=''):parts.append(s.strip()+'\n')
def table(headers, rows):
 p('| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+'\n'.join('| '+' | '.join(str(x).replace('|','/') for x in r)+' |' for r in rows))
def link(n):return f'[{n}]({D}/{n})'
def count(xs,key,v):return sum(x[key]==v for x in xs)
def mix(d):return ', '.join(f'{k} {v}' for k,v in sorted(d.items())) or 'none recorded'
def ratio(f,g):return f'{f/g:.2f}:1' if g else 'no follows'
def evidence(key,src='tables'):p(f'Evidence: {link(src+".json")}, `{key}`; every cell carries its contributing row/scenario IDs. [A]')
p('# The strategy, written down — 8 September 2026')
p('**Owner summary · descriptive audit · no claim about edge**')
p('Your system trades **intraday reactions at named MNQ levels, with a stronger taste for fades than breakouts**. It buys a failed break below support or sells a failed break above resistance, while also writing reclaim, acceptance and breakout-follow setups. Across the retained history there are **770 actionable scenario descriptions**, including **472 explicit reject/sweep-reclaim setups**. The broader, annotated setup-family count is **496 fades, 266 follows and 8 ambiguous**, not a count of executed trades. [A: C1, scenario IDs in the evidence tables; B: style interpretation.]')
p('Every session it builds and revises a map, chooses levels to write scenarios on, and—under the **currently running strict mode**—can enter through authorized scenario arms. A plan sentence alone does not place an order. Current entry checks include scenario/side consistency, permitted conditions, stop geometry, the Studio **2R minimum**, HTF veto and a fresh broker book showing no existing commitment. Breakout-retest and FVG-entry are currently shadowed. Inactive plans and refused gates stand aside; a “trend” label alone does not. [A: C8 source lines and runtime evidence.]')
p('**It is the same style, not the same daily strategy mix.** ASIA contains **209 fades / 106 follows / 5 ambiguous (n=320)**; LONDON **125 / 74 / 1 (n=200)**; NY **162 / 86 / 2 (n=250)**. Balance-labelled scenarios are **337 fades / 163 follows / 6 ambiguous (n=506)**; trend-labelled scenarios **155 / 101 / 2 (n=258)**. Both groups remain fade-heavy. The strongest same-session contrast is LONDON on **25 August versus 1 September**: **6 long / 2 short (n=8)** becomes **4 long / 9 short (n=13)**, with different level kinds. [A: C1, C3, C5–C6; exact plan rows below.]')
p('It differs from a discretionary trader exercising those choices in three concrete ways. **It can write several competing setups rather than select one trade for the day; conviction does not increase current order size; and it does not currently turn a winner into a partial-plus-runner trade.** The running exit policy says **BE=off, trail=off, size=1**. Its retained eligible fills are all one contract (**n=65**, IDs in C7), with a **25.31-minute median hold**, although some last much longer. That looks like a mixture of short intraday trades and intraday swings, not a demonstrated runner programme. [A: C7–C8; B: trade-style description.]')
p('The important difference from the saved prompt: it does trade balance-labelled plans; it is not restricted to one trade a day; and “50 points to breakeven” is not the current exit behavior. Historical arm events, exact authoring-time price and stop-composition winners are incomplete, so missing evidence is labelled unknown. **This report measures style, not profitability, and recommends no changes.** [A: C4, C7, D4–D5.]')
p('---\n\n## Evidence boundary and reproducibility')
p(f'The frozen SQLite read was **{S["snapshot_ct"]} (CT)**, in one read transaction with `mode=ro` and `PRAGMA query_only=ON`. {link("extract.py")} contains the exact extraction; {link("queries.json")} gives every SQL statement, parameters with private identifiers removed, result count and output file. `analyze.py`, `supplement.py` and this renderer reproduce the descriptive tables offline. There were no writes to trading data, configuration, prompts, code, environment or AddOn, and no restart.')
p('Evidence labels: **[A]** a stored value, code line or direct observation; **[B]** an interpretation supported by those observations. No unsupported [C] conclusion is used. Every table below identifies a source table/key whose cells enumerate IDs. `p178:S1:0` means SQLite `plans.rowid=178`, scenario `S1`, zero-based document slot `0`; level `p178:L0` means the same plan and seated-level slot. This prevents different versions of S1 being collapsed into one setup. Natural bar key is `(MNQ, tf, open_time_ms)`. Raw timestamps retain their original offsets; report event times and converted CSV fields use America/Chicago (CT).')
p('**Runtime premise NOT REPRODUCED:** the dispatch named `f8bc7044`; health instead returned **`6f677b55daa1`**, with PID **3726840**, boot **8 September 2026 18:11:54 CT**. `/proc/3726840/exe` resolved to `/home/hoang/nofx/nofx-bin`; Go build metadata gave `6f677b55daa1c7da33b8c35f8bcc67883f36b470`, `vcs.modified=false`. The loaded executable and disk binary both hashed to `418b08a44e81fb85f5f79524f0cd18d57d4e89b7d91c9100dc076bc7e82c375f`. At **18:27:01 CT**, the API positions list was empty; cutover evidence independently showed no DB/API/NT8 position and no working broker order. No live unprotected position was observed. '+link('runtime.json')+' and '+link('exit-runtime.json')+' preserve the sanitized observations. [A]')
p('The worktree began at that dev tip and the branch was claimed as `docs/the-strategy-0908`; the verified remote SHA at acceptance was `f0c172e1559aaf2718fa9c139c126bed3b8ebb2a`. Main checkout remained read-only. No lock was touched under this dispatch’s A2 override. Current-code descriptions apply to the measured revision; **the whole historical sample did not run this one version**. In particular, current strict/one-contract/exit rules must not be projected backward onto every August fill.')
p('**Final freshness check:** at **8 September 2026 18:43:07 CT**, health and the loaded/disk SHA256 still matched the same running revision, and positions remained empty with cutover ready. '+link('runtime-final.json')+' preserves the GET-only observation. The report branch was rebased onto dev **954f11b1**. Changes since 6f677b55 affected Stage A archive path handling and its documentation; the cited trading implementations were unchanged. The changed SYSTEM-MAP and AUDIT-CHECKLIST sections were reread and the provenance below refreshed. No historical table was silently refreshed beyond the original SQLite cutoff. [A]')
p('Era boundary is the named `store.DayPlanEraStart`, built by `store/attribution.go:146` and `:153` from **15 August 2026 00:00 CT**, milliseconds **1786770000000**. Retained plans: **279 rows**, comprising **277 intraday versions and 2 weekly reference documents** (weekly rows **223, 257**). These yield **806 scenario rows**: **36 S0/trigger=none no-trade sentinels**, plus **770 real scenarios** in **49 session-day groups**. The sentinel constructor is `kernel/plan_doc.go:1032`; counting it as a hold trade would be false. These are retained accepted versions, not every failed planning attempt and not independent observations. '+link('plan-inventory.csv')+'; '+link('scenarios.csv')+'. [A]')
p('Position cohort: **78 era rows → 65 eligible closed trades**, all linked to a retained scenario. Exclusions are disjoint: test rows **572, 573, 574** (`e7_farside_test`); `UNRESOLVABLE` rows **530, 539, 545, 546, 566, 571, 580**; remaining NULL `pnl_corrected` rows **576, 577, 579**. There are **4 raw NULL rows** including already-excluded test row **572**. NULL is not zero. No raw P&L, win rate, expectancy or profitability conclusion is used. The dispatch’s historical “58 trades, 12 days” is **not this snapshot’s cohort**: current eligible n is **65**, spread over **15 CT entry dates**. '+link('position-cohort.json')+' enumerates all included/excluded IDs. [A]')
p('Basis: `docs/superpowers/SYSTEM-MAP.md` and `docs/superpowers/AUDIT-CHECKLIST.md` were read as maps/checklists, not substitutes for live evidence. The planner-preparation README was **not present on this dev tree**; it was read with `git show 6095ca58:docs/superpowers/reports/2026-09-07-planner-preparation-audit/README.md`. Its pinned historical claims are not silently promoted to current findings. Trading-policy research §09 at `982091d4` governs the descriptive-only boundary; the two-day audit at `f890ea60` is historical context. Every cited source file’s exact `git log -1` result appears in the provenance appendix.')
p('## C1 · The playbook')
conds=['reject','sweep_reclaim','reclaim','breakdown_continue','breakup_continue','fvg_entry','acceptance','hold','breakout_retest']
table(['Condition','All retained n=806','Real n=770','ASIA n=320','LONDON n=200','NY n=250'],[[k,count(rows,'condition',k),count(real,'condition',k)]+[sum(x['condition']==k and x['session']==ss for x in real) for ss in ['ASIA','LONDON','NY']] for k in conds])
evidence('all_retained_condition, play_session, stand_aside')
p('The **36 extra holds are no-trade placeholders**, not entries. The observed **0 fvg_entry scenarios out of 770** is a complete retained-document count, not a claim that FVG was unavailable or that all opportunities were declined. The current condition resolver shadows `breakout_retest` and `fvg_entry`; precedence is session override → strategy → environment → default (`kernel/condition_status.go:33`, `trader/armed_executor.go:26`). The resolved boot list in '+link('runtime-log.json')+' confirms those shadows. Historical authorship of **127 breakout_retests** therefore does not mean 127 currently executable setups. [A]')
p('Fade/follow is an **annotated intended setup family**, not observed tick-by-tick approach direction. `reject` and `sweep_reclaim` fade the failed approach; acceptance, reclaim and break/continue families follow the established/reclaimed break. Breakout-retest follows the breakout impulse even though its immediate pullback approaches the entry from the other side. `hold` is overloaded: its explicit continuation/pullback wording is classified by the visible rules in `analyze.py:43`; **8/39 real holds remain ambiguous**. This convention is necessary because a reclaim or hold can describe more than one path. An exact executed “against the approach” ratio is **not recoverable** from condition labels alone. Excluding all holds leaves the less interpretive **472 explicit fades versus 259 follow-family descriptions (n=731; 1.82:1)**. The broader counts below are [A] reproducible annotations, [B] directional style—not measured entry microstructure.')
for field,values in [('session',['ASIA','LONDON','NY']),('day_type_group',sorted(set(x['day_type_group'] for x in real)))]:
 table([field,'n','Fade','Follow','Ambiguous','Fade:follow','Long','Short'],[[v,len(xs:= [x for x in real if x[field]==v]),f:=count(xs,'family','fade'),g:=count(xs,'family','follow'),count(xs,'family','ambiguous'),ratio(f,g),count(xs,'side','long'),count(xs,'side','short')] for v in values])
evidence('family_session, family_day_type, sides_session, sides_day_type')
table(['Condition','Balance n=506','Trend n=258','premium-fade n=3','premium_rejection n=3'],[[c]+[sum(x['condition']==c and x['day_type_group']==v for x in real) for v in ['balance','trend','premium-fade','premium_rejection']] for c in conds])
evidence('play_day_type; play_day_type_raw preserves every unnormalized label')
p('For display, `trend`, `trend-down`, `trend_down` share the trend group; labels beginning `balance` share balance. The raw cross-tab is retained, not overwritten. No-trade and weekly documents stay in the inventory, outside the real-scenario denominator.')
p('Current placement adds another distinction between a proposal and a trade: `trader/armed_executor.go:41` resolves `ARM_PLACE_TICKS` to **100 ticks** when unset; with MNQ **0.25-point ticks**, the limit placement band is **25 points** (`:969`, `:1056`). Both initial process environment and dotenv were unset at the final read. Already-marketable wrong-side limits are cancelled (`:1047`); the **stop-entry seam is explicitly off** in dotenv and the measured boot. Follow-family authorship therefore does not imply a stop-entry was sent. [A: runtime-final.json; runtime-log.json.]')
p('## C2 · Levels chosen for a scenario, versus levels merely seated')
p('Each scenario gets **one documented primary reference**: positive `confirm.ref_price`, otherwise the first trigger price matching a seated level within **0.125 points**. That tolerance is an audit join convention (half a MNQ tick), not a trading threshold. It resolves **762/770** to seated levels; **8/770** remain unresolved. Secondary trigger alternatives and target levels are not counted as additional primary anchors. Unknown labels stay `other`; composite labels stay composite. VWAP variants are grouped; raw labels, all matching level IDs and grades remain in '+link('scenarios.csv')+'. This is a count of **levels selected for authored scenarios**, not proof those scenarios filled. [A/B]')
kinds=sorted(set(x['level_kind'] for x in real),key=lambda k:-count(real,'level_kind',k))
lev=list(csv.DictReader((P/'levels.csv').open()))
table(['Primary level kind','Scenario n','ASIA','LONDON','NY','Seated level rows n'],[[k,count(real,'level_kind',k)]+[sum(x['level_kind']==k and x['session']==v for x in real) for v in ['ASIA','LONDON','NY']]+[count(lev,'kind',k)] for k in kinds])
p('Seated denominator is **2,649 level-version rows**, including the retained documents; selected denominator is **770 scenario-version rows**. These are different units: a level can host more than one scenario, and repeated versions repeat levels. Production `kernel/levels_role.go:303` has a fallback classification; the descriptive taxonomy deliberately preserves unknown/composite labels rather than calling every unknown a round number. Full scenario kind × session × grade counts are in supplement.json `scenario_levels_session_grade`. Full seated kind × session × grade counts: '+link('tables.json')+' `seated_levels`; primary scenario kind × session: `scenario_levels_session`. [A]')
table(['Matched seated grade','Scenario n','Top kinds (counts within grade)'],[[g,len(xs:=[x for x in real if x['level_grade']==g]),mix(dict(co.Counter(x['level_kind'] for x in xs)))] for g in sorted(set(x['level_grade'] for x in real))])
evidence('scenario_levels_grade')
p('Do not confuse **seated level grade** with **scenario quality**. Scenario qualities are **B=464, C=175, A=130, A+=1 (n=770)**; those counts do not measure predictive reliability. `min_grade=B` in saved session settings is not `min_scenario_quality`; the latter resolves separately to **C** when absent (`store/strategy.go:1497`). [A: scenarios.csv; config.json.]')
p('**Exact distance from the planner’s input price at authoring is unavailable.** No complete, version-bound input snapshot supplies that price. Two explicitly limited views follow: a price statement extracted from the saved reasoning, and the latest closed stored one-minute bar no more than two minutes before publication. Publication may occur after a long model request; neither view proves input-time distance. Saved ATR is the document’s `### 5m` ATR14, not a later live ATR.')
table(['Distance view','Scenario median points (n)','Seated median points (n)','Scenario median ATR (n)','Seated median ATR (n)'],[[label]+[f'{S["dist"][k]["median"]:.2f} (n={S["dist"][k]["n"]})' for k in [f'scenario_{v}_distance_pts',f'seated_{v}_distance_pts',f'scenario_{v}_distance_atr',f'seated_{v}_distance_atr']] for label,v in [('Reasoning-stated price','narrative'),('Publication closed-bar proxy','publication')]])
p('Evidence: '+link('summary.json')+' `dist`, each distribution lists contributing IDs; '+link('plan-inventory.csv')+' preserves the extracted price quote, ATR and bar natural key. Reasoning price exists for **105/279** plans; the publication proxy for **240/279**; saved ATR for **266/279**. Scenario anchors sit nearer than the whole seated map in these available subsets [B], but differing denominators, repeated levels and missing inputs prevent an exact all-plan authoring-distance claim.')
p('## C3 · Side and time')
p('Session/day-type long–short counts are in C1. Overall the authored set is **341 long / 429 short (n=770)**. Eligible fills are **25 long / 40 short (n=65)**; authored counts and filled counts are separate populations. '+link('tables.json')+' `eligible_position_side` and `sides_session` enumerate IDs. [A]')
table(['Stored regime-label text','Long','Short','n'],[[g,count(xs:=[x for x in real if x['regime']==g],'side','long'),count(xs,'side','short'),len(xs)] for g in sorted(set(x['regime'] for x in real))])
evidence('sides_regime')
p('These are labels embedded in accepted `bias_label`, **not a reconstructed machine regime**. All **59 retained planner_read_facts rows** lack a plan link; their IDs are enumerated in '+link('summary.json')+' `facts_without_plan_link_ids`. Joining them to nearby timestamps would invent version provenance. Thus a machine-regime-by-side verdict is unavailable. [A]')
table(['Publication hour CT','Authored scenarios n','Distinct accepted orders first observed n'],[[f'{h:02}:00–{h:02}:59',sum(int(x['hour_ct'])==h for x in real),sum(x['hour_ct']==h for x in U['unique_accepted_orders'])] for h in range(24)])
p('Authoring hour is the accepted document’s **publication time**, repeated for its scenarios—not model request start. Total authored n=770. Submission history cannot be reconstructed from `armed_orders.updated_at` or `created_at`: those are mutable authorization-state timestamps. The order column instead uses **12 distinct signal IDs**, deduplicating **24 accepted-risk rows** by earliest receipt; IDs **1/2, 3/4, …, 23/24** are paired observations of the same orders. It is **first observed acceptance**, not an exact wire-submit clock. Its coverage is only **6 September 18:30:00 CT through 8 September 17:23:16 CT**. '+link('supplement.json')+' `authored_hour`, `unique_accepted_orders`, `unique_acceptance_hour`; all first-receipt timestamps and arm IDs are preserved. Blank historical acceptance coverage is not zero placements. [A]')
p('**01:30 CT and 08:00 CT are scheduled preparation times**, LONDON and NY respectively; they are not automatic trade times. The measured boot registry opens LONDON at **02:00 CT** and NY at **08:30 CT**; ASIA prepares **16:30 CT** and opens **17:00 CT**. The broad authored family emphasis differs: LONDON 125:74 (n=200 plus 1 ambiguous), NY 162:86 (n=250 plus 2 ambiguous), and short share is **114/200 versus 128/250**. This is a session-level comparison, not evidence that the clock alone causes the difference. The sparse acceptance subset cannot establish equivalent execution behavior at those exact half-hours. [A/B: runtime-log.json; C1.]')
p('## C4 · What it skips—and what the record cannot call a skip')
p('Definitions: authored = real scenario-version rows; arm evidence = those with a retained arm row matched on plan + `armed_under_version` (fallback `version`) + scenario; reached = stored one-minute high/low contains the primary anchor in the observation window; filled = eligible positions linked to the plan’s trade date. Multiple fills can belong to one scenario. **These columns are not a funnel:** old decision-path fills can have no surviving arm row. Arm rows are reused on reauthorization (`store/armed_orders.go:221`, `:310`), so “no retained arm evidence” must not be called “never armed”.')
p('Reach window: after publication, before next retained version of the same plan, recorded dormant/invalidated/expired event, current-registry session close, or snapshot cutoff—whichever comes first. Only fully contained minute bars count. Those historical session-close boundaries are an audit convention, not a reconstruction of every historic config. A touch on incomplete history proves observed reach; absence proves “not observed” only with a complete window. No minute-level reconstruction proves that the full entry confirmation, order permission or tick path occurred. The **306 observed / 369 not observed in complete windows / 95 unknown (n=770)** are anchor-reach results, not eligible opportunities. Each observed row records its first touching bar ID in scenarios.csv. [A/B]')
cal={x['date']:x for x in T['calendar_days']}
table(['Plan trade date (CT)','Plan row IDs','Authored n','With retained arm n','Reached yes / no / unknown','Filled scenarios n','Eligible fills n (position IDs)'],[[day,','.join(map(str,r['plan_rows'])) if r else 'no retained plans',r['scenario_n'] if r else 'unknown',r['authored_with_arm_evidence_n'] if r else 'unknown',f'{r["reached"].get("observed",0)} / {r["reached"].get("not observed (complete window)",0)} / {r["reached"].get("unknown",0)}' if r else 'unknown',r['filled_scenarios_n'] if r else 'unknown',f'{len(r["position_ids"])} ({",".join(map(str,r["position_ids"])) or "none in cohort"})' if r else 'unknown'] for i in range(25) for day in [(dt.date(2026,8,15)+dt.timedelta(days=i)).isoformat()] for r in [cal.get(day)]])
evidence('calendar_days; session_days contains arm IDs as well as scenario and position IDs')
p('Rows dated 22 August, 29 August and 5 September have **no retained plan documents**, not a measured opportunity count. The 23 August row is a retained no-trade document, not an empty extraction. Plan trade date and calendar entry date differ for overnight ASIA; '+link('supplement.json')+' `fill_calendar_day` supplies the separate actual-entry-date view. No claim that filled = armed = reached is made.')
p('Among **770 real scenarios**, **52 have retained arm evidence** and **718 do not**. Of the latter, **587 have no enabled arm specification**, while **131 have an enabled arm but no surviving matched row**. The **183 enabled complete geometries** therefore cannot be called 183 placed orders. This separation survives exact row/version joining. '+link('supplement.json')+' `arm_enabled`. [A]')
table(['Condition','With arm evidence n=52','Without retained arm n=718'],[[k,sum(x['condition']==k and x['has_arm_evidence']=='True' for x in real),sum(x['condition']==k and x['has_arm_evidence']=='False' for x in real)] for k in conds])
table(['Scenario quality','With arm evidence','Without retained arm'],[[q,sum(x['quality']==q and x['has_arm_evidence']=='True' for x in real),sum(x['quality']==q and x['has_arm_evidence']=='False' for x in real)] for q in ['A+','A','B','C']])
evidence('arm_presence, arm_presence_quality')
p('The publication-price proxy is nearer for scenarios with an arm row: median **25.64 points / 1.16 ATR (n=52)** versus **34.25 points (n=625), 1.60 ATR (n=622)** without. Those are associations in available data, not a reconstructed refusal reason. The no-arm group mixes legacy plans, shadow conditions, unavailable/invalid geometry, changed versions and possible gate refusals. The current code explicitly skips absent/disabled arm specs (`trader/armed_executor.go:317`) and shadow conditions; individual historic non-arm causes are not persistently linked for every scenario. [A/B: summary.json `dist.with_arm_*`, `dist.without_arm_*`.]')
p('## C5 · Is it the same every day?')
p('**No: a recognizable family of setups is reused, but side, condition and reference levels change both across days and within revised plans.** Below is every retained real session-day, with counts rather than an impressionistic label. Abbreviations: R=reject, S=sweep_reclaim, C=reclaim, A=acceptance, H=hold, B=breakout_retest, D=breakdown_continue, U=breakup_continue. F:W is annotated fade:follow; ? is ambiguous. Each row links to exact plan rows; scenario IDs and full raw labels are in the evidence JSON/CSV. [A]')
ab={'reject':'R','sweep_reclaim':'S','reclaim':'C','acceptance':'A','hold':'H','breakout_retest':'B','breakdown_continue':'D','breakup_continue':'U'}
table(['CT session-day','Plan row IDs','n','Declared types (n)','Plays (n)','F:W:?; ratio','Long:short','Primary level kinds (n)'],[[x['session_day'],','.join(map(str,x['plan_rows'])),x['n'],mix(x['day_types']),mix({ab.get(k,k):v for k,v in x['conditions'].items()}),f'{x["families"].get("fade",0)}:{x["families"].get("follow",0)}:{x["families"].get("ambiguous",0)}; '+ratio(x['families'].get('fade',0),x['families'].get('follow',0)),f'{x["sides"].get("long",0)}:{x["sides"].get("short",0)}',mix(x['level_kinds'])] for x in T['session_days']])
evidence('session_days')
p('The similarity comparison is **defined before interpreting the pairs**: compare same-session days with at least **6 scenarios and 2 retained versions**; distance is the equal-weight mean of total-variation distances of condition, side and primary-level-kind distributions. Zero means identical marginals, one disjoint marginals. This is an audit metric, not a trading score or significance test. There are **280 qualifying pairs**; '+link('tables.json')+' `similarity_pairs` records all members, n, plan IDs and component distances. A different metric or inclusion floor can select different extrema. [A]')
for key,label in [('closest_pair','Most similar'),('farthest_pair','Most different')]:
 x=S[key];p(f'**{label}: {x["a"]} (n={x["a_n"]}; plan rows {x["a_plan_rows"]}) versus {x["b"]} (n={x["b_n"]}; rows {x["b_plan_rows"]}).** Mean distance **{x["tv"]:.3f}**; condition **{x["components"]["condition"]:.3f}**, side **{x["components"]["side"]:.3f}**, level-kind **{x["components"]["level_kind"]:.3f}**. Full plan text and version IDs: '+link('supplement.json')+f' `{key}_quotes`. [A]')
p('The similar ASIA pair shows the same choice set in different markets: **row 23 S1** says “5m acceptance below 29568.25 IB-L and 29564.50 EQL”; **row 43 S1** says “Acceptance below ONL: price breaks and holds below 29323.0 with two 5m closes.” Both sit beside rejection shorts and reclaim longs. These are quotations from the stored plans, not assertions that their conditions were satisfied. [A]')
p('The different LONDON pair changes emphasis: **row 69 S1** says “After the 01:00 CT sweep-up, 29243.75 RTH-H is support; any dip that prints 2×5m closes back above 29243.75 is a long.” **Row 182 S1** says “Price retests ONL 29123.25 and rejects with a 5m close below it; one-sided delivery continues.” The first day has **6 longs / 2 shorts (n=8)**; the second **4 / 9 (n=13)**. The comparison spans each day’s retained versions, not just these illustrative quotes. [A]')
p('The variation is **partly associated with declared day type**, as C6 quantifies, but cannot be attributed to that label alone. Market inputs, changing level locations, time, version selection and code evolution also differ. Calling the residual “arbitrary” would exceed this record. [B]')
p('## C6 · Day type and bias versus behavior')
p('Balance contains **337 fades / 506 scenarios**, trend **155 / 258**: **66.60% (n=506)** versus **60.08% (n=258)**, a descriptive difference of **6.52 percentage points**. Follow-family shares are **163/506** and **101/258**. The minor premium labels each contain **2 fades / 1 follow (n=3)**. Excluding ambiguous holds does not turn trend into an all-follow strategy. C1 gives every condition cell; '+link('supplement.json')+' `family_session_daytype` gives the session-stratified cells. [A/B]')
p('Equal weighting of retained versions rather than scenarios gives mean fade shares **67.78% across 156 balance versions** and **60.44% across 83 trend versions**; scenario denominators remain **506 and 258**. This sensitivity check reduces the influence of versions containing more scenarios, but does not make revisions independent or remove market confounding. Plan IDs are in '+link('supplement.json')+' `declared_type_per_plan`. [A]')
table(['Declared bias','Long scenarios','Short scenarios','n'],[[g,count(xs:=[x for x in real if x['bias']==g],'side','long'),count(xs,'side','short'),len(xs)] for g in sorted(set(x['bias'] for x in real))])
evidence('bias_vs_side')
p('**The label is contextual, not a hard strategy switch.** The record shows an association with play mix, so “purely decorative” is too strong; it does not prove the declaration causes a choice. There is no blanket `day_type=trend → no entry` in `trader/armed_executor.go:1878` or `trader/entry_gate.go:147`. Strict checks the cited scenario’s side; only `plan_mode=direction` directly enforces plan bias (`trader/entry_gate.go:201`, `trader/armed_executor.go:1891`). Thus **78 short scenarios under long bias and 87 long scenarios under short bias** are present (**165/770**), without contradicting strict’s current scenario-level contract. They do contradict reading a bias label as an unconditional direction instruction. [A/B]')
p('## C7 · Stops, targets and the shape of the trade')
p('Complete geometry means positive parent-arm entry, stop and target, with entry unequal to stop. There are **183/770** such scenarios, all enabled; **587/770** lack it. A separate sign check found **0 wrong-side parent stops/targets among those 183**. These are authored parent geometries, not every split leg and not broker-accepted protection. '+link('summary.json')+' `geometry_ids`, '+link('supplement.json')+' `geometry_side_errors`. [A]')
table(['Measure','n','25th percentile','Median','75th percentile','Range'],[[name,v['n'],f'{v["p25"]:.2f}',f'{v["median"]:.2f}',f'{v["p75"]:.2f}',f'{v["min"]:.2f}–{v["max"]:.2f}'] for name,key in [('Authored stop points','stop_pts'),('Authored stop / saved ATR5m','stop_atr'),('Authored arm target / initial authored risk','target_R'),('Eligible hold minutes','hold_minutes'),('Recorded filled initial-stop points','filled_initial_stop_pts')] for v in [S['dist'][key]]])
p('To cover **all executable leg geometries**, expand explicit entry legs instead of counting their parent twice: **15 split scenarios contribute 30 legs**, and **168 unsplit scenarios contribute 168 legs**, for **198 complete leg geometries**. All 198 stops are on the correct risk side. This is an authored-leg inventory, not 198 placed orders. The current one-contract guard limits actual placement regardless of a document containing two entry legs. [A: supplement.json `effective_legs`; armed_executor.go:327 and :984.]')
table(['Expanded arm-leg measure','n','25th percentile','Median','75th percentile','Range'],[[k,v['n'],f'{v["p25"]:.2f}',f'{v["median"]:.2f}',f'{v["p75"]:.2f}',f'{v["min"]:.2f}–{v["max"]:.2f}'] for k,v in U['effective_leg_stats'].items()])
p('Every expanded-leg statistic carries its full IDs in '+link('supplement.json')+' `effective_leg_stats`. **101/198** expanded authored stops lie below 1.5×saved ATR; this remains authored arithmetic, not the observed live stop-composition winner. Parent and expanded-leg distributions are both shown so repeated split entries cannot silently change the unit. [A]')
p('All distribution IDs are in '+link('summary.json')+' `dist`; filled-stop IDs are **trade_excursions.id**, linked to position IDs in '+link('excursions.json')+'. There are **60 excursion rows** attached to eligible positions, of which **49** have usable initial-stop prices; only **2/60** have positive entry ATR (excursion IDs **588,589**). These are insufficient to reconstruct a historical live-stop ATR distribution. [A]')
p('The current stop is the **widest** of authored stop, nearest risk-side seated anchor plus clearance, and ATR floor (`trader/arm_stop_anchor.go:71`). The measured boot resolves floor **1.5×ATR5m** and maximum anchor distance **3.0×ATR5m**; clearance is **2 ticks** from `kernel/min_sl.go:40`. The composition occurs before arm R:R validation (`trader/armed_executor.go:429`). Studio resolves the current R:R floor to **2** (`trader/armed_executor.go:69`, `:1914`; runtime.json `/api/config/resolved`). A farther stop may therefore invalidate a once-valid authored target. These are current rules, not a claim every historical authored geometry passed them. [A]')
p('**How often does the floor win instead of structure? Unanswerable from the retained record.** **98/183** authored stops are below 1.5×their saved ATR, but this does not say the live floor won: current live ATR can differ, a farther anchor can win, and stops are recomposed. `Bound` is not saved per historical acceptance. The log at `trader/armed_executor.go:432` prints selectively when changed or unanchored; it is not a complete denominator. Today’s retained examples show an **anchor winner at 17:01:20 CT** and an **authored winner at 17:21:16 CT** (runtime-log.json journal lines **29537,32566**); they do not establish a floor frequency. [A]')
p('Targets are not all a clean first-obstacle 2R trade. Across **183** complete geometries the arm target’s median is **2.33R**, but the first listed target-chain node is **strictly positive and below 1R in 72/183**, and **nonpositive in 3/183** when measured directionally from the arm entry. Those are authored nodes, not executed partial exits. IDs and signed R are in '+link('supplement.json')+' `first_target_below_one_R`, `first_target_nonpositive`. The arm target and first obstacle must not be conflated. [A]')
p('Eligible holds: **37/65 under 30 minutes**, **13/65 from 30 through 60**, **15/65 above 60**. All **65/65** entries are one contract; IDs are in '+link('supplement.json')+' `holds`, `quantity`. The median is **25.31 minutes**, with **12.22–55.41 minutes** covering the middle half. Extremes are position **597**, **1.192 seconds**, and **592**, **551.89 minutes**. Position 592’s long hold is not proof of an intended runner: the current source documents its historical protection incident (`trader/armed_executor.go:215`) and its stored exit was manual. No current open position was observed. [A]')
p('**Trader’s reading [B]:** level-to-level intraday trading, including short holds and longer intraday swings. “Scalp only” does not fit the longer holds; “runner system” is unsupported by the one-contract bracket and currently suspended BE/trailing mechanisms. Holding-time shape is descriptive and includes manual/forced exits and past operational failures, not just ideal intended trades.')
p('## C8 · What discretionary choices are actually implemented?')
table(['Question','Current mechanism / retained evidence','Verdict and limit'],[
['Stand aside on a trend day?','No day-type blanket veto in armed_executor.go:1878 or entry_gate.go:147; trend group contains 258 authored scenarios. Inactive/dormant plans cancel arms at armed_executor.go:239.','Refuted as a blanket trend-day rule. Specific gates can still stand aside.'],
['Pick ONE trade of the day?','one_contract.go:119 checks working entries/open positions; armed_executor.go:984 guards both placement paths and permits one placement per pass. Saved max_daily_trades=3 is disabled, master guardrails=false (config.json).','No daily best-trade selector. One simultaneous commitment is not one daily trade. C4 has multiple eligible fills on several dates.'],
['Size differently by conviction?','PlaceLimitEntry(..., side, 1, ...) at armed_executor.go:1069; current exit boot size=1. Eligible entry_quantity=1 for all 65 position IDs.','Refuted for current entry path and measured fills. The saved disabled max_contracts=2 is not current executable sizing.'],
['Move a stop after entry?','BE mechanism auto_trader.go:157; trail auto_trader_trailing.go:115. Both refuse before wire when exitMechsSuspended() is true, exit_mechs_suspend.go:35. Boot BE=off, trail=off at 18:11:54 CT.','Mechanisms exist but are currently suspended. Do not call historical stop movement impossible or infer current behavior from saved enabled=true.'],
['Take partials?','Current arm placement sends one contract with one stop and target; entry legs are not fractional exits. TCPTrader supports close quantity (trader/ninjatrader/tcp_trader.go:730), but that is not an automatic target-chain scale-out policy.','No automatic partial-plus-runner implementation demonstrated on this one-contract path; all 65 eligible entries are one contract. Target-chain nodes are plans, not partial-order receipts.'],
['Re-enter after a stop?','store/armed_orders.go:310 keeps a terminal row terminal under the same version; a new version can reauthorize. Boot-sweep exception may reauthorize same version. auto_trader_loop.go:361 explicitly recognizes post_exit rescan.','Possible after fresh authorization; not an unconditional same-setup loop. A stop-specific empirical reentry rate cannot be recovered from mutable arm history.'],
['Stop after N losses?','auto_trader_orders.go:112 reads ConsecutiveLossHalt; zero/absent is off. Field absent in saved config. Daily-loss and daily-trade limits also disabled.','Mechanism exists, currently off. No current N-loss-stop claim. Session caps are distinct and must not be substituted for it.'],
['Avoid first minutes or news?','auto_trader_session.go:27/:103 checks first 5 minutes, lunch and T1 windows for decision-path entries; orders.go:281 calls it. kernel/calendar_blackout.go:14 sets T1 ±15m. auto_trader_clock.go:675 cancels arms and flattens around T1 before armed management.','Mechanisms exist, but complete arm-path entry exclusion is NOT established: see the call-site limit below.']])
p('**Timing coverage limit [A/B]:** the strict arm path runs at `trader/auto_trader_loop.go:432`; `sessionEntryBlocked` is called from the decision-order path, not `entryGateForArm` (`trader/entry_gate.go:352`) or `runArmedPlacement` (`trader/armed_executor.go:952`). News cancellation/flattening is earlier at loop `:323`, but `enforceT1ForceFlatAt` returns false when flat and there was no cancel work (`trader/auto_trader_clock.go:708`), allowing the cycle to continue. The inspected path therefore does **not prove an unconditional first-five-minute/lunch/news ban on fresh arms**. No live placement was induced to test this. A code mechanism or a painted band is not proof every entry path is blocked.')
p('A concrete observation reinforces the narrower lunch conclusion: accepted-risk rows **21/22** first observe the same order at **8 September 2026 12:54:19 CT**, inside the code’s **12:00–13:30 CT** lunch band (`kernel/no_trade_band.go:42`). This is acceptance evidence, not reconstructed exact submission time. The saved `blackout_enabled=false` is a separate risk-control setting; it does not erase the session/news functions just traced. Current session trade caps **ASIA=7, LONDON=10, NY=10** resolve from per-session saved settings and are checked in `trader/auto_trader_session.go:81`; the same call-path limitation applies to claiming they cover arms. [A]')
p('## D · Verdict, differences from the system’s words, and unanswered questions')
p('**D1 — Strategy:** Your system repeatedly maps named intraday references and proposes both a failed-break fade and a break/reclaim continuation. The retained proposals favor fades and shorts, but allow either side. The current strict executor turns only enabled, permitted scenario geometry into a one-contract order after its gates and broker-book checks. It uses a protective bracket and current fixed-stop/fixed-target posture, with lifecycle and scheduled forced exits. This is a level-based intraday strategy family, not proof of a profitable edge. [B, supported by C1–C8.]')
p('**D2 — Consistency:** Same vocabulary, different daily composition. The session ratios and all **49** session-day rows show the variation; the defined **280-pair** comparison ranges from **0.208** to **0.705**. Balance/trend mix differs modestly, and both remain fade-heavy (**337/506**, **155/258**). Neither “identical every day” nor “random changes” is supported. [A/B: C5–C6.]')
p('**D3 — Three discretionary differences:** (1) no single daily best-trade selection: competing authored scenarios plus mechanical admission; (2) no current conviction sizing: one contract; (3) no demonstrated automatic partial-plus-runner management: one-contract brackets, BE/trail suspended. These describe the choices a discretionary trader *could* exercise and this implementation does not currently exercise; they do not claim all discretionary traders behave the same way. [A/B: C8.]')
table(['D4 · Words in the system','What the evidence supports'],[
['Saved prompt: “avoid … sideways oscillation”; custom note “No trade inside sideway zone”.','506/770 authored scenarios carry a balance-family label. Balance is not a universal stand-aside label; this does not prove every entry was inside a precisely defined forbidden zone (that zone is not retained). C1/C6; config.json.'],
['Saved frequency prompt: “2-4 trades per day”; “Single position holding time ≥ 30-60 minutes”.','Not hard current daily/hold constraints. C4 records plan-date fill counts including 10 on 20 August (IDs in that row); 37/65 holds were below 30 minutes. Code/current config has no enabled daily=one/three rule.'],
['Saved frequency prompt: “50 point move stop loss to breakeven”.','Saved knob is 40 points, but runtime suspension prevents both BE and trail. Neither prompt 50 nor saved 40 describes current wire behavior. config.json; exit-runtime.json; exit_mechs_suspend.go:35.'],
['Saved entry prompt: avoid “immediately restarting after closing positions”.','post_exit rescan is explicit at auto_trader_loop.go:361. Fresh-version reauthorization exists; no blanket post-close stand-down can be inferred. Rescan itself is not a fill.'],
['Plan bias interpreted as a one-way instruction.','165/770 authored scenarios oppose non-neutral declared bias. Strict validates scenario direction; direction mode is the separate bias gate. C6.'],
['“Trend day” interpreted as continuation-only or a day to sit out.','155 fade-family scenarios among 258 trend-labelled scenarios; no direct blanket trend veto found. C6/C8.'],
['Guide scenario quality: “INFORMATIONAL — nothing gates on it” (web/src/guide/content/planCard.ts:96).','Overbroad: the code supports a min_scenario_quality gate at armed_executor.go:1898. Current missing setting resolves C, so current A+/A/B/C labels all satisfy it. It is not a measured win probability.'],
['Guide says “lunch 11:30–13:30 ET → no entries” (web/src/guide/content/plays.ts:231).','That is 10:30–12:30 CT, whereas kernel/no_trade_band.go:42 defines 12:00–13:30 CT. Further, complete arm-path enforcement is not established; accepted rows 21/22 are at 12:54:19 CT.'],
['Guide no-trade-band prose: “Three sources, all of them enforcing” (web/src/guide/content/planCard.ts:101).','Decision-path mechanisms exist, and news cancels/flat exists. The claim about every armed entry is stronger than the inspected call sites support. C8.'],
['Guide target-chain / runner language (web/src/guide/content/plays.ts:45, :221).','183 complete geometries have a target-chain description, but that is not a partial ladder. 72/183 first nodes lie at positive <1R and 3/183 are nonpositive from entry; all 65 eligible fills are one contract. C7.'],
['Grade described as “trustworthy” (web/src/guide/content/levels.ts:12).','The audit counts labels and selected levels; it does not calibrate their reliability or identify a preferred level. No edge inference is justified.'],
['Settings Guide describes BE and trailing as suspended (web/src/guide/content/settings.ts:401, :419).','Supported by the current exit boot; this is not a contradiction. Saved enabled flags alone would misdescribe behavior.']])
p('D4 is exhaustive for the concrete prompt/Guide/label claims examined above, **not a claim to have audited every sentence of the entire Guide**. No published research ranking or previous audit performance claim is imported as evidence of this system’s edge.')
p('**D5 — What cannot be answered from this retained record:** exact model-input price/time for every version; exact historical machine regime attached to each version; every placement timestamp; every historical arm authorization/cancel/rearm because rows are mutable; every non-arm reason; whether an anchor touch would have passed full confirmation and all gates; exact live floor-versus-anchor stop winner frequency; complete broker-accepted stop/target histories; an empirical stop-specific reentry rate; the causal effect of day-type declarations versus changing markets; calibrated grade reliability; the effect of a different strategy, target or threshold; and profitability. The CSV/JSON missing fields and enumerated unmatched/unknown subsets define those limits. These are evidence gaps, not proposed strategy changes.')
p('## Source freshness and provenance')
files=['docs/superpowers/SYSTEM-MAP.md','docs/superpowers/AUDIT-CHECKLIST.md','docs/superpowers/research/2026-09-08-trading-policy/README.md','docs/superpowers/reports/2026-09-04-two-day-audit.md','store/attribution.go','kernel/plan_doc.go','kernel/levels_role.go','store/strategy.go','store/armed_orders.go','trader/armed_executor.go','trader/entry_gate.go','trader/arm_stop_anchor.go','kernel/min_sl.go','kernel/condition_status.go','trader/one_contract.go','trader/auto_trader.go','trader/auto_trader_trailing.go','trader/exit_mechs_suspend.go','trader/auto_trader_loop.go','trader/auto_trader_orders.go','trader/auto_trader_session.go','trader/auto_trader_clock.go','kernel/calendar_blackout.go','kernel/no_trade_band.go','trader/ninjatrader/tcp_trader.go','web/src/guide/content/plays.ts','web/src/guide/content/planCard.ts','web/src/guide/content/levels.ts','web/src/guide/content/settings.ts']
prov=[]
for f in files:
 log=subprocess.check_output(['git','log','-1','--format=%H %cI %s','--',f],text=True).strip();prov.append({'file':f,'command':f'git log -1 --format="%H %cI %s" -- "{f}"','output':log})
f='docs/superpowers/reports/2026-09-07-planner-preparation-audit/README.md'
prov.append({'file':f,'command':f'git log -1 6095ca58 --format="%H %cI %s" -- "{f}"','output':subprocess.check_output(['git','log','-1','6095ca58','--format=%H %cI %s','--',f],text=True).strip(),'note':'Read pinned blob; absent from current dev tree.'})
(P/'provenance.json').write_text(json.dumps(prov,indent=2)+'\n')
p('The following are literal `git log -1 --format="%H %cI %s" -- "<file>"` outputs for the source at the report worktree HEAD. The planner-audit command additionally pins `6095ca58`, as stated above. Source line references refer to that inspected tree. Generated evidence files have source queries and row IDs instead of fictitious preexisting git history. Machine-readable commands/output: '+link('provenance.json')+'.')
for r in prov:p('`'+r['file']+'`\n\n```text\n'+r['output']+'\n```')
p('## Validation and publication record')
p('Validation commands and artifact fingerprints: '+link('validate.py')+' and '+link('validation.json')+'.')
p('Offline validation checked complete scenario totals, all condition/session/day-type marginals, unique scenario keys, arm and position joins, geometry signs, duplicate accepted-risk receipts, missing-value denominators and artifact privacy. Product tests were not run: this is a documentation/evidence-only change and executes no trading code. The source snapshot and current runtime are deliberately distinguished from historical behavior. Final publication verification is recorded in the PR and owner closeout using a commit-pinned report URL and byte-size/hash comparison; no branch-path fetch is treated as pinned evidence.')
(P.parent/'2026-09-08-the-strategy.md').write_text('\n'.join(parts).rstrip()+'\n')
print('report bytes', (P.parent/'2026-09-08-the-strategy.md').stat().st_size)
