// VL i18n Consolidation - Translation Keys
// Generated by Atlas Orchestrator
// Branch: feat/i18n-consolidation-patch
// Purpose: Centralize scattered i18n strings from 8 strategy components

// ============================================================================
// COIN SOURCE TRANSLATIONS (40 keys)
// ============================================================================
export const coinSource = {
  sourceType: {
    zh: '数据源类型（static）',
    en: 'Source Type (static)',
    es: 'Tipo de fuente (static)',
  },
  static: { zh: '静态列表', en: 'Static List', es: 'Lista Estática' },
  staticCoins: {
    zh: '静态币种列表',
    en: 'Static Coin List',
    es: 'Lista Estática de Monedas',
  },
  addCoin: { zh: '添加品种', en: 'Add Symbol', es: 'Agregar Símbolo' },
  staticDesc: {
    zh: '静态币种列表 — 仅当数据源类型为 static 时使用',
    en: 'Static coin list — used only when Source Type = static',
    es: 'Lista estática — usada solo cuando Source Type = static',
  },
  maxCoins: { zh: '最多', en: 'Up to', es: 'Hasta' },
  coins: { zh: '个品种', en: 'symbols', es: 'símbolos' },
  dataSourceConfig: {
    zh: '数据源配置',
    en: 'Data Source Configuration',
    es: 'Configuración de Fuente',
  },
  excludedCoins: {
    zh: '排除品种',
    en: 'Excluded Symbols',
    es: 'Símbolos Excluidos',
  },
  excludedCoinsDesc: {
    zh: '从所有品种来源中过滤（static）',
    en: 'Filtered out from all coin sources (static)',
    es: 'Filtradas de todas las fuentes (static)',
  },
  addExcludedCoin: {
    zh: '添加排除',
    en: 'Add Excluded',
    es: 'Agregar Excluida',
  },
  oiIncreaseShort: { zh: 'OI增', en: 'OI↑', es: 'OI↑' },
  oiDecreaseShort: { zh: 'OI减', en: 'OI↓', es: 'OI↓' },
  custom: { zh: '自定义', en: 'Custom', es: 'Personalizado' },
  excludedNone: { zh: '无', en: 'None', es: 'Ninguno' },
  oiIncreaseTitle: { zh: 'OI 持仓增加榜', en: 'OI Increase', es: 'OI Aumento' },
  oiDecreaseTitle: {
    zh: 'OI 持仓减少榜',
    en: 'OI Decrease',
    es: 'OI Disminución',
  },
  oiIncreaseLabel: { zh: 'OI 增加', en: 'OI Increase', es: 'OI Aumento' },
  forLong: { zh: '适合做多', en: 'For long', es: 'Para largo' },
  oiDecreaseLabel: { zh: 'OI 减少', en: 'OI Decrease', es: 'OI Disminución' },
  forShort: { zh: '适合做空', en: 'For short', es: 'Para corto' },
}

// ============================================================================
// GRID CONFIG TRANSLATIONS (60+ keys)
// ============================================================================
export const gridConfig = {
  tradingPair: {
    zh: '交易设置',
    en: 'Trading Setup',
    es: 'Configuración de Trading',
  },
  gridParameters: {
    zh: '网格参数',
    en: 'Grid Parameters',
    es: 'Parámetros de Grid',
  },
  priceBounds: { zh: '价格边界', en: 'Price Bounds', es: 'Límites de Precio' },
  riskControl: { zh: '风险控制', en: 'Risk Control', es: 'Control de Riesgo' },
  symbol: { zh: '交易对', en: 'Trading Pair', es: 'Par de Trading' },
  symbolDesc: {
    zh: '选择要进行网格交易的交易对',
    en: 'Select trading pair for grid trading',
    es: 'Seleccionar par para grid trading',
  },
  totalInvestment: {
    zh: '投资金额',
    en: 'Investment',
    es: 'Inversión',
  },
  totalInvestmentDesc: {
    zh: '网格策略的总投资金额',
    en: 'Total investment for grid strategy',
    es: 'Inversión total',
  },
  leverage: { zh: '杠杆倍数', en: 'Leverage', es: 'Apalancamiento' },
  leverageDesc: {
    zh: '交易使用的杠杆倍数 (1-20)',
    en: 'Leverage for trading (1-20)',
    es: 'Apalancamiento (1-20)',
  },
  gridCount: { zh: '网格数量', en: 'Grid Count', es: 'Cantidad de Grids' },
  gridCountDesc: {
    zh: '网格层级数量 (5-50)',
    en: 'Number of grid levels (5-50)',
    es: 'Niveles (5-50)',
  },
  distribution: { zh: '资金分配方式', en: 'Distribution', es: 'Distribución' },
  distributionDesc: {
    zh: '网格层级的资金分配方式',
    en: 'Fund allocation across grid levels',
    es: 'Asignación de fondos',
  },
  uniform: { zh: '均匀分配', en: 'Uniform', es: 'Uniforme' },
  gaussian: {
    zh: '高斯分配 (推荐)',
    en: 'Gaussian (Recommended)',
    es: 'Gaussiana (Recomendado)',
  },
  pyramid: { zh: '金字塔分配', en: 'Pyramid', es: 'Pirámide' },
  useAtrBounds: {
    zh: '自动计算边界 (ATR)',
    en: 'Auto-calculate Bounds (ATR)',
    es: 'Calcular Límites (ATR)',
  },
  useAtrBoundsDesc: {
    zh: '基于 ATR 自动计算网格上下边界',
    en: 'Auto-calculate bounds based on ATR',
    es: 'Calcular límites automáticamente',
  },
  atrMultiplier: {
    zh: 'ATR 倍数',
    en: 'ATR Multiplier',
    es: 'Multiplicador ATR',
  },
  atrMultiplierDesc: {
    zh: 'ATR 倍数 — 用于边界计算（默认 2.0）',
    en: 'ATR multiplier for bound calculation (default 2.0)',
    es: 'Multiplicador ATR para calcular límites (por defecto 2.0)',
  },
  upperPrice: { zh: '上边界价格', en: 'Upper Price', es: 'Precio Superior' },
  upperPriceDesc: {
    zh: '网格上边界价格 (0 = 从 ATR 自动计算)',
    en: 'Grid upper bound (0 = auto-calculate from ATR)',
    es: 'Límite superior (0 = auto desde ATR)',
  },
  lowerPrice: { zh: '下边界价格', en: 'Lower Price', es: 'Precio Inferior' },
  lowerPriceDesc: {
    zh: '网格下边界价格 (0 = 从 ATR 自动计算)',
    en: 'Grid lower bound (0 = auto-calculate from ATR)',
    es: 'Límite inferior (0 = auto desde ATR)',
  },
  maxDrawdown: {
    zh: '最大回撤 (%)',
    en: 'Max Drawdown (%)',
    es: 'Máximo Drawdown (%)',
  },
  maxDrawdownDesc: {
    zh: '触发紧急退出的最大回撤百分比',
    en: 'Max drawdown before emergency exit',
    es: 'Drawdown máximo',
  },
  stopLoss: { zh: '止损 (%)', en: 'Stop Loss (%)', es: 'Stop Loss (%)' },
  stopLossDesc: {
    zh: '单仓位止损百分比',
    en: 'Stop loss per position',
    es: 'Stop loss por posición',
  },
  dailyLossLimit: {
    zh: '日损失限制 (%)',
    en: 'Daily Loss Limit (%)',
    es: 'Límite Diario (%)',
  },
  dailyLossLimitDesc: {
    zh: '每日最大亏损百分比',
    en: 'Maximum daily loss percentage',
    es: 'Pérdida diaria máxima',
  },
  useMakerOnly: {
    zh: '仅使用 Maker 订单',
    en: 'Maker Only Orders',
    es: 'Solo Maker',
  },
  useMakerOnlyDesc: {
    zh: '使用限价单以降低手续费',
    en: 'Use limit orders for lower fees',
    es: 'Órdenes límite para menos fees',
  },
  directionAdjust: {
    zh: '方向自动调整',
    en: 'Direction Auto-Adjust',
    es: 'Ajuste Automático de Dirección',
  },
  enableDirectionAdjust: {
    zh: '启用方向调整',
    en: 'Enable Direction Adjust',
    es: 'Habilitar Ajuste',
  },
  enableDirectionAdjustDesc: {
    zh: '根据箱体突破自动调整网格方向',
    en: 'Auto-adjust grid direction based on box breakouts',
    es: 'Ajustar según breaks',
  },
  directionBiasRatio: {
    zh: '偏向强度（long_bias/short_bias，默认 0.7 = 70%/30%）',
    en: 'Bias Strength (long_bias/short_bias modes, default 0.7 = 70%/30%)',
    es: 'Intensidad de Sesgo (modos long/short, por defecto 0.7)',
  },
  directionBiasRatioDesc: {
    zh: '偏多/偏空模式的强度',
    en: 'Strength for long_bias/short_bias modes',
    es: 'Fuerza del sesgo',
  },
  directionBiasExplain: {
    zh: '偏多模式：X%买 + (100-X)%卖 | 偏空模式：(100-X)%买 + X%卖',
    en: 'Long bias: X% buy + (100-X)% sell | Short bias: (100-X)% buy + X% sell',
    es: 'Sesgo largo: X% compra | Sesgo corto: X% venta',
  },
  directionExplain: {
    zh: '短期箱体突破 → 偏向，中期箱体突破 → 全仓，价格回归 → 逐步恢复中性',
    en: 'Short box breakout → bias, Mid box breakout → full, Price return → gradually recover to neutral',
    es: 'Break corto → sesgo, Break medio → full',
  },
  directionModes: {
    zh: '方向模式说明',
    en: 'Direction Modes',
    es: 'Descripción de Modos',
  },
  modeNeutral: {
    zh: '中性：50%买 + 50%卖（默认）',
    en: 'Neutral: 50% buy + 50% sell (default)',
    es: 'Neutral: 50% compra + 50% venta',
  },
  modeLongBias: {
    zh: '偏多：X%买 + (100-X)%卖',
    en: 'Long Bias: X% buy + (100-X)% sell',
    es: 'Sesgo Largo: X% compra',
  },
  modeLong: {
    zh: '全多：100%买 + 0%卖',
    en: 'Long: 100% buy + 0% sell',
    es: 'Largo: 100% compra',
  },
  modeShortBias: {
    zh: '偏空：(100-X)%买 + X%卖',
    en: 'Short Bias: (100-X)% buy + X% sell',
    es: 'Sesgo Corto: X% venta',
  },
  modeShort: {
    zh: '全空：0%买 + 100%卖',
    en: 'Short: 0% buy + 100% sell',
    es: 'Corto: 100% venta',
  },
  buy: { zh: '买', en: 'buy', es: 'compra' },
  sell: { zh: '卖', en: 'sell', es: 'venta' },
}

// ============================================================================
// GRID RISK TRANSLATIONS (50 keys)
// ============================================================================
export const gridRisk = {
  gridRisk: { zh: '网格风控', en: 'Grid Risk', es: 'Riesgo de Grid' },
  leverageInfo: { zh: '杠杆', en: 'Leverage', es: 'Apalancamiento' },
  positionInfo: { zh: '仓位', en: 'Position', es: 'Posición' },
  liquidationInfo: { zh: '清算', en: 'Liquidation', es: 'Liquidación' },
  marketState: { zh: '市场', en: 'Market', es: 'Mercado' },
  boxState: { zh: '箱体', en: 'Box', es: 'Caja' },
  currentLeverage: { zh: '当前', en: 'Current', es: 'Actual' },
  effectiveLeverage: { zh: '有效', en: 'Effective', es: 'Efectivo' },
  recommendedLeverage: { zh: '建议', en: 'Recommend', es: 'Recomendado' },
  currentPosition: { zh: '当前', en: 'Current', es: 'Actual' },
  maxPosition: { zh: '最大', en: 'Max', es: 'Máximo' },
  positionPercent: { zh: '占比', en: 'Usage', es: 'Uso' },
  liquidationPrice: { zh: '清算价', en: 'Liq Price', es: 'Precio Liquidación' },
  liquidationDistance: { zh: '距离', en: 'Distance', es: 'Distancia' },
  regimeLevel: { zh: '波动', en: 'Regime', es: 'Regulación' },
  currentPrice: { zh: '价格', en: 'Price', es: 'Precio' },
  breakoutLevel: { zh: '突破', en: 'Breakout', es: 'Breakout' },
  breakoutDirection: { zh: '方向', en: 'Direction', es: 'Dirección' },
  shortBox: { zh: '短期', en: 'Short', es: 'Corto' },
  midBox: { zh: '中期', en: 'Mid', es: 'Medio' },
  longBox: { zh: '长期', en: 'Long', es: 'Largo' },
  narrow: { zh: '窄幅', en: 'Narrow', es: 'Estrecho' },
  standard: { zh: '标准', en: 'Standard', es: 'Estándar' },
  wide: { zh: '宽幅', en: 'Wide', es: 'Ancho' },
  volatile: { zh: '剧烈', en: 'Volatile', es: 'Volátil' },
  trending: { zh: '趋势', en: 'Trending', es: 'Tendencia' },
  none: { zh: '无', en: 'None', es: 'Ninguno' },
  short: { zh: '短期', en: 'Short', es: 'Corto' },
  mid: { zh: '中期', en: 'Mid', es: 'Medio' },
  long: { zh: '长期', en: 'Long', es: 'Largo' },
  up: { zh: '↑', en: '↑', es: '↑' },
  down: { zh: '↓', en: '↓', es: '↓' },
  loading: { zh: '加载中...', en: 'Loading...', es: 'Cargando...' },
  error: { zh: '加载失败', en: 'Load Failed', es: 'Error al Cargar' },
  noData: { zh: '暂无数据', en: 'No Data', es: 'Sin Datos' },
}

// ============================================================================
// RISK CONTROL TRANSLATIONS (25+ keys)
// ============================================================================
export const riskControl = {
  positionLimits: {
    zh: '仓位限制',
    en: 'Position Limits',
    es: 'Límites de Posición',
  },
  maxPositions: {
    zh: '最大持仓数量',
    en: 'Max Positions',
    es: 'Máximo de Posiciones',
  },
  maxPositionsDesc: {
    zh: '同时持有的最大持仓数量',
    en: 'Maximum positions held simultaneously',
    es: 'Posiciones máximas simultáneas',
  },
  tradingLeverage: {
    zh: '交易杠杆（交易所杠杆）',
    en: 'Trading Leverage (Exchange)',
    es: 'Apalancamiento (Exchange)',
  },
  btcEthLeverage: {
    zh: 'BTC/ETH 交易杠杆',
    en: 'BTC/ETH Trading Leverage',
    es: 'BTC/ETH Apalancamiento',
  },
  btcEthLeverageDesc: {
    zh: '交易所开仓杠杆（AI 指导；保存时钳制到 1–20）',
    en: 'Exchange leverage for opening positions (AI-guided; save clamps it to 1–20)',
    es: 'Apalancamiento del exchange (guía AI; guardado fija 1–20)',
  },
  altcoinLeverage: {
    zh: '山寨币交易杠杆',
    en: 'Altcoin Trading Leverage',
    es: 'Apalancamiento Altcoins',
  },
  altcoinLeverageDesc: {
    zh: '交易所开仓杠杆（AI 指导；保存时钳制到 1–20）',
    en: 'Exchange leverage for opening positions (AI-guided; save clamps it to 1–20)',
    es: 'Apalancamiento del exchange (guía AI; guardado fija 1–20)',
  },
  positionValueRatio: {
    zh: '仓位价值比例（代码强制）',
    en: 'Position Value Ratio (CODE ENFORCED)',
    es: 'Ratio de Valor (CÓDIGO)',
  },
  positionValueRatioDesc: {
    zh: '单仓位名义价值 / 账户净值，由代码强制执行',
    en: 'Position notional value / equity, enforced by code',
    es: 'Valor nominal / equity',
  },
  btcEthPositionValueRatio: {
    zh: 'BTC/ETH 仓位价值比例',
    en: 'BTC/ETH Position Value Ratio',
    es: 'BTC/ETH Ratio de Valor',
  },
  btcEthPositionValueRatioDesc: {
    zh: '单仓最大名义价值 = 净值 × 此值（代码强制，默认 5）',
    en: 'Max position value = equity × this ratio (CODE ENFORCED, default 5)',
    es: 'Valor máximo = equity × ratio (CÓDIGO, por defecto 5)',
  },
  altcoinPositionValueRatio: {
    zh: '山寨币仓位价值比例',
    en: 'Altcoin Position Value Ratio',
    es: 'Altcoin Ratio de Valor',
  },
  altcoinPositionValueRatioDesc: {
    zh: '单仓最大名义价值 = 净值 × 此值（代码强制，默认 1）',
    en: 'Max position value = equity × this ratio (CODE ENFORCED, default 1)',
    es: 'Valor máximo = equity × ratio (CÓDIGO, por defecto 1)',
  },
  riskParameters: {
    zh: '风险参数',
    en: 'Risk Parameters',
    es: 'Parámetros de Riesgo',
  },
  minRiskReward: {
    zh: '最小风险回报比',
    en: 'Min Risk/Reward Ratio',
    es: 'Ratio Riesgo/Recompensa Mínimo',
  },
  minRiskRewardDesc: {
    zh: '开仓要求的最低盈亏比',
    en: 'Minimum profit ratio for entry',
    es: 'Ratio mínimo para entrada',
  },
  maxMarginUsage: {
    zh: '最大保证金使用率（AI 提示，非强制）',
    en: 'Max Margin Usage (AI-guided, not enforced)',
    es: 'Uso Máximo de Margen (guía AI)',
  },
  maxMarginUsageDesc: {
    zh: '保证金使用率上限（AI 提示，非代码强制）',
    en: 'Max margin utilization — AI-guided hint, not code-enforced',
    es: 'Uso máximo de margen (guía AI, no forzado)',
  },
  entryRequirements: {
    zh: '开仓要求',
    en: 'Entry Requirements',
    es: 'Requisitos de Entrada',
  },
  minPositionSize: {
    zh: '最小开仓金额',
    en: 'Min Position Size',
    es: 'Tamaño Mínimo',
  },
  minPositionSizeDesc: {
    zh: '最小名义价值',
    en: 'Minimum notional value',
    es: 'Valor mínimo',
  },
  // CME futures settle in USD — the futures variant below replaces the legacy crypto-perp description.
  minPositionSizeDescFutures: {
    zh: 'USD 最小名义价值',
    en: 'Minimum notional value in USD',
    es: 'Valor mínimo en USD',
  },
  minConfidence: {
    zh: '最小信心度',
    en: 'Min Confidence',
    es: 'Confianza Mínima',
  },
  minConfidenceDesc: {
    zh: 'AI 开仓信心度阈值',
    en: 'AI confidence threshold for entry',
    es: 'Umbral de confianza AI',
  },

  // === Hold discipline (hold-lock) ===
  holdDiscipline: {
    zh: '持仓纪律（锁仓）',
    en: 'Hold discipline (hold-lock)',
    es: 'Disciplina de retención',
  },
  holdDisciplineDesc: {
    zh: '开启后：持仓期间禁止 AI 提前平仓，交易只按 AI 设定的止损/止盈（交易所挂单）离场；紧急平仓与回撤监控不受影响。在 ai_watch 持仓模式下这是真正生效的底线保护（观察员只记录、无下单权限，此开关拦截任何 AI 平仓）。默认关闭。',
    en: 'When ON: once in a position, the AI cannot close early — the trade rides to the stop/target the AI set (a real order resting at the exchange). Only AI closes are gated; Emergency Flat and the drawdown monitor bypass it. In ai_watch position mode this is the ACTIVE bottom-rail protection: the observer only records (zero order authority) and this switch blocks any AI close. Default OFF.',
    es: 'Cuando está ON: en posición, la IA no cierra antes; la operación va al stop/objetivo. Solo los cierres de IA se bloquean; Flat de emergencia y el monitor de drawdown lo ignoran. En modo ai_watch es la protección de fondo activa (el observador solo registra). Por defecto OFF.',
  },

  // === Auto-breakeven ===
  breakeven: {
    zh: '止损移至保本',
    en: 'Move stop to breakeven',
    es: 'Mover stop a equilibrio',
  },
  breakevenDesc: {
    zh: '当浮盈达到设定点数后，把止损移到开仓价（保本）。仅期货 (NT8)。默认关闭。SUSPENDED (0B) — 当前运行中该功能已暂停，开启后不会移动止损。',
    en: 'Move the stop to your entry (breakeven) after N points in profit. Futures (NT8) only. Default OFF. SUSPENDED (0B) — the running binary does not move the stop.',
    es: 'Mueve el stop a la entrada tras N puntos. Solo futuros (NT8). OFF por defecto. SUSPENDIDO (0B) — el binario en ejecución no mueve el stop.',
  },
  breakevenTrigger: {
    zh: '触发点数',
    en: 'Trigger (points)',
    es: 'Disparador (puntos)',
  },

  // === Trailing profit (Phase 3B) ===
  trailing: {
    zh: '移动止盈（追踪止损）',
    en: 'Trailing profit (trailing stop)',
    es: 'Trailing stop',
  },
  trailingDesc: {
    zh: '设计行为：按 最优价 ∓ 倍数×ATR(周期,5m) 逐级收紧止损。仅期货 (NT8)。默认关闭。SUSPENDED (0B) — 计算仍会产生新价位，但不会发到交易所（见 auto_trader_trailing.go）。',
    en: 'Designed: the stop ratchets to best-price ∓ mult×ATR(period, 5m), tighten-only. Futures (NT8) only. Default OFF. SUSPENDED (0B) — the ratchet computes a new level but the broker is never moved (auto_trader_trailing.go).',
    es: 'Diseñado: el stop se ajusta a mejor-precio ∓ mult×ATR. Solo futuros (NT8). OFF por defecto. SUSPENDIDO (0B) — el ratchet calcula pero el broker nunca se mueve.',
  },
  trailingMult: {
    zh: 'ATR 倍数',
    en: 'ATR multiple',
    es: 'Múltiplo ATR',
  },
  trailingPeriod: {
    zh: 'ATR 周期 (5m)',
    en: 'ATR period (5m)',
    es: 'Período ATR (5m)',
  },
  trailingArm: {
    zh: '启动条件',
    en: 'Arms',
    es: 'Se activa',
  },
  trailingArmBE: {
    zh: '保本触发后（默认）',
    en: 'after breakeven (default)',
    es: 'tras breakeven (defecto)',
  },
  trailingArmPts: {
    zh: '浮盈达到点数',
    en: 'after N points in profit',
    es: 'tras N puntos',
  },
  trailingArmNow: {
    zh: '立即',
    en: 'immediately',
    es: 'inmediato',
  },

  alwaysActive: {
    zh: '始终生效（安全）',
    en: 'always active (safety)',
    es: 'siempre activo (seguridad)',
  },

  // === Strategy Studio Phase 1 — prop-firm guardrails (Chunk 6) ===
  guardrailsTitle: {
    zh: '防护栏（Prop-Firm 规则）',
    en: 'Prop-Firm Guardrails',
    es: 'Barreras Prop-Firm',
  },
  guardrailsDesc: {
    zh: '硬性闸门：触发即阻止新开仓并记录原因；关闭则跳过（记录）。永不影响实盘账户拦截。',
    en: 'Hard gates: each blocks new entries + logs when tripped; off = skipped (logged). Never affects the live-account block.',
    es: 'Puertas duras: bloquean nuevas entradas + registran; off = omitido. No afecta el bloqueo de cuenta real.',
  },
  masterSwitch: {
    zh: '风险防护栏总开关',
    en: 'Risk guardrails',
    es: 'Barreras de riesgo',
  },
  masterSwitchDesc: {
    zh: '关闭则全部防护栏停用（记录）；实盘账户拦截始终生效，不可关闭。',
    en: 'OFF disables ALL guardrails (logged). The live-account block stays ON always — untoggleable.',
    es: 'OFF desactiva TODAS las barreras. El bloqueo de cuenta real siempre activo.',
  },
  dailyLossLimit: {
    zh: '每日亏损上限 (USD) — 默认开启；留空则取环境变量 RISK_MAX_DAILY_LOSS_USD',
    en: 'Daily loss limit (USD) — default ON; a blank value falls back to env RISK_MAX_DAILY_LOSS_USD',
    es: 'Límite de pérdida diaria (USD) — ON por defecto; vacío usa RISK_MAX_DAILY_LOSS_USD',
  },
  dailyProfitTarget: {
    zh: '每日盈利目标 (USD) — 默认关闭',
    en: 'Daily profit target (USD) — default OFF',
    es: 'Objetivo de ganancia diaria (USD) — OFF por defecto',
  },
  maxDailyTrades: {
    zh: '每日最大开仓次数 — 默认关闭',
    en: 'Max daily trades — entries per CME session-day; default OFF',
    es: 'Máx. operaciones diarias — OFF por defecto',
  },
  consecutiveLossHalt: {
    zh: '连续亏损熔断 (N 笔后停止开仓) — 存在感知：留空 = 继承（默认 8，开启）；显式 0 = 关闭；不受总开关控制',
    en: 'Consecutive-loss halt (stop after N losers) — presence-aware: blank = inherit (shipped default 8, ON); explicit 0 = OFF; NOT gated by the master switch',
    es: 'Freno por pérdidas seguidas (parar tras N) — presencia: vacío = hereda (8, ON); 0 explícito = OFF; no lo controla el master',
  },
  reentryCooldown: {
    zh: '止损后再入场冷却 (分钟, 或价格离止损 ≥1×ATR15) — 默认 20；0 = 关闭；不受总开关控制',
    en: 'Re-entry cooldown after stop (min, or ≥1×ATR15 from stop) — default 20; 0 = OFF; NOT gated by the master switch',
    es: 'Enfriamiento de reingreso tras stop (min, o ≥1×ATR15) — por defecto 20; 0 = OFF; no lo controla el master',
  },
  maxContractsField: {
    zh: '单笔最大合约数 — 默认 2（常开钳制；旧开关从未有读取方）',
    en: 'Max contracts / order — default 2 (always-on clamp; the old toggle never had a reader)',
    es: 'Máx. contratos / orden — por defecto 2 (tope siempre activo)',
  },
  notionalCapField: {
    zh: '名义上限倍数 (权益×N) — 默认 20（安全底线，开关默认开启）',
    en: 'Notional cap (equity × N) — default 20 (safety backstop, toggle default ON)',
    es: 'Tope nocional (capital × N) — por defecto 20 (respaldo, ON)',
  },
  blackoutStart: {
    zh: '禁止交易开始 (CT) — 开关默认关闭；窗口内不做新决策（NT8 侧 SL/TP 仍保护持仓）',
    en: 'Blackout start (CT) — toggle default OFF; inside [start,end] CT no new decisions (NT8-side SL/TP still protect positions)',
    es: 'Inicio bloqueo (CT) — OFF por defecto; sin decisiones dentro de la ventana (SL/TP en NT8 siguen)',
  },
  blackoutEnd: {
    zh: '禁止交易结束 (CT) — 窗口按 America/Chicago 时间',
    en: 'Blackout end (CT) — window times are America/Chicago',
    es: 'Fin bloqueo (CT) — horario America/Chicago',
  },
  consistencyPctField: {
    zh: '一致性上限 — 单日已实现盈利 ≤ 历史总盈利的此 %（默认关闭；需有前日盈利才生效）',
    en: 'Consistency cap — a CME session-day may realize at most this % of all-time total realized profit (default OFF; needs prior-day profit to trigger)',
    es: 'Consistencia — un día ≤ este % del total histórico (OFF por defecto; requiere ganancia previa)',
  },
  futuresRiskTitle: {
    zh: '期货风险（每笔，约值）',
    en: 'Futures Risk (per trade, est.)',
    es: 'Riesgo Futuros (por op., est.)',
  },
  estContracts: {
    zh: '约合合约数',
    en: 'Est. contracts',
    es: 'Contratos est.',
  },
  dollarRisk: {
    zh: '每笔风险 ($)',
    en: '$ risk / trade',
    es: 'Riesgo $ / op.',
  },
  marginPerContract: {
    zh: '保证金/合约 (约)',
    en: 'Margin / contract (est.)',
    es: 'Margen / contrato',
  },
  toggleOn: { zh: '开', en: 'On', es: 'On' },
  toggleOff: { zh: '关', en: 'Off', es: 'Off' },
  // W1 (g) — the short labels on a card's effective chips when one card holds
  // a switch AND its value (the chip itself is the server's row).
  effOnOff: { zh: '开关', en: 'on/off', es: 'on/off' },
  effValue: { zh: '数值', en: 'value', es: 'valor' },
}

// ============================================================================
// PROMPT SECTIONS TRANSLATIONS (12+ keys)
// ============================================================================
export const promptSections = {
  promptSections: {
    zh: 'System Prompt 自定义',
    en: 'System Prompt Customization',
    es: 'Personalización de Prompt',
  },
  promptSectionsDesc: {
    zh: '自定义 AI 行为和决策逻辑（输出格式和风控规则不可修改）',
    en: 'Customize AI behavior and decision logic (output format and risk rules are fixed)',
    es: 'Personalizar comportamiento AI',
  },
  roleDefinition: {
    zh: '角色定义',
    en: 'Role Definition',
    es: 'Definición de Rol',
  },
  roleDefinitionDesc: {
    zh: '定义 AI 的身份和核心目标（System Prompt 可编辑段落）',
    en: 'Define AI identity and core objectives (editable System Prompt section)',
    es: 'Definir identidad AI (sección editable del System Prompt)',
  },
  tradingFrequency: {
    zh: '交易频率',
    en: 'Trading Frequency',
    es: 'Frecuencia de Trading',
  },
  tradingFrequencyDesc: {
    zh: '设定交易频率预期和过度交易警告',
    en: 'Set trading frequency expectations and overtrading warnings',
    es: 'Establecer frecuencia',
  },
  entryStandards: {
    zh: '开仓标准',
    en: 'Entry Standards',
    es: 'Estándares de Entrada',
  },
  entryStandardsDesc: {
    zh: '定义开仓信号条件和避免事项（System Prompt 可编辑段落）',
    en: 'Define entry signal conditions and avoidances (editable System Prompt section)',
    es: 'Definir señales de entrada (sección editable del System Prompt)',
  },
  decisionProcess: {
    zh: '决策流程',
    en: 'Decision Process',
    es: 'Proceso de Decisión',
  },
  decisionProcessDesc: {
    zh: '设定决策步骤和思考流程（System Prompt 可编辑段落）',
    en: 'Set decision steps and thinking process (editable System Prompt section)',
    es: 'Establecer proceso (sección editable del System Prompt)',
  },
  resetToDefault: {
    zh: '重置为默认',
    en: 'Reset to Default',
    es: 'Restablecer',
  },
  chars: { zh: '字符', en: 'chars', es: 'caracteres' },
  modified: { zh: '已修改', en: 'Modified', es: 'Modificado' },
}

// ============================================================================
// INDICATOR TRANSLATIONS (75+ keys)
// ============================================================================
export const indicator = {
  marketData: { zh: '市场数据', en: 'Market Data', es: 'Datos de Mercado' },
  marketDataDesc: {
    zh: 'AI 分析所需的核心价格数据',
    en: 'Core price data for AI analysis',
    es: 'Datos de precio esenciales',
  },
  technicalIndicators: {
    zh: '技术指标',
    en: 'Technical Indicators',
    es: 'Indicadores Técnicos',
  },
  technicalIndicatorsDesc: {
    zh: '可选的技术分析指标，AI 可自行计算',
    en: 'Optional indicators, AI can calculate them',
    es: 'Indicadores opcionales',
  },
  marketSentiment: {
    zh: '市场情绪',
    en: 'Market Sentiment',
    es: 'Sentimiento de Mercado',
  },
  marketSentimentDesc: {
    zh: '持仓量、资金费率等市场情绪数据',
    en: 'OI, funding rate and market sentiment data',
    es: 'OI, funding rate',
  },
  // CME futures have no funding rate — subtitle drops it (OI still applies).
  marketSentimentDescFutures: {
    zh: '持仓量等市场情绪数据',
    en: 'OI and market sentiment data',
    es: 'OI y sentimiento de mercado',
  },
  timeframes: { zh: '时间周期', en: 'Timeframes', es: 'Marcos de Tiempo' },
  timeframesDesc: {
    zh: '选择 K 线分析周期，★ 为主周期（双击设置）',
    en: 'Select K-line timeframes, ★ = primary (double-click)',
    es: 'Seleccionar timeframes',
  },
  klineCount: { zh: 'K 线数量', en: 'K-line Count', es: 'Cantidad de Velas' },
  scalp: { zh: '超短', en: 'Scalp', es: 'Scalp' },
  intraday: { zh: '日内', en: 'Intraday', es: 'Intradía' },
  swing: { zh: '波段', en: 'Swing', es: 'Swing' },
  position: { zh: '趋势', en: 'Position', es: 'Posición' },
  rawKlines: {
    zh: 'OHLCV 原始 K 线',
    en: 'Raw OHLCV K-lines',
    es: 'Velas OHLCV',
  },
  rawKlinesDesc: {
    zh: 'OHLCV 原始 K 线 — 始终启用，AI 分析必需（编辑器挂载时强制开启）',
    en: 'Raw OHLCV klines — always enabled, required for AI analysis (force-set on mount)',
    es: 'Velas OHLCV — siempre activas, requeridas para el análisis de IA (se fuerzan al montar)',
  },
  required: { zh: '必须', en: 'Required', es: 'Requerido' },
  ema: { zh: 'EMA 均线', en: 'EMA', es: 'EMA' },
  emaDesc: {
    zh: '指数移动平均线块（默认周期 20, 50）',
    en: 'Exponential Moving Average block (default periods 20, 50)',
    es: 'Media Móvil Exponencial (periodos por defecto 20, 50)',
  },
  macd: { zh: 'MACD', en: 'MACD', es: 'MACD' },
  macdDesc: {
    zh: 'MACD 块（开/关）',
    en: 'MACD block (on/off)',
    es: 'Bloque MACD (on/off)',
  },
  rsi: { zh: 'RSI', en: 'RSI', es: 'RSI' },
  rsiDesc: {
    zh: '相对强弱指标块（默认周期 7, 14）',
    en: 'Relative Strength Index block (default periods 7, 14)',
    es: 'Índice de Fuerza Relativa (periodos por defecto 7, 14)',
  },
  atr: { zh: 'ATR', en: 'ATR', es: 'ATR' },
  atrDesc: {
    zh: '真实波幅均值块（默认周期 14）',
    en: 'Average True Range block (default period 14)',
    es: 'Rango Promedio Verdadero (periodo por defecto 14)',
  },
  boll: { zh: 'BOLL 布林带', en: 'Bollinger Bands', es: 'Bandas de Bollinger' },
  bollDesc: {
    zh: '布林带块（默认周期 20；标准差倍率固定为 2）',
    en: 'Bollinger Bands block (default period 20; std-dev multiplier fixed at 2)',
    es: 'Bandas de Bollinger (periodo 20; multiplicador de desviación fijo en 2)',
  },
  svp: {
    zh: 'SVP 成交量分布',
    en: 'Volume Profile (SVP)',
    es: 'Perfil de Volumen (SVP)',
  },
  svpDesc: {
    zh: '当日/前一日 RTH 成交量分布：POC + 价值区(VAH/VAL)，加入期货 AI 提示词（默认关闭）',
    en: 'RTH volume-at-price: POC + value area (VAH/VAL), added to the futures AI prompt (default OFF)',
    es: 'Volumen por precio RTH: POC + área de valor (VAH/VAL), al prompt de IA de futuros (OFF por defecto)',
  },
  volume: { zh: '成交量', en: 'Volume', es: 'Volumen' },
  volumeDesc: {
    zh: '成交量分布块（开/关）',
    en: 'Volume profile block (on/off)',
    es: 'Bloque de perfil de volumen (on/off)',
  },
  oi: { zh: '持仓量', en: 'Open Interest', es: 'Interés Abierto' },
  oiDesc: {
    zh: '持仓量块（开/关）',
    en: 'Open-interest block (on/off)',
    es: 'Bloque de interés abierto (on/off)',
  },
  fundingRate: { zh: '资金费率', en: 'Funding Rate', es: 'Funding Rate' },
  fundingRateDesc: {
    zh: '资金费率块（开/关）',
    en: 'Funding-rate block (on/off)',
    es: 'Bloque de tasa de financiación (on/off)',
  },
  oiRanking: { zh: 'OI 排行', en: 'OI Ranking', es: 'Ranking OI' },
  oiRankingDesc: {
    zh: '持仓量增减排行',
    en: 'OI change ranking',
    es: 'Cambios de OI',
  },
  oiRankingNote: {
    zh: '显示持仓量增加/减少的币种排行，帮助发现资金流向',
    en: 'Shows coins with OI increase/decrease, helps identify capital flow',
    es: 'Identificar flujo de capital',
  },
  priceRankingNote: {
    zh: '显示涨幅/跌幅排行，结合资金流和持仓变化分析趋势强度',
    en: 'Shows top gainers/losers, combined with fund flow and OI for trend analysis',
    es: 'Analizar fuerza de tendencia',
  },
  priceRankingMulti: { zh: '多周期', en: 'Multi-period', es: 'Multi-período' },
  duration: { zh: '周期', en: 'Duration', es: 'Duración' },
  limit: { zh: '数量', en: 'Limit', es: 'Límite' },
  aiCanCalculate: {
    zh: '💡 提示：AI 可自行计算这些指标，开启可减少 AI 计算量',
    en: '💡 Tip: AI can calculate these, enabling reduces AI workload',
    es: '💡 AI puede calcularlos',
  },
  viewApiDocs: { zh: 'API 文档', en: 'API Docs', es: 'Docs API' },
  apiKey: { zh: 'API Key', en: 'API Key', es: 'API Key' },
  fillDefault: { zh: '填入默认', en: 'Fill Default', es: 'Llenar Default' },
  connected: { zh: '已配置', en: 'Configured', es: 'Configurado' },
  notConfigured: { zh: '未配置', en: 'Not Configured', es: 'No Configurado' },
}

// ============================================================================
// PUBLISH SETTINGS TRANSLATIONS (8 keys)
// ============================================================================
export const publishSettings = {
  publishToMarket: {
    zh: '发布到策略市场',
    en: 'Publish to Market',
    es: 'Publicar al Mercado',
  },
  publishDesc: {
    zh: '策略将在市场公开展示，其他用户可发现并使用',
    en: 'Strategy will be publicly visible in the marketplace',
    es: 'Visible públicamente',
  },
  showConfig: { zh: '公开配置参数', en: 'Show Config', es: 'Mostrar Config' },
  showConfigDesc: {
    zh: '允许他人查看和复制详细配置',
    en: 'Allow others to view and clone config details',
    es: 'Permitir clonación',
  },
  private: { zh: '私有', en: 'PRIVATE', es: 'PRIVADO' },
  public: { zh: '公开', en: 'PUBLIC', es: 'PÚBLICO' },
  hidden: { zh: '隐藏', en: 'HIDDEN', es: 'OCULTO' },
  visible: { zh: '可见', en: 'VISIBLE', es: 'VISIBLE' },
}

// ============================================================================
// CHART TABS TRANSLATIONS (5 keys)
// ============================================================================
export const chartTabs = {
  crypto: { zh: '加密', en: 'Crypto', es: 'Cripto' },
  stocks: { zh: '美股', en: 'Stocks', es: 'Acciones' },
  forex: { zh: '外汇', en: 'Forex', es: 'Forex' },
  metals: { zh: '金属', en: 'Metals', es: 'Metales' },
  ninjatrader: { zh: 'NT', en: 'NT', es: 'NT' },
}

// ============================================================================
// HELPER FUNCTION
// ============================================================================

export function ts(
  entry: { zh: string; en: string; [k: string]: string },
  lang: string
): string {
  return entry[lang] ?? entry.en ?? ''
}

// ============================================================================
// AGGREGATED EXPORTS FOR TRANSLATIONS.TS
// ============================================================================

export const zhStrategy = {
  ...Object.fromEntries(Object.entries(coinSource).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(Object.entries(gridConfig).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(Object.entries(gridRisk).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(Object.entries(riskControl).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(
    Object.entries(promptSections).map(([k, v]) => [k, v.zh])
  ),
  ...Object.fromEntries(Object.entries(indicator).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(
    Object.entries(publishSettings).map(([k, v]) => [k, v.zh])
  ),
  ...Object.fromEntries(Object.entries(chartTabs).map(([k, v]) => [k, v.zh])),
}

export const enStrategy = {
  ...Object.fromEntries(Object.entries(coinSource).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(Object.entries(gridConfig).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(Object.entries(gridRisk).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(Object.entries(riskControl).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(
    Object.entries(promptSections).map(([k, v]) => [k, v.en])
  ),
  ...Object.fromEntries(Object.entries(indicator).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(
    Object.entries(publishSettings).map(([k, v]) => [k, v.en])
  ),
  ...Object.fromEntries(Object.entries(chartTabs).map(([k, v]) => [k, v.en])),
}

export const esStrategy = {
  ...Object.fromEntries(Object.entries(coinSource).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(Object.entries(gridConfig).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(Object.entries(gridRisk).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(Object.entries(riskControl).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(
    Object.entries(promptSections).map(([k, v]) => [k, v.es])
  ),
  ...Object.fromEntries(Object.entries(indicator).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(
    Object.entries(publishSettings).map(([k, v]) => [k, v.es])
  ),
  ...Object.fromEntries(Object.entries(chartTabs).map(([k, v]) => [k, v.es])),
}
