package store

// knobRegistry classifies every schema leaf. Status is EVIDENCE-DERIVED, not
// guessed: a knob is live only when a consumer outside store/ actually reads its
// Go field, and every live entry carries that file:line. The audit's dead knobs
// are hand-marked with the reason they cannot take effect — which is a DIFFERENT
// test from "has no consumer", and the 2026-09-03 sweep proved neither subsumes
// the other (7 audit-dead knobs DO have consumers; the grep found ~14 more with
// none that the audit never named).
var knobRegistry = map[string]KnobEntry{
	"buffer_points":                    {Path: "buffer_points", Status: KnobLive, Consumers: []string{"store/structural_geometry.go:ResolveStructuralStop", "trader/armed_executor.go:composeArmStop"}, Note: "Research buffer beyond frozen zone; missing uncalibrated value refuses."},
	"round_trip_cost_points":           {Path: "round_trip_cost_points", Status: KnobLive, Consumers: []string{"store/structural_geometry.go:ResolveStructuralStop", "trader/structural_geometry.go:ComposeLevelFadeGeometry"}, Note: "Point costs for complete round trip; baseline owner research assumption 2 points."},
	"acceptance_rule":                  {Path: "acceptance_rule", Status: KnobFolded, Consumers: []string{"store/strategy.go:AcceptanceRuleFor (returns the one rule)"}, Note: "W-KNOB-PRUNE 2026-09-18: one rule exists (1×5m close); the resolver already mapped every stored vocabulary onto it since 2026-08-30. Dropdown removed; a stored other value is logged and never takes effect."},
	"ai500_limit":                      {Path: "ai500_limit", Status: KnobLive, Consumers: []string{"kernel/engine.go:448"}, Note: ""},
	"altcoin_max_leverage":             {Path: "altcoin_max_leverage", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:552"}, Note: ""},
	"altcoin_max_position_value_ratio": {Path: "altcoin_max_position_value_ratio", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:554"}, Note: ""},
	"approval_required":                {Path: "approval_required", Status: KnobLive, Consumers: []string{"trader/auto_trader_planconfig.go:155"}, Note: ""},
	"atr_multiplier":                   {Path: "atr_multiplier", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid_levels.go:35"}, Note: ""},
	"atr_periods":                      {Path: "atr_periods", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:791"}, Note: ""},
	"blackout_enabled":                 {Path: "blackout_enabled", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:188"}, Note: ""},
	"blackout_end_ct":                  {Path: "blackout_end_ct", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:167"}, Note: ""},
	"blackout_start_ct":                {Path: "blackout_start_ct", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:167"}, Note: ""},
	"boll_periods":                     {Path: "boll_periods", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:792"}, Note: ""},
	"breakdown":                        {Path: "breakdown", Status: KnobLive, Consumers: []string{"kernel/plan_confirm.go:190"}, Note: ""},
	"breakeven_enabled":                {Path: "breakeven_enabled", Status: KnobLive, Consumers: []string{"trader/auto_trader.go:196"}, Note: ""},
	"breakeven_trigger_points":         {Path: "breakeven_trigger_points", Status: KnobLive, Consumers: []string{"trader/auto_trader.go:199"}, Note: ""},
	"btc_eth_max_leverage":             {Path: "btc_eth_max_leverage", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:551"}, Note: ""},
	"btc_eth_max_position_value_ratio": {Path: "btc_eth_max_position_value_ratio", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:553"}, Note: ""},
	"condition_status":                 {Path: "condition_status", Status: KnobLive, Consumers: []string{"trader/auto_trader_planner.go:1481"}, Note: ""},
	"config":                           {Path: "config", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid_regime.go:157"}, Note: ""},
	"config_visible":                   {Path: "config_visible", Status: KnobLive, Consumers: []string{"api/strategy.go:44"}, Note: ""},
	"consecutive_loss_halt":            {Path: "consecutive_loss_halt", Status: KnobLive, Consumers: []string{"trader/auto_trader_orders.go:116"}, Note: ""},
	"consistency_enabled":              {Path: "consistency_enabled", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:196"}, Note: ""},
	"consistency_max_day_pct":          {Path: "consistency_max_day_pct", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:169"}, Note: ""},
	"context_limit":                    {Path: "context_limit", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"created_at":                       {Path: "created_at", Status: KnobLive, Consumers: []string{"trader/auto_trader_calendar.go:36"}, Note: ""},
	"custom_prompt":                    {Path: "custom_prompt", Status: KnobLive, Consumers: []string{"kernel/engine_prompt_futures.go:257"}, Note: ""},
	"daily_loss_enabled":               {Path: "daily_loss_enabled", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:157"}, Note: ""},
	"daily_loss_limit_pct":             {Path: "daily_loss_limit_pct", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid.go:187"}, Note: ""},
	"daily_loss_limit_usd":             {Path: "daily_loss_limit_usd", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:158"}, Note: ""},
	"daily_profit_enabled":             {Path: "daily_profit_enabled", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:160"}, Note: ""},
	"daily_profit_target_usd":          {Path: "daily_profit_target_usd", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:161"}, Note: ""},
	"data_path":                        {Path: "data_path", Status: KnobLive, Consumers: []string{"kernel/engine.go:815"}, Note: ""},
	"decision_process":                 {Path: "decision_process", Status: KnobLive, Consumers: []string{"kernel/engine_prompt_futures.go:213"}, Note: ""},
	"description":                      {Path: "description", Status: KnobLive, Consumers: []string{"api/strategy.go:76"}, Note: ""},
	"direction_bias_ratio":             {Path: "direction_bias_ratio", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid_levels.go:103"}, Note: ""},
	"distribution":                     {Path: "distribution", Status: KnobLive, Consumers: []string{"kernel/grid_engine.go:153"}, Note: ""},
	"ema_periods":                      {Path: "ema_periods", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:789"}, Note: ""},
	"enable":                           {Path: "enable", Status: KnobLive, Consumers: []string{"trader/auto_trader_planconfig.go:73"}, Note: ""},
	"enable_atr":                       {Path: "enable_atr", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:241"}, Note: ""},
	"enable_boll":                      {Path: "enable_boll", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:249"}, Note: ""},
	"enable_direction_adjust":          {Path: "enable_direction_adjust", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid_regime.go:65"}, Note: ""},
	"enable_ema":                       {Path: "enable_ema", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:221"}, Note: ""},
	"enable_funding_rate":              {Path: "enable_funding_rate", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:265"}, Note: ""},
	"enable_macd":                      {Path: "enable_macd", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:229"}, Note: ""},
	"enable_multi_timeframe":           {Path: "enable_multi_timeframe", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:209"}, Note: ""},
	"enable_netflow_ranking":           {Path: "enable_netflow_ranking", Status: KnobLive, Consumers: []string{"kernel/engine.go:966"}, Note: ""},
	"enable_oi":                        {Path: "enable_oi", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:261"}, Note: ""},
	"enable_oi_ranking":                {Path: "enable_oi_ranking", Status: KnobLive, Consumers: []string{"kernel/engine.go:935"}, Note: ""},
	"enable_price_ranking":             {Path: "enable_price_ranking", Status: KnobLive, Consumers: []string{"kernel/engine.go:998"}, Note: ""},
	"enable_quant_data":                {Path: "enable_quant_data", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:276"}, Note: ""},
	"enable_quant_netflow":             {Path: "enable_quant_netflow", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:965"}, Note: ""},
	"enable_quant_oi":                  {Path: "enable_quant_oi", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:965"}, Note: ""},
	"enable_raw_klines":                {Path: "enable_raw_klines", Status: KnobLive, Consumers: []string{"agent/skill_management_handlers.go:1197"}, Note: ""},
	"enable_rsi":                       {Path: "enable_rsi", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:233"}, Note: ""},
	"enable_svp":                       {Path: "enable_svp", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:328"}, Note: ""},
	"enable_volume":                    {Path: "enable_volume", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:257"}, Note: ""},
	"entry_standards":                  {Path: "entry_standards", Status: KnobLive, Consumers: []string{"kernel/engine_prompt_futures.go:203"}, Note: ""},
	"eod_flat_offset_min":              {Path: "eod_flat_offset_min", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"evening_digest":                   {Path: "evening_digest", Status: KnobFolded, Consumers: []string{"trader/auto_trader_planconfig.go:eveningDigestEnabled → store.DayPlanConfig.EveningDigestOn"}, Note: "W-KNOB-PRUNE 2026-09-18: constant OFF unless a stored true; every live strategy stores true (honoured, logged once). Toggle removed."},
	"excluded_coins":                   {Path: "excluded_coins", Status: KnobLive, Consumers: []string{"kernel/engine.go:613"}, Note: ""},
	"external_data_sources":            {Path: "external_data_sources", Status: KnobIneffective, Consumers: nil, Note: "zero engine consumers"},
	"fixed_overhead":                   {Path: "fixed_overhead", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"grid_config":                      {Path: "grid_config", Status: KnobLive, Consumers: []string{"trader/auto_trader_decision.go:108"}, Note: ""},
	"grid_count":                       {Path: "grid_count", Status: KnobLive, Consumers: []string{"kernel/grid_engine.go:153"}, Note: ""},
	"guardrails_enabled":               {Path: "guardrails_enabled", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:153"}, Note: ""},
	"headers":                          {Path: "headers", Status: KnobLive, Consumers: []string{"kernel/engine.go:795"}, Note: ""},
	"hold_discipline":                  {Path: "hold_discipline", Status: KnobLive, Consumers: []string{"trader/auto_trader_orders.go:84"}, Note: ""},
	"htf_veto":                         {Path: "htf_veto", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"hyper_main_limit":                 {Path: "hyper_main_limit", Status: KnobLive, Consumers: []string{"kernel/engine.go:527"}, Note: ""},
	"id":                               {Path: "id", Status: KnobLive, Consumers: []string{"kernel/plan_confirm.go:372"}, Note: ""},
	"indicators":                       {Path: "indicators", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:328"}, Note: ""},
	"is_active":                        {Path: "is_active", Status: KnobLive, Consumers: []string{"api/handler_user.go:411"}, Note: ""},
	"is_default":                       {Path: "is_default", Status: KnobLive, Consumers: []string{"api/strategy.go:126"}, Note: ""},
	"is_public":                        {Path: "is_public", Status: KnobLive, Consumers: []string{"api/strategy.go:43"}, Note: ""},
	"klines":                           {Path: "klines", Status: KnobLive, Consumers: []string{"kernel/stale_data.go:74"}, Note: ""},
	"language":                         {Path: "language", Status: KnobLive, Consumers: []string{"kernel/engine.go:384"}, Note: ""},
	"last_entry_offset_min":            {Path: "last_entry_offset_min", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"level":                            {Path: "level", Status: KnobLive, Consumers: []string{"kernel/plan_confirm.go:192"}, Note: ""},
	"levels_fresh_by_tf":               {Path: "levels_fresh_by_tf", Status: KnobFolded, Consumers: []string{"trader/auto_trader_dayplan.go installLevelStateProvider HTF branch (S2 2026-09-16)"}, Note: "W-KNOB-PRUNE 2026-09-18: verdict REMOVE (S4c: freshness separates nothing) but the owner's MNQ strategy stores true — code path kept, stored value honoured + logged once, toggle removed. Delete the grader once the owner clears it."},
	"leverage":                         {Path: "leverage", Status: KnobLive, Consumers: []string{"kernel/grid_engine.go:153"}, Note: ""},
	"longer_count":                     {Path: "longer_count", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"longer_timeframe":                 {Path: "longer_timeframe", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:773"}, Note: ""},
	"lower_price":                      {Path: "lower_price", Status: KnobLive, Consumers: []string{"kernel/grid_engine.go:283"}, Note: ""},
	"max_contracts_enabled":            {Path: "max_contracts_enabled", Status: KnobIneffective, Consumers: nil, Note: "parse-only (strategy.go)"},
	"max_contracts_per_order":          {Path: "max_contracts_per_order", Status: KnobLive, Consumers: []string{"trader/auto_trader_orders.go:57"}, Note: ""},
	"max_daily_trades":                 {Path: "max_daily_trades", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:164"}, Note: ""},
	"max_daily_trades_enabled":         {Path: "max_daily_trades_enabled", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:163"}, Note: ""},
	"max_drawdown_pct":                 {Path: "max_drawdown_pct", Status: KnobLive, Consumers: []string{"kernel/formatter.go:162"}, Note: ""},
	"max_levels":                       {Path: "max_levels", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:366"}, Note: ""},
	"htf_seats":                        {Path: "htf_seats", Status: KnobLive, Consumers: []string{"kernel/levels_score.go seatHTF (S3)"}, Note: "0-6, nil=2"},
	"flip_reread":                      {Path: "flip_reread", Status: KnobLive, Consumers: []string{"trader/auto_trader_planner.go maybeRereadAfterFlip (W-FLIP-REREAD)"}, Note: "false=OFF (legacy dormant)"},
	"death_reread":                     {Path: "death_reread", Status: KnobLive, Consumers: []string{"trader/death_reread.go maybeRereadAfterDeath + deathBornWickActive (W-DEATH-REREAD)"}, Note: "owner ruling 2026-09-18 12:3x CT 'fix all' — nil=true (ON, default): a fired death line goes dormant AND launches ONE budgeted re-read (spends class-35 replan budget); explicit false=OFF (today byte-identical, dormant only)."},
	"geometry_reference_levels":        {Path: "geometry_reference_levels", Status: KnobLive, Consumers: []string{"kernel/planner_prompt.go EnsureReferenceLevelIDs (map ids)", "trader/auto_trader_planner.go write-site stamp", "trader/structural_geometry.go resolveEntryGeometryZone via ComposeLevelFadeGeometryWith (executor tf wildcard + null-width reference-line admission)", "trader/one_setup_wiring.go oneSetupLevelRef (consult)", "trader/write_time_feasibility.go composeArmStop context GeometryRefIDs (W-WRITE-TIME-FEASIBILITY write site)"}, Note: "W-GEOMETRY-REFUSAL 2026-09-18 — owner ruling 'both fix now': nil=ON (default) assigns stable ids to reference levels with unknown formation close + empty source tf wildcard; explicit false=OFF (today byte-identical)."},
	"t1_currencies":                    {Path: "t1_currencies", Status: KnobLive, Consumers: []string{"trader/auto_trader_calendar.go t1WindowsFor (arm gate)", "trader/auto_trader_planner.go plannerT1Lines (plan write)", "trader/fade_facts.go fadeFactsAt (InT1Blackout)", "kernel/planner_prompt.go Calendar section"}, Note: "via T1CurrenciesFor(): empty=[USD] (shipped default, W-T1-CURRENCIES 2026-09-18); ALL/* = every currency hard-blocks (pre-wave behaviour); other T1 events are advisory lines only."},
	"max_margin_usage":                 {Path: "max_margin_usage", Status: KnobIneffective, Consumers: nil, Note: "prompt text only \u2014 advisory, never a gate (engine_prompt.go)"},
	"max_notional_leverage":            {Path: "max_notional_leverage", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:557"}, Note: ""},
	"max_positions":                    {Path: "max_positions", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:131"}, Note: ""},
	"max_trades":                       {Path: "max_trades", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"method":                           {Path: "method", Status: KnobLive, Consumers: []string{"kernel/engine.go:790"}, Note: ""},
	"min_confidence":                   {Path: "min_confidence", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:556"}, Note: ""},
	"min_grade":                        {Path: "min_grade", Status: KnobLive, Consumers: []string{"trader/auto_trader_planner.go:1994"}, Note: ""},
	"min_position_size":                {Path: "min_position_size", Status: KnobIneffective, Consumers: nil, Note: "crypto path hardcodes 12/60 (engine_position.go)"},
	"min_risk_reward_ratio":            {Path: "min_risk_reward_ratio", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:555"}, Note: ""},
	"min_scenario_quality":             {Path: "min_scenario_quality", Status: KnobLive, Consumers: []string{"kernel/engine_position.go:300"}, Note: ""},
	"model_limits":                     {Path: "model_limits", Status: KnobLive, Consumers: []string{"api/strategy.go:384"}, Note: ""},
	"name":                             {Path: "name", Status: KnobLive, Consumers: []string{"kernel/no_trade_band.go:91"}, Note: ""},
	"netflow_ranking_duration":         {Path: "netflow_ranking_duration", Status: KnobLive, Consumers: []string{"kernel/engine.go:970"}, Note: ""},
	"netflow_ranking_limit":            {Path: "netflow_ranking_limit", Status: KnobLive, Consumers: []string{"kernel/engine.go:975"}, Note: ""},
	"nofxos_api_key":                   {Path: "nofxos_api_key", Status: KnobLive, Consumers: []string{"kernel/engine.go:343"}, Note: ""},
	"notional_cap_enabled":             {Path: "notional_cap_enabled", Status: KnobIneffective, Consumers: nil, Note: "parse-only (strategy.go)"},
	"oi_low_limit":                     {Path: "oi_low_limit", Status: KnobLive, Consumers: []string{"kernel/engine.go:488"}, Note: ""},
	"oi_ranking_duration":              {Path: "oi_ranking_duration", Status: KnobLive, Consumers: []string{"kernel/engine.go:939"}, Note: ""},
	"oi_ranking_limit":                 {Path: "oi_ranking_limit", Status: KnobLive, Consumers: []string{"kernel/engine.go:944"}, Note: ""},
	"oi_top_limit":                     {Path: "oi_top_limit", Status: KnobLive, Consumers: []string{"kernel/engine.go:468"}, Note: ""},
	"plan_enabled":                     {Path: "plan_enabled", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:365"}, Note: ""},
	"plan_mode":                        {Path: "plan_mode", Status: KnobLive, Consumers: []string{"trader/entry_gate.go:160"}, Note: ""},
	"fade_or_wide_k":                   {Path: "fade_or_wide_k", Status: KnobLive, Consumers: []string{"trader/fade_facts.go:155"}, Note: "W2 LABEL knob: sets exclusion (a)'s k; changes what is RECORDED, never what is armed. Zero = C5 default 1.28."},
	"one_setup_enabled":                {Path: "one_setup_enabled", Status: KnobLive, Consumers: []string{"store/resolve_source.go:ResolveOneSetup", "trader/one_setup_wiring.go:oneSetupConfig"}, Note: "ONE SETUP (dispatch 102): nil=ON [O]; false restores the wide book byte-identically (E2). Gates arm AUTHORIZATION only — never cancels, never places."},
	"one_setup_min_grade":              {Path: "one_setup_min_grade", Status: KnobLive, Consumers: []string{"store/resolve_source.go:ResolveOneSetup", "kernel/one_setup.go:OneSetupBestCandidate"}, Note: "ONE SETUP: the lowest grade the best level near price may carry; empty=B [O]."},
	"picture_htf":                      {Path: "picture_htf", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved", "trader/picture_htf_evaluator.go (W-PICTURE-HTF)"}, Note: "W-PICTURE-HTF 2026-09-19: the owner's two-picture method as a deterministic SIM entry mode (4H body levels → H1 close break → next-5m entry). nil=OFF. Engineering-default knobs, not researched optimums."},
	"day_plan.picture_htf.enabled":              {Path: "picture_htf.enabled", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved"}, Note: "picture_htf master switch; false = OFF (the mode must print its readiness honestly, never 'active')."},
	"day_plan.picture_htf.tick_size":            {Path: "picture_htf.tick_size", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved"}, Note: "one instrument tick (default 0.25 MNQ); the H1 close must cross by at least one tick."},
	"day_plan.picture_htf.pivot_window":         {Path: "picture_htf.pivot_window", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved"}, Note: "latest N completed 4H candles for body-pivot discovery (default 120)."},
	"day_plan.picture_htf.swing_lookback":       {Path: "picture_htf.swing_lookback", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved"}, Note: "preceding N completed 5m candles for the structural swing stop (default 24)."},
	"day_plan.picture_htf.entry_window_sec":     {Path: "picture_htf.entry_window_sec", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved"}, Note: "submission allowed within N seconds of the new 5m interval (default 10)."},
	"day_plan.picture_htf.freshness_sec":        {Path: "picture_htf.freshness_sec", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved"}, Note: "max accepted age of the freshest bar frame at evaluation and send (default 2s)."},
	"day_plan.picture_htf.min_rr":               {Path: "picture_htf.min_rr", Status: KnobLive, Consumers: []string{"store/strategy.go:PictureHtfResolved"}, Note: "0 = the strategy's configured minimum R:R; the nearest eligible zone is never skipped to fix R:R."},
	"structure_map":                    {Path: "structure_map", Status: KnobFolded, Consumers: []string{"store/resolve_source.go:ResolveStructureMap", "trader/structure_map_wire.go:structureMapForRead", "kernel/structure_map.go:RenderStructureSection"}, Note: "W-KNOB-PRUNE 2026-09-18: advisory STRUCTURE table (D/4h/1h bias only, never a gate), default OFF until R25; toggle removed, the owner's stored true is honoured + logged once."},
	"planner_model":                    {Path: "planner_model", Status: KnobLive, Consumers: []string{"trader/auto_trader_planner.go:71"}, Note: ""},
	"planner_timeframes":               {Path: "planner_timeframes", Status: KnobLive, Consumers: []string{"trader/auto_trader_planner.go:1990"}, Note: ""},
	"price_ranking_duration":           {Path: "price_ranking_duration", Status: KnobLive, Consumers: []string{"kernel/engine.go:1002"}, Note: ""},
	"price_ranking_limit":              {Path: "price_ranking_limit", Status: KnobLive, Consumers: []string{"kernel/engine.go:1007"}, Note: ""},
	"primary_count":                    {Path: "primary_count", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:764"}, Note: ""},
	"primary_timeframe":                {Path: "primary_timeframe", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:763"}, Note: ""},
	"prompt_variant":                   {Path: "prompt_variant", Status: KnobLive, Consumers: []string{"trader/auto_trader_loop.go:546"}, Note: ""},
	"proximity_filter_atr":             {Path: "proximity_filter_atr", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:375"}, Note: ""},
	"publish_config":                   {Path: "publish_config", Status: KnobLive, Consumers: []string{"api/strategy.go:42"}, Note: ""},
	"quant_data":                       {Path: "quant_data", Status: KnobLive, Consumers: []string{"kernel/engine.go:858"}, Note: ""},
	"realign_cap":                      {Path: "realign_cap", Status: KnobFolded, Consumers: []string{"trader/auto_trader_planconfig.go:RealignCap → store.DayPlanConfig.RealignCapResolved", "api/handler_plan.go realign endpoint"}, Note: "W-KNOB-PRUNE 2026-09-18: folded into the re-plan section — constant 5 unless stored (the owner stores 10, honoured + logged). Control removed."},
	"reentry_cooldown_minutes":         {Path: "reentry_cooldown_minutes", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:619"}, Note: ""},
	"refresh_secs":                     {Path: "refresh_secs", Status: KnobLive, Consumers: []string{"kernel/engine.go:782"}, Note: ""},
	"replan_cap":                       {Path: "replan_cap", Status: KnobLive, Consumers: []string{"trader/auto_trader_reset.go:112"}, Note: ""},
	"role_definition":                  {Path: "role_definition", Status: KnobLive, Consumers: []string{"kernel/engine_prompt_futures.go:99"}, Note: ""},
	"rsi_periods":                      {Path: "rsi_periods", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:790"}, Note: ""},
	"scenario_cap":                     {Path: "scenario_cap", Status: KnobFolded, Consumers: []string{"trader/auto_trader_planconfig.go:scenarioCap → store.DayPlanConfig.ScenarioCapResolved", "kernel/planner_prompt.go plannerOutputContract"}, Note: "W-KNOB-PRUNE 2026-09-18: constant 3 unless stored (the owner stores 5, honoured + logged). Control removed."},
	"selected_timeframes":              {Path: "selected_timeframes", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:762"}, Note: ""},
	"session":                          {Path: "session", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:403"}, Note: ""},
	"sessions_enabled":                 {Path: "sessions_enabled", Status: KnobLive, Consumers: []string{"trader/auto_trader_planconfig.go:77"}, Note: ""},
	"source_type":                      {Path: "source_type", Status: KnobLive, Consumers: []string{"kernel/engine.go:418"}, Note: ""},
	"static_coins":                     {Path: "static_coins", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:272"}, Note: ""},
	"stop_loss_pct":                    {Path: "stop_loss_pct", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid_orders.go:362"}, Note: ""},
	"strategy_type":                    {Path: "strategy_type", Status: KnobLive, Consumers: []string{"trader/auto_trader_decision.go:107"}, Note: ""},
	"suggestions":                      {Path: "suggestions", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"symbol":                           {Path: "symbol", Status: KnobLive, Consumers: []string{"kernel/grid_engine.go:153"}, Note: ""},
	"system_prompt":                    {Path: "system_prompt", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:590"}, Note: ""},
	"total":                            {Path: "total", Status: KnobLive, Consumers: []string{"kernel/engine_analysis.go:256"}, Note: ""},
	"total_investment":                 {Path: "total_investment", Status: KnobLive, Consumers: []string{"kernel/grid_engine.go:153"}, Note: ""},
	"trading_frequency":                {Path: "trading_frequency", Status: KnobLive, Consumers: []string{"kernel/engine_prompt_futures.go:142"}, Note: ""},
	"trailing_arm":                     {Path: "trailing_arm", Status: KnobLive, Consumers: []string{"trader/auto_trader_trailing.go:52"}, Note: ""},
	"trailing_arm_points":              {Path: "trailing_arm_points", Status: KnobLive, Consumers: []string{"trader/auto_trader_trailing.go:58"}, Note: ""},
	"trailing_atr_mult":                {Path: "trailing_atr_mult", Status: KnobLive, Consumers: []string{"trader/auto_trader_trailing.go:44"}, Note: ""},
	"trailing_atr_period":              {Path: "trailing_atr_period", Status: KnobLive, Consumers: []string{"trader/auto_trader_trailing.go:48"}, Note: ""},
	"trailing_enabled":                 {Path: "trailing_enabled", Status: KnobLive, Consumers: []string{"trader/auto_trader_trailing.go:43"}, Note: ""},
	"transition_standdown":             {Path: "transition_standdown", Status: KnobCandidate, Consumers: nil, Note: "no consumer found by a FIELD grep on 2026-09-03 (grep -rn \".<Field>\\b\" kernel trader api agent provider). A METHOD-based reader would NOT appear, so this is NOT dead and must not be removed: it needs a method-level grep with the command quoted before any status change."},
	"type":                             {Path: "type", Status: KnobLive, Consumers: []string{"kernel/htf_veto.go:115"}, Note: ""},
	"updated_at":                       {Path: "updated_at", Status: KnobLive, Consumers: []string{"trader/armed_executor.go:1027"}, Note: ""},
	"upper_price":                      {Path: "upper_price", Status: KnobLive, Consumers: []string{"kernel/grid_engine.go:283"}, Note: ""},
	"url":                              {Path: "url", Status: KnobLive, Consumers: []string{"kernel/engine.go:778"}, Note: ""},
	"usage_pct":                        {Path: "usage_pct", Status: KnobLive, Consumers: []string{"api/strategy.go:385"}, Note: ""},
	"use_ai500":                        {Path: "use_ai500", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:272"}, Note: ""},
	"use_atr_bounds":                   {Path: "use_atr_bounds", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid.go:304"}, Note: ""},
	"use_hyper_all":                    {Path: "use_hyper_all", Status: KnobLive, Consumers: []string{"kernel/engine.go:497"}, Note: ""},
	"use_hyper_main":                   {Path: "use_hyper_main", Status: KnobLive, Consumers: []string{"kernel/engine.go:516"}, Note: ""},
	"use_maker_only":                   {Path: "use_maker_only", Status: KnobLive, Consumers: []string{"trader/auto_trader_grid_orders.go:127"}, Note: ""},
	"use_oi_low":                       {Path: "use_oi_low", Status: KnobLive, Consumers: []string{"kernel/engine.go:477"}, Note: ""},
	"use_oi_top":                       {Path: "use_oi_top", Status: KnobLive, Consumers: []string{"kernel/engine_prompt.go:272"}, Note: ""},
	"user_id":                          {Path: "user_id", Status: KnobLive, Consumers: []string{"trader/auto_trader_planner.go:61"}, Note: ""},
	"wake_min_interval_min":            {Path: "wake_min_interval_min", Status: KnobFolded, Consumers: []string{"trader/auto_trader_wake_levels.go:287", "trader/auto_trader_transition.go:193", "trader/auto_trader_planner.go:804"}, Note: "W-KNOB-PRUNE 2026-09-18: constant 30 unless stored; control removed."},
	"wake_on_15m_zone":                 {Path: "wake_on_15m_zone", Status: KnobFolded, Consumers: []string{"trader/auto_trader_wake_levels.go:103"}, Note: "W-KNOB-PRUNE 2026-09-18: LEGACY per-class switch, collapsed into wake_on_level_events. Read only for the mapping (any of the five ON → the single switch ON); the Studio never writes it again."},
	"wake_on_htf_ob":                   {Path: "wake_on_htf_ob", Status: KnobFolded, Consumers: []string{"trader/auto_trader_wake_levels.go:147", "trader/auto_trader_wake_levels.go:103"}, Note: "W-KNOB-PRUNE 2026-09-18: LEGACY per-class switch, collapsed into wake_on_level_events. Read only for the mapping (any of the five ON → the single switch ON); the Studio never writes it again. Additionally keeps its own effect: the HTF order-block wake class runs only when this legacy field is stored true (the owner's MNQ strategy) — the shipped default OFF is unchanged. NEW COUPLING (review of #172): the class is ANDed with wake_on_level_events — pre-prune it was gated by its own field alone; now the single switch OFF disables OBs too (pinned by trader.TestKnobPrunePin_WakeCandidates_SingleSwitchOwnsOB; inert for every stored strategy)."},
	"wake_on_htf_zone":                 {Path: "wake_on_htf_zone", Status: KnobFolded, Consumers: []string{"trader/auto_trader_wake_levels.go:103"}, Note: "W-KNOB-PRUNE 2026-09-18: LEGACY per-class switch, collapsed into wake_on_level_events. Read only for the mapping (any of the five ON → the single switch ON); the Studio never writes it again."},
	"wake_on_ifvg":                     {Path: "wake_on_ifvg", Status: KnobFolded, Consumers: []string{"trader/auto_trader_wake_levels.go:103"}, Note: "W-KNOB-PRUNE 2026-09-18: LEGACY per-class switch, collapsed into wake_on_level_events. Read only for the mapping (any of the five ON → the single switch ON); the Studio never writes it again."},
	"wake_on_level_events":             {Path: "wake_on_level_events", Status: KnobLive, Consumers: []string{"trader/auto_trader_wake_levels.go:103"}, Note: "W-KNOB-PRUNE 2026-09-18: the ONE level-event wake switch (nil = ON) — HTF S/D zones + seated-level invalidation, with the 15m zone/FVG + iFVG classes riding at their shipped-ON default; HTF OBs only via the legacy stored wake_on_htf_ob=true."},
	"wake_on_seated_invalidation":      {Path: "wake_on_seated_invalidation", Status: KnobFolded, Consumers: []string{"trader/auto_trader_wake_levels.go:103"}, Note: "W-KNOB-PRUNE 2026-09-18: LEGACY per-class switch, collapsed into wake_on_level_events. Read only for the mapping (any of the five ON → the single switch ON); the Studio never writes it again."},
	"write_time_feasibility":           {Path: "write_time_feasibility", Status: KnobLive, Consumers: []string{"trader/auto_trader_planner.go (write-time feasibility check, W-WRITE-TIME-FEASIBILITY)"}, Note: "W-WRITE-TIME-FEASIBILITY 2026-09-18: nil/unset = ON (owner ruling 'fix all' 08:3x CT — a scenario whose arm would be refused at arm is repair-hinted, then written arm.enabled=false); explicit false = today's WARN-only behaviour byte-identical. Geometry resolves through the executor's composeArmStop — the write site follows the executor to ArmGeometryVerdict(doc, sc, cfg.DayPlan.GeometryRefIDsEnabled()) at the W-GEOMETRY-REFUSAL merge (CTO BLOCKER 3)."},
}
