import { GUIDE_BUILT_REV, type GuideSection } from '../types'

// Mentor mode (🧑‍🏫) — the owner's mentor's method, built as a per-strategy
// trading mode. Everything below is read from the lane branches that implement
// it (feat/mentor-eval, feat/mentor-isb, feat/mentor-boxes-swing,
// feat/mentor-p3). Items not yet merged are marked "coming with Mentor mode".
export const mentor: GuideSection = {
  id: 'mentor',
  num: 17,
  title: 'Mentor Mode',
  tagline:
    "The mentor's method: three setups, four locations, hard filters, small and patient.",
  asBuiltRev: GUIDE_BUILT_REV,
  blocks: [
    {
      kind: 'callout',
      title: 'SIM only, OFF by default',
      items: [
        {
          title: 'This is a Simulated-mode strategy',
          body: 'Mentor mode trades on NinjaTrader SIM, never live. mentor_mode is per strategy and defaults OFF; while OFF, nothing in this package is consulted and the bot is byte-identical.',
          cite: 'trader/mentor_mode.go:158 · kernel/mentor/mentor.go Config.Enabled',
        },
        {
          title: 'Entries are stop orders only — never limit',
          body: '"mình KHÔNG BẮT LIMIT nữa… chỉ có set lệnh BUY STOP, SELL STOP thôi." You wait at a level and a stop order puts you in; no chasing, no market entries.',
          cite: 'LEVELS ruling 2026-10-03',
        },
        {
          title: 'Entries become stop-LIMIT',
          body: 'The ISB order type is stop-limit with the limit at the stop price ("đừng đặt buy stop market nữa…"). The live wire stays stop-market until the cancel-confirm frame lands — mentor_mode must not be enabled before then.',
          cite: 'D1.4 p1 @ 24:41–24:55 · coming with Mentor mode',
        },
      ],
    },
    {
      kind: 'h',
      text: 'The three setups',
    },
    {
      kind: 'cards',
      cards: [
        {
          title: 'Inside bar (ISB)',
          body: "Candle 2's BODY inside candle 1's FULL range (wicks included). Direction = candle 1's colour. Entry at the ISB candle's own extreme + 1–1.5 pt buffer, stop at its opposite extreme, no fixed stop size — skip only when the stop is \"in the twenties\". The FIRST inside-bar candle is I1 — the order sits at its extremes and the containment test is against I1. A following candle that does not fill and whose BODY is NOT inside I1 → cancel at once. Body inside I1 → keep. I1 counts as candle 1 of the stack; candles 2 and 3 inside → keep; the 4th not filling → cancel (it becomes a 5m inside bar = rest).",
          tag: 'D1.4 p1',
        },
        {
          title: 'PHL / PLH — the pullback',
          body: "Uptrend pullback → buy stop at the previous candle's high, stop at that candle's low, target NEAR the old high. Downtrend bounce → the exact mirror. Wait 1–2 more pullback candles; a higher low is required (a flat low is an FTGL, not a PHL).",
          tag: 'D2.2 p1',
        },
        {
          title: 'SWING4H — 4h EMA 34',
          body: 'The line is the 4h EMA 34 known at the start of the current 4h bar (17:00 CT anchor), drawn BEFORE price gets there. Switch straight down to the 5m and wait for a LITERAL touch. Reject (closes back on the approach side) → stop order tight on the candle, stop 30 beyond the line. Through-close → cancel; closes back → 5m inside bar with the stop AT the line. Stop ~100 → do not enter. One setup per approach until price leaves the line by the stop distance.',
          tag: 'D5.2',
        },
      ],
    },
    {
      kind: 'h',
      text: 'The four locations',
    },
    {
      kind: 'table',
      title:
        'A PHL/PLH is only valid at one of these (the ISB may be anywhere — see the ruling below)',
      head: ['Location', 'Where it comes from', 'Note'],
      rows: [
        [
          'Key levels',
          '1H RTH colour changes — a line at the OPEN of the new-colour candle (never the wick), from the market open',
          'Pruned < 20 pts apart (keep the more recent); deleted when a 1H candle CLOSES through it',
        ],
        [
          'EMA 34',
          "The trading chart's EMA 34 — 1m for intraday (R3)",
          'The 4h EMA 34 belongs to the SWING4H setup only',
        ],
        [
          '5m trigger-line retest',
          'A candle breaks the previous 5m extreme (wick included); the retest of that line is a location',
          'Between two opposing trigger lines: NO trade at all, ISB included',
        ],
        [
          'Box edge',
          'FTGH/FTGL boxes, 1m regular candles, paired by role with no tolerance',
          'A box edge is used again and again; a box dies only on escape (a 1m BODY closes outside) or at day end',
        ],
      ],
    },
    {
      kind: 'callout',
      title: 'OWNER RULING — the ISB may be taken ANYWHERE',
      items: [
        {
          title: 'PHL/PLH still need a location',
          body: 'Only the ISB is anywhere. The PHL/PLH and the SWING4H still need their locations above.',
          cite: 'OWNER RULING 00:1x CT',
        },
        {
          title: 'Never between two trigger lines',
          body: 'Between two opposing 5m trigger lines there is NO trade at all, ISB included.',
          cite: 'trigger zone filter — merged',
        },
        {
          title: 'Only same-direction inside a 5m ISB box',
          body: 'The latest 5m ISB candle is boxed; only a same-direction 1m ISB trades inside it.',
          cite: 'ISB rest box filter — merged',
        },
        {
          title: 'Smaller size at an old high/low',
          body: 'An ISB at an old high/low trades the reduced size.',
          cite: 'coming with Mentor mode',
        },
        {
          title: 'Skip a stop in the twenties',
          body: 'A stop of 20–29.99 pts must not be taken — the only stop-size skip the method has.',
          cite: 'ISBTwentiesPts 20 — merged',
        },
      ],
    },
    {
      kind: 'callout',
      title: 'Rulings 2026-10-03 — locations, boxes, exits',
      items: [
        {
          title: 'Per-visit level references',
          body: 'A level reference lasts until a closed candle departs the level; every NEW visit (a closed candle not touching it since the last reference) gets its own reference candle and stop. One level no longer blocks itself for the whole day.',
          cite: 'L1 — lvl_revisit_min_pts, default 0',
        },
        {
          title: 'Box ping-pong needs ≥ 50 pts',
          body: 'A reference candle touching one of the two boxes is NOT mid-range: touch the lower box → trade up, touch the upper → trade down — but only when the gap between the FTGL top and the FTGH bottom is at least 50 pts; below that the entry is refused (ping_pong_range_too_small). PHL/PLH anywhere ELSE between the boxes stays banned.',
          cite: 'D3.2 p2 @07:50–09:14 · D4.2 p2 @05:17',
        },
        {
          title: 'Every box return trades',
          body: 'Each new visit gets a reference candle and the same reject rule (close OUTSIDE the box on the approach side = trade; close inside = cancel). The first return is the 3rd touch; later returns trade too. Boxes die at end of day only.',
          cite: 'R1 · D3.2 p2 @06:25',
        },
        {
          title: 'Intraday confluence (exit C, size 10)',
          body: 'LONG = entry at an FTGL AND a key level (inside the box or within 2 pts of its edge) AND the 5m BUY trigger agrees; SHORT = FTGH + key level + 5m SELL trigger. Then: hold at least 1:2, the stop is never moved up (exit C), size 10; size 20 only when 4h AND 1h agree and room ≥ 30 pts.',
          cite: 'R2 · D3.4 p3 @07:38',
        },
        {
          title: 'A loss at a place blocks it',
          body: 'After a LOSS at a level, a box edge or the EMA line (entry filled, then the stop hit), that place is blocked until a departure candle. Two losses at one place → that place is off for the day.',
          cite: 'E2 · G2 · D4.2 p2 @01:56',
        },
        {
          title: 'Leg budget — two entries per leg',
          body: 'A leg runs from the PHL/PLH to the old extreme and allows at most 2 entries (the PHL/PLH + a same-direction ISB). A stop-out inside the leg closes it; a NEW leg starts only on a 1m CLOSE beyond the prior high (long) / low (short).',
          cite: 'G1 · X15 @00:36–02:46',
        },
      ],
    },
    {
      kind: 'h',
      text: 'The filters',
    },
    {
      kind: 'table',
      title: 'What keeps you out',
      head: ['Filter', 'Rule', 'Knob'],
      rows: [
        [
          'Trigger zone',
          'Between two opposing 5m trigger lines there is NO trade at all, ISB included — wait for it to escape both',
          '—',
        ],
        [
          'ISB rest box',
          'The latest 5m ISB candle is boxed and extended right; only a same-direction 1m ISB trades inside; a 1m BODY closing outside deletes the box',
          '—',
        ],
        [
          'Day gate (§7)',
          'Measure the Globex run (17:00 → 08:30 CT) before the open. Conflict on a spent day → the machine is OFF for the day (latched at 08:30). Spent + agree → trade but cap the target at 15 pts; on a spent day skip any setup whose stop is over 15',
          'DayGateSpentPts 300 · DayGateTargetCapPts 15',
        ],
        [
          '4h/1h direction',
          'Entries only WITH the 4h trigger; 1h agreeing or silent. 1h opposite → sit out until it flips. No 4h trigger → nothing to follow',
          '—',
        ],
        [
          'Room rule',
          'The room to target must be at least 2× the risk; the stop never exceeds 25 pts (SWING4H exempt — its ceiling is 100)',
          'RoomMultiple 2 · StopCeilingPts 25',
        ],
        [
          'ORB gate (opening range) — coming with Mentor mode',
          'ORB = the high and the low of the FIRST 2-minute candle of the regular session (08:30–08:32 CT), drawn only once that candle has completed. NO trade inside the ORB and NO reversal trade at either edge. Trade only after price has LEFT the box — escape test: a 1m BODY close outside. Direction follows the escape side: below → shorts only (ISB short / PLH); above → longs only. The escape picks the side; it is NOT an entry. No ORB for pre-market. The SWING4H is exempt.',
          'orb_gate_enabled = true (default ON) · X5 @01:52, 02:36, 03:29–03:47, 05:42',
        ],
        [
          'Coming with Mentor mode',
          'Between-boxes mid-range ban (NO PHL/PLH regardless of width, ISB only) · 15m-confirm conflict (R6) · loss box — two losses at one place, the level is off for the day (R11) · news 07:30 CT — no resting order through the print (R12) · EMA 34 turned off while price cuts through it (§11)',
          '—',
        ],
      ],
    },
    {
      kind: 'callout',
      title: 'Daily limits',
      items: [
        {
          title: 'Done for the day after a win',
          body: 'One win and the machine is done for the day.',
          cite: 'coming with Mentor mode',
        },
        {
          title: 'Trading window 08:30–09:30 CT',
          body: 'The day is only 08:30–09:30 CT. The SWING4H is exempt.',
          cite: 'knob — coming with Mentor mode',
        },
        {
          title: 'Never widen a stop, never add',
          body: 'A stop only ever moves toward break-even. Never add to a position.',
          cite: 'coming with Mentor mode',
        },
        {
          title: '"One loss → done" is NOT used',
          body: 'His personal one-loss rule stays his. The machine does not copy it.',
          cite: 'OWNER RULING 00:1x CT',
        },
      ],
    },
    {
      kind: 'h',
      text: 'Sizing',
    },
    {
      kind: 'table',
      title: 'The size table (SIM)',
      head: ['Tier', 'Default contracts', 'Knob'],
      rows: [
        ['Base', '5', 'mentor_base_contracts'],
        ['Confluence (many things agree)', '10', 'mentor_confluence_contracts'],
        ['Big (the hard tier)', '20', 'mentor_big_contracts'],
        ['Hard cap', '20', 'mentor_max_contracts'],
        [
          'Reduced (stop in the twenties / spent day)',
          '3',
          'mentor_reduced_contracts',
        ],
        ['SWING4H', '3', 'mentor_swing4h_contracts'],
        ['Spent day (§7)', '2', 'mentor_spent_day_contracts'],
      ],
    },
    {
      kind: 'h',
      text: 'The exits',
    },
    {
      kind: 'table',
      title: 'Three paths, chosen at the fill',
      head: ['Path', 'Rule'],
      rows: [
        [
          'A — resonance',
          'A PHL/PLH filled and then an ISB in the SAME direction within 3 candles: the moment that ISB appears, the stop goes to break-even and the trade rides (do not trail it)',
        ],
        [
          'B — normal',
          'At +0.5R the stop moves to break-even (live R:R stays 1:1); at +1R take half off; then the stop trails behind each closed candle (trail_tf: 1m default, 30s/45s allowed, off = legacy)',
        ],
        ['C — confluence', 'Hold to at least 1:2 — the stop does not move up'],
        [
          'SWING4H',
          'First target = the 5m EMA 34 (or the 50-pt fallback); BE at +1R; hold to the close of the 2nd 4h candle after entry',
        ],
        [
          'ISB partial',
          'For an ISB trade the first partial is taken when the candle that FILLED you closes — a setup has three parts, never a fourth (coming with Mentor mode: replaces +1R half-off for ISB trades)',
        ],
      ],
    },
    {
      kind: 'h',
      text: 'Every knob, with its default and source',
    },
    {
      kind: 'knobs',
      knobs: [
        {
          label: 'Mentor mode',
          where: 'Strategy → Mentor mode (per strategy)',
          what: 'Turns the mentor method on for this strategy. SIM only.',
          trader:
            'OFF until you want the method. Everything below only exists while this is ON.',
          consumer:
            'trader/mentor_mode.go:158 · kernel/mentor/mentor.go Config.Enabled',
          range: 'true / false',
          systemDefault: 'OFF',
          recommended:
            'OFF — SIM only, and the wire is still stop-market until the cancel-confirm frame lands.',
          whenToTouch:
            'Only after every item marked "coming with Mentor mode" has shipped.',
          perSession: 'No — per strategy.',
        },
        {
          label: 'Base contracts',
          where: 'Strategy → Mentor mode → sizing',
          what: 'The default contract count for a mentor entry.',
          trader: '5 contracts on SIM per setup.',
          consumer: 'trader/mentor_mode.go:25 mentorBaseContractsDefault',
          range: 'int',
          systemDefault: '5',
          recommended: '5 — the size table the CTO shipped with P3.',
          whenToTouch: 'When you deliberately re-size the method.',
          perSession: 'No.',
        },
        {
          label: 'Confluence contracts',
          where: 'Strategy → Mentor mode → sizing',
          what: 'Size when many things agree (the confluence path).',
          trader: '10 contracts when everything lines up.',
          consumer: 'trader/mentor_mode.go:26',
          range: 'int',
          systemDefault: '10',
          recommended:
            '10 — the confluence tier: everything agrees, trade it bigger.',
          whenToTouch: 'With the confluence exit path.',
          perSession: 'No.',
        },
        {
          label: 'Big contracts',
          where: 'Strategy → Mentor mode → sizing',
          what: 'The big tier — the largest deliberate size.',
          trader: '20 contracts max on a big tier.',
          consumer: 'trader/mentor_mode.go:27',
          range: 'int',
          systemDefault: '20',
          recommended: '20 — also the hard cap.',
          whenToTouch: 'Never above the hard cap.',
          perSession: 'No.',
        },
        {
          label: 'Max contracts',
          where: 'Strategy → Mentor mode → sizing',
          what: 'The hard ceiling across all tiers.',
          trader: 'No mentor position ever exceeds this.',
          consumer: 'trader/mentor_mode.go:31',
          range: 'int',
          systemDefault: '20',
          recommended: '20 — the big tier and the hard cap.',
          whenToTouch: 'To tighten the cap.',
          perSession: 'No.',
        },
        {
          label: 'Reduced contracts',
          where: 'Strategy → Mentor mode → sizing',
          what: 'Size when the stop is in the twenties or the day is spent.',
          trader: '3 contracts on the reduced tier.',
          consumer: 'trader/mentor_mode.go:28',
          range: 'int',
          systemDefault: '3',
          recommended: '3 — the reduced tier for twenties/spent stops.',
          whenToTouch: 'With the twenties/spent tier rules.',
          perSession: 'No.',
        },
        {
          label: 'SWING4H contracts',
          where: 'Strategy → Mentor mode → sizing',
          what: 'Size for the 4h EMA 34 swing setup.',
          trader: '3 contracts on the swing.',
          consumer: 'trader/mentor_mode.go:29',
          range: 'int',
          systemDefault: '3',
          recommended:
            '3 — the swing is exempt from the 25-pt ceiling; keep it small.',
          whenToTouch: 'Never — fixed by the size table.',
          perSession: 'No.',
        },
        {
          label: 'Spent-day contracts',
          where: 'Strategy → Mentor mode → sizing',
          what: 'Size when the §7 day gate says the day already ran 300+.',
          trader: '1–2 contracts — "on range days hold 1–2 contracts only".',
          consumer: 'trader/mentor_mode.go:30',
          range: 'int',
          systemDefault: '2',
          recommended: '2 — the §7 spent-day tier.',
          whenToTouch: 'With DayGateSpentPts.',
          perSession: 'No.',
        },
        {
          label: 'Trail timeframe',
          where: 'Strategy → Mentor mode → exits',
          what: 'The candle-trail timeframe for the B exit.',
          trader: '1m — the stop trails behind each closed 1m candle.',
          consumer: 'trader/mentor_mode.go:449 mentorTrailTFDefault',
          range: '1m / 30s / 45s / off',
          systemDefault: '1m',
          recommended: '1m — the course frame.',
          whenToTouch: 'off = the video-8 legacy, kept as a knob.',
          perSession: 'No.',
        },
        {
          label: 'Key level timeframe',
          where: 'Strategy → Mentor mode → levels',
          what: 'The TF of the colour-change walk that draws key levels.',
          trader: '1H — "90%-95% các levels quan trọng xuất phát từ khung 1H".',
          consumer: 'kernel/mentor/mentor.go KeyLevelTFMinutes',
          range: 'minutes',
          systemDefault: '60 (1H RTH, from the market open)',
          recommended: '60 — slide 31, the written spec.',
          whenToTouch: 'Other TFs exist for experimentation only.',
          perSession: 'No.',
        },
        {
          label: 'Key levels RTH only',
          where: 'Strategy → Mentor mode → levels',
          what: 'Only RTH candles count for key levels.',
          trader:
            'ON — external hours are not counted ("Không tính external hours").',
          consumer: 'kernel/mentor/mentor.go KeyLevelRTHOnly',
          range: 'true / false',
          systemDefault: 'true',
          recommended: 'true — the slide says RTH only.',
          whenToTouch: 'Never — the slide is explicit.',
          perSession: 'No.',
        },
        {
          label: 'Key level prune',
          where: 'Strategy → Mentor mode → levels',
          what: 'Two levels closer than this: delete one, keep the more recent.',
          trader: '20 pts.',
          consumer: 'kernel/mentor/mentor.go KeyLevelPrunePts',
          range: 'pts',
          systemDefault: '20',
          recommended: '20 — D5.3 p1 @ 16:08–16:44.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'EMA 34 period',
          where: 'Strategy → Mentor mode → indicators',
          what: 'The EMA 34 period for the level lines.',
          trader: '34.',
          consumer: 'kernel/mentor/mentor.go EMAPeriod34',
          range: 'period',
          systemDefault: '34',
          recommended: '34 — the method names it exactly.',
          whenToTouch: 'Never — the method names it.',
          perSession: 'No.',
        },
        {
          label: 'EMA 9 period',
          where: 'Strategy → Mentor mode → indicators',
          what: 'The EMA 9 period (the reverse-ISB home).',
          trader: '9.',
          consumer: 'kernel/mentor/mentor.go EMAPeriod9',
          range: 'period',
          systemDefault: '9',
          recommended: '9 — the reverse-ISB home.',
          whenToTouch: 'Never.',
          perSession: 'No.',
        },
        {
          label: 'EMA timeframe',
          where: 'Strategy → Mentor mode → indicators',
          what: 'The TF the EMA 34/9 lines are computed on.',
          trader: '1m.',
          consumer: 'kernel/mentor/mentor.go EMATFMinutes',
          range: 'minutes',
          systemDefault: '1',
          recommended: '1 — the EMA lines are computed on the 1m.',
          whenToTouch: 'Experimentation only.',
          perSession: 'No.',
        },
        {
          label: 'EMA 34 location timeframe',
          where: 'Strategy → Mentor mode → locations',
          what: 'The EMA 34 timeframe for the LOCATION gate (R3: intraday = the trading chart).',
          trader:
            '1m — the intraday EMA 34 lives on the 1m chart; the 4h EMA 34 is ONLY the swing.',
          consumer: 'kernel/mentor/mentor.go EMALocationTFMinutes',
          range: 'minutes',
          systemDefault: '1',
          recommended: '1 — D5.4 @ 01:00–01:27, the intraday chart.',
          whenToTouch: 'Experimentation only.',
          perSession: 'No.',
        },
        {
          label: 'Touch band',
          where: 'Strategy → Mentor mode → touches',
          what: 'How close counts as touching a level.',
          trader: '0 — a LITERAL touch only ("KHÔNG ĐƯỢC GẦN ĐỤNG").',
          consumer: 'kernel/mentor/mentor.go TouchBandPts',
          range: 'pts',
          systemDefault: '0',
          recommended: '0 — the literal touch is the method.',
          whenToTouch: 'Never — the literal touch is the method.',
          perSession: 'No.',
        },
        {
          label: 'ISB buffer',
          where: 'Strategy → Mentor mode → ISB',
          what: 'Buffer on BOTH the entry and the stop, outward.',
          trader: '1.5 pts.',
          consumer: 'kernel/mentor/mentor.go ISBBufferPts',
          range: 'pts',
          systemDefault: '1.5',
          recommended: '1.5 — D1.4 p1 @ 22:22–22:30.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'ISB twenties',
          where: 'Strategy → Mentor mode → ISB',
          what: 'An ISB whose stop is at/above this ("in the twenties") is not taken.',
          trader:
            '20 pts — and there is NO minimum stop (the old 5–6-pt cap is gone).',
          consumer: 'kernel/mentor/mentor.go ISBTwentiesPts',
          range: 'pts',
          systemDefault: '20',
          recommended: '20 — D4.1 p1 @ 05:41.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Reverse ISB at EMA 9',
          where: 'Strategy → Mentor mode → setups',
          what: 'R7: an ISB pointing AGAINST the trend at EMA 9 reverses — uptrend → long buy stop above the ISB high; downtrend → the mirror. Requires price to actually reach EMA 9.',
          trader: 'OFF by default — the course keeps it behind its own knob.',
          consumer: 'kernel/mentor/mentor.go ISBReverseEMA9Enabled',
          range: 'true / false',
          systemDefault: 'false',
          recommended: 'OFF — the course keeps R7 behind its own knob.',
          whenToTouch: 'Only with the ISB family fully wired.',
          perSession: 'No.',
        },
        {
          label: 'PHL min candles from old extreme',
          where: 'Strategy → Mentor mode → PHL/PLH',
          what: 'The entry must be at least this many candles from the old extreme (wait 1–2 more pullback candles).',
          trader: '3.',
          consumer: 'kernel/mentor/mentor.go PHLMinCandlesFromExtreme',
          range: 'candles',
          systemDefault: '3',
          recommended: '3 — D2.2 p2 @ 05:25.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'PHL target shy',
          where: 'Strategy → Mentor mode → PHL/PLH',
          what: 'Target this far short of the old extreme — NEAR it, not at it.',
          trader: '5 pts.',
          consumer: 'kernel/mentor/mentor.go PHLTargetShyPts',
          range: 'pts',
          systemDefault: '5',
          recommended: '5 — D2.2 p1 @ 06:50.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Stop ceiling',
          where: 'Strategy → Mentor mode → risk',
          what: 'Hard stop ceiling for PHL/PLH and ISB stops.',
          trader: '25 pts — the SWING4H is exempt (its ceiling is 100).',
          consumer: 'kernel/mentor/mentor.go StopCeilingPts',
          range: 'pts',
          systemDefault: '25',
          recommended: '25 — D3.3 p1 @ 02:04.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Room multiple',
          where: 'Strategy → Mentor mode → risk',
          what: 'The room to target must be at least this × the risk.',
          trader: '2×.',
          consumer: 'kernel/mentor/mentor.go RoomMultiple',
          range: '×',
          systemDefault: '2',
          recommended: '2 — D5.3 p1 @ 09:16.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Mid-range gap',
          where: 'Strategy → Mentor mode → filters',
          what: 'Mid-range ban. Coming with Mentor mode: when price sits between an FTGL below and an FTGH above, ANY width, PHL/PLH are banned — ISB only.',
          trader:
            '0 = DISABLED. Coming with Mentor mode: enabled for price between an FTGL below and an FTGH above, any width.',
          consumer: 'kernel/mentor/mentor.go RangeGapPts',
          range: 'pts (0 = off)',
          systemDefault: '0 (disabled)',
          recommended: 'Left at 0 until DS-103 wires the between-boxes ban.',
          whenToTouch: 'After the between-boxes ban ships.',
          perSession: 'No.',
        },
        {
          label: 'Day gate spent threshold',
          where: 'Strategy → Mentor mode → day gate',
          what: 'The Globex run (17:00 → 08:30 CT) at/above this before the open = a spent day.',
          trader:
            '300 pts — "already run 300–400 before the open → 80–90% it ranges".',
          consumer: 'kernel/mentor/mentor.go DayGateSpentPts',
          range: 'pts',
          systemDefault: '300',
          recommended: '300 — D5.1 p1 @ 15:57.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Day gate target cap',
          where: 'Strategy → Mentor mode → day gate',
          what: 'On a spent+agree day, cap the target distance; skip any setup whose stop is over this.',
          trader: '15 pts — "15 điểm bán, 10 điểm bán".',
          consumer: 'kernel/mentor/mentor.go DayGateTargetCapPts',
          range: 'pts',
          systemDefault: '15',
          recommended: '15 — D5.1 p1.',
          whenToTouch: 'With the spent tier.',
          perSession: 'No.',
        },
        {
          label: 'Swing EMA period',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'The 4h EMA period for the swing line.',
          trader: '34.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.EMAPeriod',
          range: 'period',
          systemDefault: '34',
          recommended: '34 — the swing line period.',
          whenToTouch: 'Never.',
          perSession: 'No.',
        },
        {
          label: 'Swing line offset',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'The line placement offset — toward the approaching price (the 4h is too coarse to place exactly).',
          trader: '5 pts.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.LineOffsetPts',
          range: 'pts (5–10)',
          systemDefault: '5',
          recommended: '5 — the base tier of the shipped size table.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Swing stop distance',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'The clean-rejection stop distance beyond the line.',
          trader: '30 pts — 30–60 allowed.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.StopBeyondLinePts',
          range: 'pts',
          systemDefault: '30',
          recommended: '30 — D5.2 table.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Swing max stop',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'A swing stop at/above this → do not enter. The swing is EXEMPT from the 25-pt ceiling.',
          trader: '100 pts.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.MaxStopPts',
          range: 'pts',
          systemDefault: '100',
          recommended: '100 — D5.2 table.',
          whenToTouch: 'Never below 25+30.',
          perSession: 'No.',
        },
        {
          label: 'Swing entry buffer',
          where: 'Strategy → Mentor mode → SWING4H',
          what: "Buffer beyond the reference candle's extreme. R8: NO buffer — the order sits tight on the candle.",
          trader: '0.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.EntryBufferPts',
          range: 'pts',
          systemDefault: '0',
          recommended: '0 — R8: the order sits tight on the candle.',
          whenToTouch: 'Never — R8 removed the buffer.',
          perSession: 'No.',
        },
        {
          label: 'Swing target fallback',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'First target when no 5m EMA 34 is available.',
          trader: '50 pts.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.TargetFallbackPts',
          range: 'pts',
          systemDefault: '50',
          recommended: '50 — D5.2 table.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Swing target EMA period',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'The first target is the 5m EMA 34.',
          trader: '34 on the 5m.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.TargetEMA5mPeriod',
          range: 'period',
          systemDefault: '34',
          recommended: '34 — the first-target EMA.',
          whenToTouch: 'Never.',
          perSession: 'No.',
        },
        {
          label: 'Swing leeway candles',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'After a through-close, the window for the 5m inside-bar entry.',
          trader: '2 candles.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.LeewayCandles',
          range: 'candles',
          systemDefault: '2',
          recommended: '2 — D5.2 p1 @ 15:21.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Swing hold bars',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'Hold to the close of the N-th 4h candle after entry.',
          trader: '2 — the method does not state the hold length.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.Hold4hBars',
          range: '4h candles',
          systemDefault: '2',
          recommended: '2 [C] — the method does not state the hold length.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Swing respects 5m zone',
          where: 'Strategy → Mentor mode → SWING4H',
          what: 'Gate swing entries on the 5m trigger zone when true.',
          trader:
            'OFF — §8 is a self-contained 4h → 5m procedure; nothing ties it to the trigger lines.',
          consumer: 'kernel/mentor/swing4h.go SwingCfg.Respects5mZone',
          range: 'true / false',
          systemDefault: 'false',
          recommended: 'false [C] — not stated in the method.',
          whenToTouch: 'Experimentation only.',
          perSession: 'No.',
        },
        {
          label: 'Box timeframe',
          where: 'Strategy → Mentor mode → boxes',
          what: 'The FTGH/FTGL box timeframe. 1m REGULAR is the course frame; 2m and 5m Heikin Ashi are 2025 extras, off by default.',
          trader: '1m.',
          consumer: 'kernel/mentor/box.go BoxCfg.TF',
          range: '1m / 2m / 5mha',
          systemDefault: '1m',
          recommended: '1m — D3.3 part1_06-25 frame.',
          whenToTouch: 'Experimentation only.',
          perSession: 'No.',
        },
        {
          label: 'Box touch band',
          where: 'Strategy → Mentor mode → boxes',
          what: 'A wick within this of a box edge counts as a touch (the third touch is the trade).',
          trader: '0.25 pts.',
          consumer: 'kernel/mentor/box.go BoxCfg.TouchBandPts',
          range: 'pts',
          systemDefault: '0.25',
          recommended: '0.25 — the wick touch tolerance.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Leg budget',
          where: 'Strategy → Mentor mode → limits',
          what: 'At most two entries per leg (the PHL/PLH plus a same-direction ISB); a stop-out closes the leg; a 1m close beyond the prior extreme starts a new one.',
          trader: 'ON — the method runs the budget (X15 @00:36–02:46).',
          consumer: 'kernel/mentor/limits.go leg_budget_enabled',
          range: 'true / false',
          systemDefault: 'true',
          recommended: 'true — G1 ruling 2026-10-03.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Leg reset on',
          where: 'Strategy → Mentor mode → limits',
          what: 'What opens a new leg after the budget is spent: a 1m close beyond the prior high/low.',
          trader: 'close.',
          consumer: 'kernel/mentor/limits.go leg_reset_on',
          range: 'close',
          systemDefault: 'close',
          recommended: 'close — G1 ruling 2026-10-03.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'Level revisit distance',
          where: 'Strategy → Mentor mode → levels',
          what: 'Extra departure distance (pts) a closed candle must clear before a new visit starts a new level reference.',
          trader: '0 — the method states none.',
          consumer: 'kernel/mentor/eval.go lvl_revisit_min_pts',
          range: 'pts',
          systemDefault: '0',
          recommended:
            '0 — L1 ruling 2026-10-03 (the mentor never states one).',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: 'EMA 34 cross cap (30m)',
          where: 'Strategy → Mentor mode → EMA34',
          what: 'Cap crossings around the EMA line in a 30m window (“xien len xien xuong”). The mentor gave no number, so the question is open (Q21).',
          trader: 'OFF — no number stated yet.',
          consumer: 'kernel/mentor ema_max_cross_30m',
          range: 'int / off',
          systemDefault: 'off',
          recommended:
            'off — E4 ruling 2026-10-03, default OFF; sensitivity rows v5_ema_cross2/4 exist in the replay.',
          whenToTouch: 'Only when the mentor answers Q21.',
          perSession: 'No.',
        },
        {
          label: 'Loss departure distance',
          where: 'Strategy → Mentor mode → limits',
          what: 'After a loss at a place (level, box edge or the EMA line), a closed candle AFTER the loss candle whose close is this many pts away from the loss price is the departure that un-blocks it. One number for every place.',
          trader: '20 pts — “leave the area”, no stated number.',
          consumer: 'kernel/mentor loss_departure_pts',
          range: 'pts',
          systemDefault: '20',
          recommended: '20 — departure ruling 2026-10-03.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
        {
          label: '5m trigger at locations',
          where: 'Strategy → Mentor mode → levels',
          what: 'The 5m trigger filter at levels and boxes (“bat buoc”). OFF only for the sensitivity row that measures what it costs.',
          trader: 'ON.',
          consumer: 'kernel/mentor location trigger filter',
          range: 'true / false',
          systemDefault: 'true',
          recommended:
            'true — L3 ruling 2026-10-03; v5_loc_notrig is the off-row.',
          whenToTouch: 'Rarely.',
          perSession: 'No.',
        },
      ],
    },
  ],
}
