import { GUIDE_BUILT_REV, type GuideSection } from '../types'

export const plays: GuideSection = {
  id: 'plays',
  num: 5,
  title: 'The Plays',
  tagline: 'Eight condition templates + the A-setup chain.',
  asBuiltRev: GUIDE_BUILT_REV,
  blocks: [
    {
      kind: 'h',
      text: 'ONE SETUP — THE BOOK ARMS ONE PLAY; THE FOLLOW IS RECORDED',
    },
    {
      kind: 'p',
      text: "Owner's ruling, 2026-09-10 [O]: \"one setup you understand completely beats five you half-do.\" Since this build the book ARMS exactly one play — the fade (`reject`) — and only when three things hold at the moment of authorization: (1) LEVEL — the scenario's level IS the best merged candidate within the reachability band right now, grade first (at or above the min grade, default B), distance second, any timeframe, any kind; (2) PLAY — the condition is `reject`; (3) PERMISSION — the fade-permission label reads permitted at that instant. NULL never permits and an unresolved level identity never resolves by 'nearest'. A declined scenario is still evaluated, confirmed and recorded as an episode — its row carries all three verdicts — it is just never armed. Its chip reads 'one-setup: declined — level=… · play=… · permission=…'. The structural-stop candidate uses the near edge of the first distinct eligible frozen zone. It refuses unsuitable geometry without moving the target; the plan card shows the recorded boundary, buffer and reason. One arm at a time per plan: when two scenarios are allowed the higher-quality one arms first and the other reads second_setup_waiting until the first is terminal. A resting arm is never cancelled by a later flip of the best level (that would meet MANUAL-CANCEL-WINS and kill the re-arm); the case is counted as declined_while_resting.",
    },
    {
      kind: 'p',
      text: 'The map is untouched. Nothing the planner is shown changes: the level block, the seat race, the merge, the candidates and the planner prompt are byte-identical with the switch on or off (pinned by a golden generated before the wave existed). This is a filter at the arm seam, not a change to what the desk sees.',
    },
    {
      kind: 'p',
      text: "THE FOLLOW-PLAN — RECORDED ONLY [T]. A real trader knows one level, two plans: hold it and the trend confirms, break it and the bias flips. Round 17 measured the second half and found nothing on MNQ: role reversal is UNTESTED on index futures and the naive follow LOSES (Mesfin: 80.7% pullback stop-out; the sweep loses both ways). So for EVERY level a scenario is authored on, beside the fade-plan the book now RECORDS the follow-plan and never arms it: the BREAK (the first CLOSED 5-minute bucket beyond the level — a forming bucket is not a break), the role reversal from that instant (recorded on the episode row, never on the map), the RETEST (the first touch of the reversed level from the far side), the would-be entry (a passive limit at the level, filled only if the retest bar traded THROUGH by a tick — a touch is not a fill, so an untouched-through retest records NULL with the reason), its MAE/MFE at 10 and 20 five-minute buckets and the net after 2-pt friction, whether the reversed level HELD on the retest (the detector's own verdict for that touch), and the bias the break implies — written BESIDE the plan's frozen bias, never into it. Every field is NULL until its event; a level never broken is a row with break_at NULL, a zero-trade outcome exactly as never-confirmed is for the fade. Nothing here reaches the wire: removing the recorder changes no arm, no order, no gate verdict.",
    },
    {
      kind: 'p',
      text: "The pre-registered null and the cell that would change the ruling: role reversal ≤ 50% and the follow ≤ 0 net. The follow goes live only if the owner's OWN record shows a cell (approach direction × level timeframe, ~385 episodes per cell, pooled first) where broken levels reverse role with a 95% lower bound above 50% AND the follow nets positive after 2-pt friction at both horizons. Day zero of that record is this boot. The knobs: one_setup_enabled (ON by default; OFF removes the one-setup selection checks; structural construction still governs reject fades) and one_setup_min_grade (B). Boot line: '🎯 one setup: ON[O] · level=best-near-price(min-grade B)[O] · play=reject · target=first-distinct-eligible-zone · permission-required=yes · map=untouched · today armable=… declined=… · follow-plan=RECORDED-ONLY[T] breaks=… retests=… role-reversed=…/… · bias-flip=recorded-only · off-switch=one_setup_enabled'.",
    },
    {
      kind: 'cards',
      cards: [
        {
          title: 'reclaim',
          body: 'Setup: level touched → price closes back on the original side → confirm: 1×5m close beyond (rule 1x5m_close) or a 1m-MSS (rule 1m_mss). NEVER 2×5m (2x5m_reserved — the double close is legal only on waterfall-class plays). The planner writes it when a level was lost and re-taken. Expectancy: the bread-and-butter retest play.',
          tag: 'play 1',
        },
        {
          title: 'hold',
          body: 'Setup: price holds a level → confirm: time_hold (price holds beyond the ref for the STORED confirm.hold_min minutes of 1m closes, no close back across — a plan that stores none is counted on the ACCEPT_HOLD_MIN = 10 authoring default and the chip says so) or 1x5m_close as the fallback. Written when the plan expects support/resistance to keep working.',
          tag: 'play 2',
        },
        {
          title: 'sweep_reclaim',
          body: 'Setup: level swept (liquidity taken) → close back inside → the SPLIT contract (E4): leg 1 = touch at the sweep ref (resting limit, no confirm), leg 2 = 1m-MSS or the reclaim 1×5m close — never 2×. The house play at ONH/ONL. Expectancy: week 0% / −192 when misplayed as fade-the-poke; the sweep first is what makes it valid.',
          tag: 'play 3',
        },
        {
          title: 'reject',
          body: 'Setup: first touch rejected at a zone → confirm: TOUCH at the level (rule touch) — fades never close-confirm (fade_requires_touch). Structure stop ≥2 ticks beyond the level; limit at the level. NY stat: 75% win / +665 (the best measured condition×session pair).',
          tag: 'play 4 · 75%',
        },
        {
          title: 'acceptance',
          body: 'Setup: closes through a level and holds → confirm: time_hold (confirm.hold_min minutes of 1m closes — minutes stated in the prose must be stored there, else the write is refused; absent in the prose → the 10-minute ACCEPT_HOLD_MIN default) or 1x5m_close. HOUSE RULE: acceptance requires a PRIOR sweep + displacement or the plan skips it (0% win evidence for bare acceptance).',
          tag: 'play 5',
        },
        {
          title: 'breakout_retest',
          body: 'Setup: break above/below → first retest holds → confirm: touch at the retest level + the STOP-ENTRY fallback (no retest within RETEST_WAIT_BARS = 6 bars → stop-entry beyond the break candle); 1x5m legal for the break leg. The ONH breakout play when price is at the top of the stack.',
          tag: 'play 6',
        },
        {
          title: 'fvg_entry',
          body: 'Setup: the A-setup\'s finish — displacement leaves a gap → first retrace INTO the FVG → confirm: touch at the gap band. entry_mode ce by default (edge only for A-grade HTF-confluent origins); stop beyond the sweep extreme; T1 = first opposing pool; runner = the draw. T1 and "runner" are PLAN VOCABULARY, not an exit ladder: an arm reaches the broker as ONE bracket — one entry, one stop, one target — at the size kernel.StageAContractCap() resolves (one contract today), so nothing scales out at T1 and leaves a remainder. Targets beyond the first node are guidance for the executor AI, validated for reachability at write time and never enforced at execution. chain_after links it to its sweep_reclaim. FVG DEMAND (A2c): a fresh machine gap matching your bias expects an fvg_entry — or a one-line reason why not.',
          tag: 'play 7',
        },
        {
          title: 'breakdown_continue',
          body: "Setup: price closes BELOW a broken level with displacement ≥ 1.0×ATR5m (BD_MIN_DISP_ATR) and no reclaim close → the waterfall SHORT. The STORED confirm.rule governs the count: 1x5m_close = ONE completed 5m close beyond the level, 2x5m_close = TWO — rendered, recorded, desked, armed and write-validated on that count. BD_MIN_CLOSES (1) is only the authoring default for a play that stores no close rule, and is labelled as such. Two-leg confirm: leg 1 = the breakdown close, leg 2 = the retest that FAILS to reclaim. Under the market_in_zone entry policy (W3 — the default for every NEWLY authored plan) BOTH entry modes arm: pullback puts the entry_zone AT the broken level, immediate puts it at the confirming close; the arm chains on leg 1 (wait_confirm) and the limit at the zone's far edge is placed once leg 1 is MET. A legacy plan (written before W3, no policy) keeps the old law: pullback arms, immediate is AI-path only. Born 2026-08-28: the −347pt NY crash — bias right, but NO plan-legal continuation short existed.",
          tag: 'play 8 · −347',
        },
        {
          title: 'breakup_continue',
          body: 'The LONG mirror: closes ABOVE a broken level with displacement ≥ 1.0×ATR5m, no reclaim → continuation long; the stored 1x5m_close / 2x5m_close is the count (BD_MIN_CLOSES = 1 only when none is stored), same two-leg confirm. entry_mode pullback and immediate BOTH arm under market_in_zone (the zone at the broken level / at the confirming close, chained on leg 1); a legacy plan keeps pullback = arm, immediate = AI-path. 2x5m_close is legal ONLY on this class — everywhere else it is 2x5m_reserved.',
          tag: 'play 8b',
        },
      ],
    },
    { kind: 'h', text: 'Arms follow the bias' },
    {
      kind: 'p',
      text: "With plan mode on strict an AI decision never enters by itself: entries execute ONLY through armed plan scenarios (W3 — a decision that CITES a market_in_zone scenario is a nudge that runs that scenario's armed pass, placement only, and is still recorded as refused). A plan whose bias direction carries no armed scenario cannot act on the direction it just argued for — it can take the other side, or nothing. On 2026-09-03 the NY v7 plan was biased long, wrote two long scenarios and one short, and armed only the short: both confirms went true at 11:58 CT and the long had no way to trade.",
    },
    {
      kind: 'p',
      text: 'The plan is still stored when this happens — the check WARNS and counts per side rather than rejecting, because on the stored history a hard reject would have refused about two thirds of every plan ever written. It becomes a rejection by a later ruling, once the planner has had the vocabulary long enough to comply.',
    },
    { kind: 'h', text: 'Entry type follows the condition' },
    {
      kind: 'table',
      title: 'What kind of order an arm becomes',
      head: ['Condition', 'Entry type', 'Why'],
      rows: [
        [
          'reject',
          'limit',
          'The entry IS the level — it rests at the anchor, one tick into the trade.',
        ],
        [
          'fvg_entry',
          'limit',
          'Rests at the gap edge or CE. Currently SHADOWED — do not arm it.',
        ],
        [
          'sweep_reclaim',
          'limit',
          "The split arm's legs rest at the sweep ref.",
        ],
        [
          'breakup_continue / breakdown_continue',
          'limit (pullback)',
          'The arm rests AT the broken level and chains on confirm leg 1. A stop entry here is only the no-retest fallback.',
        ],
        [
          'reclaim',
          'stop entry (legacy) · limit (market_in_zone)',
          'Only valid once price travels back THROUGH the level: a buy stop above the trigger (sell stop below, short). A limit here would fill on the wrong side of the move.',
        ],
        [
          'acceptance / hold / breakout_retest',
          'limit (market_in_zone) · not armable (legacy)',
          'W3: under market_in_zone they arm like every other condition — a limit at the far edge of the entry_zone, chained on their confirm (wait_confirm) because a time_hold / close is not a touch; an armed time_hold must hold at least day_plan.min_hold_min (3) minutes. breakout_retest stays SHADOW by default (recorded, never placed) until the owner un-shadows it. A LEGACY plan (no policy) keeps them AI-path plays.',
        ],
      ],
    },
    {
      kind: 'p',
      text: 'Under market_in_zone (the default for new plans) the table collapses to one answer: EVERY arm is a LIMIT at the FAR edge of its entry_zone, and an authored stop_entry is refused by name. The rows above are the LEGACY (and planned_order) mapping, which plans written before W3 keep byte-for-byte.',
    },
    { kind: 'h', text: 'Entry policy — enter AROUND the price (W3)' },
    {
      kind: 'p',
      text: 'day_plan.entry_policy_default is stamped on every arm of a NEWLY authored plan (a stored plan is never re-stamped). market_in_zone (default): the entry is a LIMIT at the FAR edge of the planner\'s own economics.entry_zone — a long buys at the zone HIGH, a short sells at the zone LOW — so it fills at once inside the zone and can never fill beyond it on the adverse side. planned_order: today\'s resting order at the exact entry, legal only on reject, fvg_entry and sweep_reclaim leg 1 (anywhere else the arm stays legacy). legacy: stamp nothing. The planner may write "policy": "planned_order" itself on a reject / fvg_entry / sweep_reclaim leg-1 arm.',
    },
    {
      kind: 'p',
      text: 'At write, every enabled market_in_zone arm is judged (NOT gated by write_time_feasibility): the zone is present, contains arm.entry, is at most day_plan.zone_max_pts (10) wide, sits on the permitted side of the confirm ref (a touch zone contains the ref ±1 tick; a close / time_hold / 1m_mss zone lies wholly on the confirm side of it), keeps the stop and target OUTSIDE it, and still holds a tick after rounding inward; then the executor\'s own gates judge each at its WORST fill — R:R at the far edge, the stop distance at the near edge (the stop is composed from the near edge). Attempts 1–2 hint the planner ("S2 entry zone: zone_too_wide — …"); the last attempt writes the arm disabled with arm_disabled_reason = the zone code (zone_missing · zone_too_wide · zone_entry_outside · zone_trigger_side · zone_bracket · zone_empty). Where the zone sits against the frozen geometry is logged as a label (🎯 zone at write … provenance=…), never a refusal.',
    },
    {
      kind: 'p',
      text: 'On the plan card a market_in_zone leg shows one line: "Entry: around <planned entry> (zone <lo>–<hi>) · <status>", the status being one of Waiting for price · Blocked: <reason> · Armed: <verdict> · Placed at <limit> · Filled <price> (n ticks — the fill vs the limit sent, + worse / − better) · Cancel pending: <reason>. A missing number reads n/a, never 0. Legacy and planned_order legs show no line, and no line appears until the executor writes a ledger row — a market_in_zone arm still waiting on wait_confirm shows only the armed chip.',
    },
    {
      kind: 'p',
      text: 'At placement every armed market_in_zone row gets a verdict from the last 1m close against its zone (boundaries inclusive): inside or beyond → the limit is sent at the far edge through the same gates as every arm (hold, admission, one contract, slot); short_of_zone (a long below the zone, a short above it) → nothing is sent and the row stays armed; unknown (no price, a bad zone, or a last 1m bar older than 3 minutes) → nothing at all. Passes run on the 2-minute scan AND on each final 1m bar while the active plan has a market_in_zone arm (at most once a second), and an AI decision that cites the scenario under strict runs the same full pass for that scenario only — every pass goes through the authoring gates and the admitted set. A working zone limit that rests longer than day_plan.zone_rest_max_min (30) minutes is cancelled ("zone rest expired"), and a scenario whose zone order reached the broker is not re-armed within the same plan version (a boot sweep still re-arms it; a new version always may). Logs: 🧭 zone verdict (each change, counted per class) · ⏳ … market_in_zone WAITING · ⚠️ … market_in_zone NOT adjudicated · 📌 … market_in_zone placement requested · ⏱ zone rest expired · ⚡ zone fill (slippage vs the limit, + worse) · 🚨 zone fill CONTRADICTION (a fill beyond the far edge) · ⚔️ arm REFUSED … market_in_zone:<code> · 🚦 strict: decision cites S… → armed pass.',
    },
    {
      kind: 'p',
      text: 'PRECONDITION — one setup: with one_setup ON (its default when unset) the seam declines every non-reject play (play_not_reject), so under market_in_zone only reject arms can place. Turn one_setup OFF to trade the other conditions under strict; the 🎛 entry law boot line WARNs while both are on.',
    },
    {
      kind: 'p',
      text: 'The machine derives the type from the condition and refuses a contradiction by name — a stop entry authored for a reject fade is rejected rather than quietly turned into a limit, because a silent correction hides a plan that has misunderstood its own play.',
    },
    { kind: 'h', text: 'What has to be true before a stop entry is placed' },
    {
      kind: 'p',
      text: 'A stop entry only makes sense while the market is still on the resting side of its trigger: a buy stop needs price BELOW the trigger, a sell stop needs price ABOVE it. If the market is already at or past the trigger the order would fire the instant it reached the broker, at whatever the market is now rather than at the level the plan chose — so the arm is cancelled instead, and the line says which side it found: "accepted through (stop side): price 29515.25 <= trigger 29590.50".',
    },
    {
      kind: 'p',
      text: 'The boundary is not the same as a limit\u2019s. A limit sitting exactly at its price still rests; a stop sitting exactly at its trigger fires. So the stop test is at-or-through and the limit test is strictly-through, and they are two separate checks chosen by order kind rather than one shared one. Until 2026-09-05 the stop side borrowed the limit test, which inverted every answer it gave: it cancelled the valid stops and placed the ones the market had already run past.',
    },
    {
      kind: 'p',
      text: 'If the guard cannot answer at all — no price this cycle, no trigger, a side it does not recognise — nothing happens. The arm is left exactly as it is for the next cycle, the line reads "NOT adjudicated", and it is counted. Not knowing is never a reason to cancel a live order.',
    },
    {
      kind: 'p',
      text: 'And the order has to be one NinjaTrader will actually work. A stop entry is refused outright unless the AddOn that answered on the wire is new enough to place the trigger in the stop-price slot: "addon build predates the stop-slot fix (build_id=…)". Between deploying the bot and recompiling the AddOn in NinjaTrader that refusal is the expected state — limits are unaffected and keep placing normally. Note the order, because it matters in that window: the wrong-way guard runs BEFORE the build floor, so an arm the market has already run past is cancelled outright rather than held back by the refusal. A refused arm stays armed and is retried next cycle; a cancelled one is gone.',
    },
    { kind: 'h', text: 'What "far" counts' },
    {
      kind: 'p',
      text: "An arm authored more than 3.0×ATR5m from the current price is logged and counted per side — 71% of arm-enabled scenarios were authored at a price the tape never reached in that version's life, and on one day six versions carried a short arm 62.25 points above the day's high. Nothing is refused for being far: the count exists so a week of evidence can decide whether that threshold should become a gate at all.",
    },
    { kind: 'h', text: 'THE ENTRY LAW (per condition — machine-enforced)' },
    {
      kind: 'code',
      title:
        'one table, one chokepoint — the validator REJECTS violations by name',
      lines: [
        'reject / fvg_entry    → touch ONLY · fade_requires_touch · stop ≥2 ticks beyond',
        'sweep_reclaim         → leg-1 touch at the sweep ref, leg-2 1m_mss (1x5m_close alt)',
        'reclaim               → 1x5m_close | 1m_mss · 2x5m_reserved',
        'breakout_retest       → touch at the retest + stop-entry fallback · 1x5m_close legal',
        'acceptance / hold     → time_hold | 1x5m_close · 2x5m_reserved',
        'breakdown/breakup     → the STORED 1x5m_close|2x5m_close + displacement',
        '                       (BD_MIN_CLOSES=1 = authoring default only)',
        '                       → 2x5m_close legal ONLY here',
        '',
        '15m confirms are DEAD — confirm_rule_15m_removed (rejected by name).',
        'Tokens are spelled the way the field accepts them: confirm.rule takes',
        'touch|1x5m_close|2x5m_close|1m_mss|time_hold, while death/flip.rule is a',
        'SEPARATE enum (2x5m|5m_close). Never move a token between the two.',
      ],
    },
    {
      kind: 'h',
      text: 'ARM SPLIT vs ARM SINGLE (class 38 · normalizer class 39)',
    },
    {
      kind: 'code',
      title: 'legs[] belong to sweep_reclaim and nothing else',
      lines: [
        'sweep_reclaim   → SPLIT: EXACTLY 2 legs · confirm=touch at the sweep ref',
        '                  leg 1 rests (wait_confirm false) · leg 2 chains (true)',
        '                  leg 2 rule = confirm2.rule ∈ 1m_mss | 1x5m_close',
        '                  top-level entry/stop/target mirror leg 1',
        'everything else → SINGLE: arm{} and NO legs',
        '                  (market_in_zone: every other condition; wait_confirm:true',
        '                   whenever the confirm is not a touch)',
        '                  (legacy: breakdown_continue, breakup_continue, reject,',
        '                   fvg_entry — wait_confirm:true)',
        'breakout_retest → arms under market_in_zone, SHADOW by default (recorded,',
        '                  never placed); a legacy plan never arms it (GAR-F4)',
        '',
        'Class 39 (owner ruling 2026-09-01): if the model STILL puts legs on a',
        'non-sweep condition, the machine drops the legs array, re-validates the',
        'single top-level arm and proceeds with a ⚖ WARN naming every dropped',
        'leg — instead of burning a retry. If the single arm is itself invalid',
        'the plan is rejected UNCHANGED with the original reason. Never a leg',
        'synthesized; never the reverse (one leg on sweep_reclaim stays a reject).',
        'Counter: arms_normalized_class39 (recorded, survives restarts).',
        '',
        'Why it is in the guide: 35 of 121 validator rejects in the 72h to',
        '2026-09-01 were legs on a non-sweep condition, and the prompt never',
        'said the rule. Class 38 makes the prompt state every restriction the',
        'validator enforces; the boot line 📜 prompt/validator contract counts',
        'them and fails loudly if one goes unstated.',
      ],
    },
    { kind: 'h', text: 'The new confirm rules' },
    {
      kind: 'code',
      title: '1m-MSS and time_hold — the E5/E6 primitives',
      lines: [
        '1m_mss    : last confirmed 1m fractal swing (k=2) broken by a 1m CLOSE',
        '            beyond it with displacement ≥ MSS_MIN_DISP_ATR × ATR5m (0.5).',
        '            Closed bars only — a wick beyond the swing NEVER counts.',
        '            Renders "1m-MSS: MET/NOT-MET (swing <px> @<t>)".',
        'time_hold : price holds beyond the ref for confirm.hold_min minutes of',
        '            1m closes with no close back across — for acceptance/hold.',
        '            hold_min is STORED from the prose ("holds 3 minutes" →',
        '            hold_min: 3, refused at write if absent or different);',
        '            none stored → ACCEPT_HOLD_MIN (10), named as the default.',
        'stop_entry: the breakout-retest fallback — a STOP-MARKET entry beyond the',
        '            break candle after RETEST_WAIT_BARS (6) no-retest bars,',
        '            STOP_ENTRY_OFFSET_TICKS (2) beyond. THREE gates, in the order',
        '            they actually run: STOP_ENTRY_SEAM · the stop-side',
        '            wrong-way guard (at-or-through = cancelled, never placed)',
        '            · the AddOn build floor, LAST, inside the wire call (the',
        '            received build must prove the trigger reaches the',
        '            stop-price slot).',
      ],
    },
    { kind: 'h', text: 'Entry-mechanics knobs' },
    {
      kind: 'p',
      text: "BD_MIN_CLOSES (1) · BD_MIN_DISP_ATR (1.0) · MSS_MIN_DISP_ATR (0.5) · ACCEPT_HOLD_MIN (10) · STOP_ENTRY_OFFSET_TICKS (2) · RETEST_WAIT_BARS (6) · STOP_ENTRY_SEAM (off). BD_MIN_CLOSES and ACCEPT_HOLD_MIN are AUTHORING DEFAULTS: a scenario's stored confirm.rule / confirm.hold_min governs its evaluation, and the env value is read only when nothing valid is stored (the card chip then says \"authoring default\"). Default confirm = 1x5m_close; a sweep_reclaim arm may split into TWO child orders (leg 1 touch + leg 2 chained) — either leg's stop-out cancels the sibling's unfilled order (no doubling into a failed level).",
    },
    { kind: 'h', text: 'THE A-SETUP (the chained play)' },
    {
      kind: 'code',
      title: 'sweep → displacement → FVG retrace, at a fresh Tier-1 origin',
      lines: [
        'S1 sweep_reclaim : liquidity pool swept (ONH/EQH) + reclaim close',
        '        │  chain_after: S1',
        '        ▼',
        'S2 fvg_entry    : the displacement gap retraces into the FVG band',
        '        entry_mode = ce (edge only for A-grade HTF-confluent origins)',
        '        stop beyond the sweep extreme · T1 = first opposing pool',
        '        runner = the draw (nearest opposing liquidity beyond T1) — vocabulary only: no partial exit exists, the whole position closes at once',
        '',
        'a bare fvg_entry with NO sweep precursor at a non-A/B origin',
        'gets a WARN at write — the raw-FVG null (40k sample) says it',
        'has no standalone edge.',
      ],
    },
    { kind: 'h', text: 'No-trade is a trade' },
    {
      kind: 'p',
      text: 'The planner is now SHOWN which levels can carry a waterfall: the facts block states the displacement floor for the cycle (1.0×ATR5m, resolved) and, per seated level, the measured displacement since its break — or "none — no break". A breakdown_continue authored below the floor is refused at write, and before 2026-09-03 that number was enforced without ever being stated. Sitting out is a position. The gates the planner is taught: balance day → edges only or skip · opening gap >1.2×ATR or outside-range open → never fade · no A/B zone in reach AND no pool swept by 09:30 CT → skip the day · lunch 12:00–13:30 CT — the window kernel.LunchWindowCT() resolves — refuses entries on BOTH paths since 2026-09-09: the band is read in executeDecisionWithRecord (trader/auto_trader_orders.go:281), by the adherence grader, and — since dispatch 104 — in maybeManageArmedOrdersAt before the scenario loop. Until then no band predicate appeared in trader/armed_executor.go at all, so with plan_mode=strict, where a resting order is the only way in, it refused nothing; an arm resting when the band opens is now cancelled rather than grandfathered · Tier-1 news → stand aside. A real skip looks like: "no_trade: balance day — no A/B zone in reach by 09:30 CT, skip" — that is a decision, not a failure.',
    },
  ],
}
