#!/bin/bash
# q07 — per-trade risk as it actually ran: stop distances (armed_orders), worst trades, MAE/MFE, fees
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
S() { echo "--- $1"; sqlite3 -header "$DB" "$2"; }
S "armed_orders: stop distance pts by state (all rows)" "SELECT state, COUNT(*) n, ROUND(MIN(ABS(entry_px-stop_px)),2) mn, ROUND(AVG(ABS(entry_px-stop_px)),2) mean, ROUND(MAX(ABS(entry_px-stop_px)),2) mx FROM armed_orders WHERE entry_px>0 AND stop_px>0 GROUP BY state ORDER BY n DESC;"
S "armed_orders: stop distance pts, ordered (all with prices) — for quantiles" "SELECT ROUND(ABS(entry_px-stop_px),2) d FROM armed_orders WHERE entry_px>0 AND stop_px>0 ORDER BY 1;"
S "armed_orders: post-0B (created >= 2026-09-02 07:49 CT) stop distances, ids" "SELECT id, session, scenario, side, ROUND(ABS(entry_px-stop_px),2) stop_pts, ROUND(ABS(target_px-entry_px),2) tgt_pts, state, datetime(strftime('%s',created_at),'unixepoch','-5 hours') created_ct FROM armed_orders WHERE datetime(strftime('%s',created_at),'unixepoch') >= '2026-09-02 12:49:00' AND entry_px>0 AND stop_px>0 ORDER BY id;"
S "sample trades: worst 8 by pnl_corrected" "SELECT id, plan_session, cited_scenario_id, side, entry_price, exit_price, pnl_corrected, ROUND((exit_price-entry_price)*CASE WHEN lower(side) LIKE 'long%' OR lower(side)='buy' THEN 1 ELSE -1 END,2) pts, close_reason, source FROM trader_positions WHERE plan_id<>'' AND pnl_corrected IS NOT NULL AND source<>'e7_farside_test' ORDER BY pnl_corrected ASC LIMIT 8;"
S "sample trades: best 5" "SELECT id, plan_session, cited_scenario_id, side, pnl_corrected, close_reason FROM trader_positions WHERE plan_id<>'' AND pnl_corrected IS NOT NULL AND source<>'e7_farside_test' ORDER BY pnl_corrected DESC LIMIT 5;"
S "sample: close_reason distribution" "SELECT COALESCE(close_reason,'<null>') cr, COUNT(*) n, ROUND(SUM(pnl_corrected),2) sum, ROUND(AVG(pnl_corrected),2) avg FROM trader_positions WHERE plan_id<>'' AND pnl_corrected IS NOT NULL AND source<>'e7_farside_test' GROUP BY 1 ORDER BY n DESC;"
S "sample: fee column" "SELECT SUM(fee<>0) nonzero_fee, COUNT(*) n, MIN(fee), MAX(fee) FROM trader_positions WHERE plan_id<>'' AND pnl_corrected IS NOT NULL AND source<>'e7_farside_test';"
S "sample: mae/mfe populated + sign convention (ids, side, mae, mfe, pnl)" "SELECT COUNT(*) n, SUM(mae IS NOT NULL AND mae<>0) mae_set, SUM(mfe IS NOT NULL AND mfe<>0) mfe_set, ROUND(MIN(mae),2), ROUND(MAX(mae),2), ROUND(MIN(mfe),2), ROUND(MAX(mfe),2) FROM trader_positions WHERE plan_id<>'' AND pnl_corrected IS NOT NULL AND source<>'e7_farside_test';"
S "sample: mae/mfe first 6 rows for units check" "SELECT id, side, entry_price, exit_price, mae, mfe, pnl_corrected FROM trader_positions WHERE plan_id<>'' AND pnl_corrected IS NOT NULL AND source<>'e7_farside_test' AND mae IS NOT NULL ORDER BY id LIMIT 6;"
S "ab_confirm_log: non-counterfactual rows, mae_r/mfe_r summary" "SELECT is_counterfactual, COUNT(*) n, ROUND(AVG(mae_r),3) mae_r_avg, ROUND(MIN(mae_r),3) mae_r_min, ROUND(AVG(mfe_r),3) mfe_r_avg, ROUND(AVG(net_pnl),2) net_pnl_avg, SUM(net_pnl IS NOT NULL) net_set FROM ab_confirm_log GROUP BY 1;"
S "ab_confirm_log: rule/condition x n" "SELECT rule, condition, COUNT(*) n, SUM(is_counterfactual=0) real FROM ab_confirm_log GROUP BY 1,2 ORDER BY n DESC LIMIT 12;"
S "trader_fills commission column (era)" "SELECT COUNT(*), SUM(COALESCE(commission,0)<>0), ROUND(SUM(commission),2) FROM trader_fills WHERE filled_at >= '2026-08-19';" 
