#!/bin/bash
# q15 — filled arms: stop/target pts, planned RR, matched position P&L (realised R); post-0B and post-strict trade rate
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
S() { echo "--- $1"; sqlite3 -header "$DB" "$2"; }
S "filled arms (all): id, session, scenario, side, entry, stop_pts, tgt_pts, planned RR, fill_price, updated CT" "SELECT id, session, scenario, side, entry_px, ROUND(ABS(entry_px-stop_px),2) stop_pts, ROUND(ABS(target_px-entry_px),2) tgt_pts, ROUND(ABS(target_px-entry_px)/ABS(entry_px-stop_px),2) rr, fill_price, datetime(strftime('%s',updated_at),'unixepoch','-5 hours') upd_ct FROM armed_orders WHERE state='filled' ORDER BY id;"
S "armed_entry/reconcile positions since 08-31 (arm fills materialised): id, entry CT, side, entry, exit, pnl, pts" "SELECT id, datetime(entry_time/1000,'unixepoch','-5 hours') et, side, entry_price, exit_price, pnl_corrected, source, cited_scenario_id FROM trader_positions WHERE entry_time >= 1787115600000 AND source IN ('armed_entry','reconcile') ORDER BY id;"
S "planned RR across ALL arms with prices (mean/min/max)" "SELECT COUNT(*) n, ROUND(AVG(ABS(target_px-entry_px)/ABS(entry_px-stop_px)),2) rr_mean, ROUND(MIN(ABS(target_px-entry_px)/ABS(entry_px-stop_px)),2) rr_min, ROUND(MAX(ABS(target_px-entry_px)/ABS(entry_px-stop_px)),2) rr_max FROM armed_orders WHERE entry_px>0 AND stop_px>0 AND target_px>0;"
S "trade rate: positions per CT day since 0B (2026-09-02 07:49 CT = 1788353340000)" "SELECT date(entry_time/1000,'unixepoch','-5 hours') d, COUNT(*) n, GROUP_CONCAT(source) src FROM trader_positions WHERE entry_time >= 1788353340000 GROUP BY 1;"
S "strict since when? first entry_gate strict refusal in decision_records" "SELECT MIN(datetime(timestamp,'-5 hours')), COUNT(*) FROM decision_records WHERE execution_log LIKE '%strict%' AND timestamp >= '2026-09-01';"
S "decision-path refusals by class since 09-02 (execution_log LIKE entry_gate)" "SELECT date(timestamp,'-5 hours') d, COUNT(*) FROM decision_records WHERE timestamp >= '2026-09-02' AND execution_log LIKE '%entry_gate%' GROUP BY 1;"
S "arm refusal counters (system_config arm_refusals_0b) since 09-02" "SELECT key, value FROM system_config WHERE key LIKE 'arm_refusals_0b:%' AND (key LIKE '%2026-09-02%' OR key LIKE '%2026-09-03%' OR key LIKE '%2026-09-04%') ORDER BY key;"
S "armed rows 104/105 + broker latest snapshot" "SELECT id, state, signal_id, entry_px, stop_px, target_px, condition, boot_id, datetime(strftime('%s',created_at),'unixepoch','-5 hours') created_ct FROM armed_orders WHERE id IN (104,105);"
S "latest nt8_order_snapshots" "SELECT id, account, reason, order_count, working_count, datetime(received_at_ms/1000,'unixepoch','-5 hours') recv_ct FROM nt8_order_snapshots ORDER BY id DESC LIMIT 3;"
S "1d closes: 08-17 and 09-03 (drift over the window)" "SELECT date(open_time_ms/1000,'unixepoch','-5 hours') d, c FROM bars WHERE symbol='MNQ' AND tf='1d' AND open_time_ms BETWEEN 1787115600000-86400000*2 AND 1788763200000 ORDER BY 1;"
