#!/bin/bash
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "=== A. plan_id='UNRESOLVABLE' rows, all-time ==="
sqlite3 "$DB" "SELECT id, plan_id, source, pnl_corrected, plan_session, datetime(entry_time/1000,'unixepoch','-5 hours') FROM trader_positions WHERE plan_id='UNRESOLVABLE' ORDER BY id;"
echo "=== B. count + sum ==="
sqlite3 "$DB" "SELECT COUNT(*), ROUND(SUM(pnl_corrected),2) FROM trader_positions WHERE plan_id='UNRESOLVABLE';"
echo "=== C. distinct plan_id values in era (id>=521) ==="
sqlite3 "$DB" "SELECT CASE WHEN plan_id='' THEN '(empty)' WHEN plan_id IS NULL THEN '(null)' WHEN plan_id='UNRESOLVABLE' THEN 'UNRESOLVABLE' ELSE '(real)' END k, COUNT(*) FROM trader_positions WHERE id>=521 GROUP BY k;"
echo "=== D. the 7 ids the report calls EMPTY-condition ==="
sqlite3 -header "$DB" "SELECT id, plan_id, cited_scenario_id, plan_session, pnl_corrected, source FROM trader_positions WHERE id IN (530,539,545,546,566,571,580);"
echo "=== E. n=65 sample: exclusions ==="
sqlite3 "$DB" "SELECT COUNT(*) n_era FROM trader_positions WHERE plan_id IS NOT NULL AND plan_id<>'' AND id>=521;"
sqlite3 "$DB" "SELECT COUNT(*) n65, ROUND(SUM(pnl_corrected),2) FROM trader_positions WHERE plan_id IS NOT NULL AND plan_id<>'' AND id>=521 AND source<>'e7_farside_test' AND pnl_corrected IS NOT NULL;"
echo "=== F. compliant (exclude UNRESOLVABLE) ==="
sqlite3 "$DB" "SELECT COUNT(*) n, ROUND(SUM(pnl_corrected),2) s, ROUND(AVG(pnl_corrected),4) m FROM trader_positions WHERE plan_id IS NOT NULL AND plan_id<>'' AND plan_id<>'UNRESOLVABLE' AND id>=521 AND source<>'e7_farside_test' AND pnl_corrected IS NOT NULL;"
echo "=== G. UNRESOLVABLE within the 65 sample ==="
sqlite3 -header "$DB" "SELECT id, ROUND(pnl_corrected,2), plan_session, source, pnl_correction_note FROM trader_positions WHERE plan_id='UNRESOLVABLE' AND id>=521 AND source<>'e7_farside_test' AND pnl_corrected IS NOT NULL ORDER BY id;"
