import csv,json,pathlib,hashlib,re
root=pathlib.Path('/tmp/nofx-understanding-market-20260913'); out=pathlib.Path('/tmp/nofx-review-07'); manifest=pathlib.Path('/tmp/nofx-repo-understanding-20260913/docs/superpowers/reports/2026-09-13-repo-understanding')
a=next(a for a in json.load(open(manifest/'review-plan.json'))['assignments'] if a['id']==7)
notes={
'aster/trader_positions.go':'Signed position-risk JSON; absolute quantity and lowercase side; unchecked string assertions on required price/leverage fields can panic. Margin-change failures mostly log and return nil; leverage errors propagate.',
'binance/futures_account.go':'Cached wallet/available/unrealized balances. Income-derived GetTrades has no fill quantity, price, fee or side; GetClosedPnL nevertheless wraps those missing values. Per-symbol/from-ID SDK trade reads carry actual fill detail. Commission/PnL symbol discovery each capped at 1000 without pagination.',
'binance/futures_orders.go':'Hedge-mode market entry/close and Algo SL/TP; quantity-zero close reads signed positions. Opens cancel all symbol orders before validation. Selective cancel list errors omitted; bulk cancellation always nil. Grid placement ignores ReduceOnly, PositionSide, PostOnly and requested ClientID. Protection uses ClosePosition(true), ignoring requested quantity.',
'binance/futures_positions.go':'Caches signed position quantity. Margin mode mostly fail-open, leverage reads cached positions and sleeps five seconds after update. Sizing helper is margin allocation, not stop-risk. Hardcoded minimum notional 10. Decimal formatting uses rounding/fallback rather than authoritative step-multiple validation.',
'bitget/trader.go':'Constructor sets one-way account mode via POST and logs failure. HMAC/base64 signed V2 transport unwraps Data with 30-second timeout; manual GET query assembly lacks URL encoding. 15-second account caches, five-minute contract cache with shared timestamp; FormatQuantity rounds decimals and defaults to four.',
'bitget/trader_orders.go':'USDT-FUTURES cross-margin requests; market acknowledgement returned as FILLED, closes reduceOnly YES. Plan placement and cancellation paths; individual cancel errors discarded. GetOpenOrders merges ordinary/plan snapshots and swallows failed reads. Limit path honors ReduceOnly but not PostOnly or ClientID.',
'bitget/trader_positions.go':'15-second positions cache; absolute amount, lower side, numeric prices/time. History limited 100, converts fees and milliseconds; lacks record IDs/pagination.',
'bybit/order_sync.go':'Raw mainnet HMAC execution list through DefaultClient, no timeout or cursor. closedSize decides action; whole execution assigned one action even reversal. 24h sync sorts milliseconds, creates order/fill/position separately, existing order skips all repair; ticker has no stop.',
'bybit/trader.go':'Mainnet SDK constructor adds Referer header, not API key. Qty step public GET with no timeout; permanent cache and fallback step 1. FormatQuantity floors to step. SDK acknowledgement parser returns NEW.',
'gate/order_sync.go':'Latest max-100 fills locally filtered by start time, signed size/closeSize determine action. Quanto multiplier defaults to 1 on lookup failure. Sync uses trade-ID orders and separate writes; existing close trades replay into PositionBuilder without idempotency token enforcement here. No ticker shutdown.',
'gate/trader_orders.go':'USDT futures SDK. Base quantity divided by quanto then integer truncation; <=0 forced to one contract. Reduce-only closes; all market acks labeled FILLED. Margin setter is no-op, leverage risk-limit rejection becomes nil. Selective cancel ignores orderType; trigger classification ignores short direction. Open-order quantity uses multiplier fallback 1.',
'hyperliquid/order_sync.go':'24h user fills sorted and written as separate order/fill/PositionBuilder updates; trade-ID dedup prevents later repair after order insertion. Synthetic MARKET/maker=false fields. Unstoppable ticker.',
'hyperliquid/trader_account.go':'Combines spot USDC, perp summary and XYZ equity with partial auxiliary-read failures ignored. XYZ HTTP always mainnet; SDK calls use configured exchange. Status read error/absence returns FILLED with zero fill data. User fills Dir parsing and PnL fallback; zero-PnL closes omitted by GetClosedPnL. GetOpenOrders compares raw coin to input unlike other methods.',
'hyperliquid/trader_positions.go':'Perp and XYZ positions normalized separately; absolute amounts, pointer-safe optional prices; XYZ failure returns partial success. Margin mode is mutable trader-wide local bool consumed by leverage update.',
'indodax/trader_account.go':'Spot IDR balance and synthetic holdings: total equity counts IDR only, not valued crypto. Position entry equals current mark, unrealized zero; mark lookup errors ignored. ClosedPnL fetches only btc_idr and emits both buys/sells without quantity/entry/PnL; parse failure becomes nil success.',
'kucoin/order_sync.go':'Single-page max100 fills and recent fills; nanosecond timestamps, multiplier fallback BTC .001/other .01, positive close fee decides closing. Sorted sync separate writes, trade-ID skip on replay, no ticker shutdown. ToTradeRecord preserves parsed action.',
'kucoin/trader.go':'30-second signed futures transport with server-time offset and HMAC passphrase/partner. Timestamp failure resyncs but does not retry original request. Symbol conversion case-sensitive, not idempotent. Metadata cache all contracts five minutes. Quantity rounds lots and caps maximum, ignores lot-size/minimum.',
'kucoin/trader_account.go':'Cached USDT account overview; margin balance as wallet, explicit AccountEquity aliases avoid wallet-plus-PnL reconstruction.',
'kucoin/trader_positions.go':'Open nonzero positions, sign to lower side/absolute base quantity; missing multiplier defaults .001 for every symbol, missing leverage defaults 10. Cache plus explicit invalidation.',
'lighter/orders.go':'Stop wrappers to CreateStopOrder, auth/query order reads, SDK cancellation. Query errors return error in GetOrderStatus, but numeric fields remain strings. SL/TP selective cancel routes to all active orders; individual failure logged then nil. uint16 market index narrowed to uint8. Active-order URL debug log may include auth prefix.',
'lighter/trading.go':'SDK signed market/limit/protective transactions, multipart sendTx, local precision/market cache. Submission distinct internally but wrappers fabricate FILLED. pollForOrderIndex ignores txHash and takes max index. Normalize strips USDT before /USDT causing slash leftovers; lowercase suffix not stripped. 5% market/trigger execution band, 7d limit/30d stop expiry. Leverage always cross, margin setter defaults 10x on position read failure.',
'lighter/types.go':'JSON DTOs with string numeric order fields and trade position-before fields. parseFloat accepts empty as zero. Checksum uses Keccak nibble casing with only length validation; no hexadecimal validation and uppercase 0X prefix unsupported.',
'okx/trader_account.go':'Balance labels totalEq as wallet without totalEquity key; consumer adds UPL again. Local margin setting applied to requests; leverage failures swallowed. ClosedPnL incorrectly expects response envelope after doRequest unwrapped Data; quantity would remain contracts.',
'okx/trader_orders.go':'Hedge-style opens, mode-aware closes read fresh positions and cap quantity, but net-mode closes lack reduceOnly. ID/sCode acknowledgement labeled FILLED. Stops and cancels ignore item-level sCode accepted by transport. Selective algo cancellation ignores requested type. Open-order reads swallow errors and quantities stay contracts; synthetic _sl/_tp IDs need routing before cancellation.',
'okx/trader_positions.go':'Positions convert ctVal to base quantity when available; net negative position mislabeled long because only posSide short controls side. Metadata failure leaves contract units. Shared timestamp instrument cache; explicit position invalidation.'
}
rows=list(csv.DictReader(open(manifest/'go-functions.tsv'),delimiter='\t')); paths={f['path'] for f in a['files']}
basePurpose={
'GetBalance':'Read venue account data and map wallet/equity/available/unrealized fields for the shared account consumer.', 'GetPositions':'Read venue positions and normalize symbol, side, quantity and price fields into shared maps.',
'OpenLong':'Submit market buy entry after venue-specific sizing/leverage and pending-order cleanup.', 'OpenShort':'Submit market sell entry after venue-specific sizing/leverage and pending-order cleanup.',
'CloseLong':'Submit sell close; quantity zero requests current entire position.', 'CloseShort':'Submit buy close; quantity zero requests current entire position.',
'SetMarginMode':'Configure or request margin mode under this adapter’s semantics.', 'SetLeverage':'Request leverage using this adapter’s venue representation.',
'GetMarketPrice':'Resolve venue symbol and read current market price.', 'SetStopLoss':'Place protective stop for supplied position side.', 'SetTakeProfit':'Place profit-taking protection for supplied position side.',
'CancelStopLossOrders':'Request selective stop-loss cancellation; actual adapter filtering is documented in risks.', 'CancelTakeProfitOrders':'Request selective take-profit cancellation; actual adapter filtering is documented in risks.',
'CancelAllOrders':'Cancel ordinary and/or protective orders for the symbol; inspect adapter error handling.', 'CancelStopOrders':'Cancel protective-order set for the symbol; some adapters broaden scope.',
'GetOpenOrders':'Map ordinary/protective venue order snapshots to types.OpenOrder.', 'GetOrderStatus':'Translate venue order status and execution fields for caller polling.',
'GetClosedPnL':'Retrieve and translate recent closure records; missing values and history coverage are adapter-specific.', 'GetTrades':'Retrieve venue history and translate execution records for history synchronization.',
'FormatQuantity':'Format venue quantity with adapter-specific precision/unit conversion.', 'PlaceLimitOrder':'Translate types.LimitOrderRequest to venue limit placement and result.',
'CancelOrder':'Cancel a single order by provided venue identifier.', 'GetOrderBook':'Read and convert bid/ask levels to price/quantity pairs.',
'clearCache':'Invalidate cached balances and positions under mutexes.', 'InvalidatePositionCache':'Invalidate position cache and timestamp under mutex.',
'sign':'HMAC-SHA256 timestamp/method/path/body and encode base64 for authentication.', 'doRequest':'Serialize/sign/request venue HTTP endpoint; validate response and unwrap its Data.',
'convertSymbol':'Translate shared symbol to venue naming convention.', 'convertSymbolBack':'Translate venue naming to shared symbol.',
'getContract':'Read cached contract metadata or refresh through venue endpoint.', 'getInstrument':'Read cached OKX instrument metadata or fetch a single instrument.',
'NewBitgetTrader':'Create timeout/caches/auth client and POST account one-way position-mode change.', 'setPositionMode':'POST Bitget USDT-FUTURES one-way account mode; recognize already/same errors.',
'genBitgetClientOid':'Construct client order ID from two current clock readings.', 'NewBybitTrader':'Create mainnet SDK client, Referer transport and 15-second caches.',
'RoundTrip':'Set partner Referer header then delegate transport request.', 'getQtyStep':'Resolve/cache public linear contract quantity step; return 1 on failure.',
'parseOrderResult':'Check SDK result code and map orderId plus NEW acknowledgement.', 'getTradesViaHTTP':'Sign and fetch mainnet V5 execution list through DefaultClient.',
'parseTradesResult':'Decode weakly typed execution fields and derive action from side/closedSize.',
'cancelPlanOrders':'List Bitget plan type then cancel each returned ID.', 'cancelTriggerOrders':'List Gate trigger orders and cancel all returned IDs regardless of orderType.',
'cancelAlgoOrders':'List OKX conditional orders and cancel every algo ID regardless of orderType.',
'GetTradesForSymbol':'Read actual Binance per-symbol account fills since millisecond timestamp.', 'GetTradesForSymbolFromID':'Read actual Binance per-symbol account fills starting at trade ID.',
'GetCommissionSymbols':'Discover symbols with commission income since timestamp; bounded single page.', 'GetPnLSymbols':'Discover symbols with realized-PnL income since timestamp; bounded single page.',
'CalculatePositionSize':'Compute balance*riskPercent/100*leverage/price; does not reference stop distance.', 'GetMinNotional':'Return hardcoded 10.0 minimum quote notional.',
'CheckMinNotional':'Fetch price and refuse quantity*price below hardcoded minimum.', 'GetSymbolPrecision':'Extract LOT_SIZE decimal precision or default 3.',
'GetSymbolPricePrecision':'Extract PRICE_FILTER decimal precision or default 2.', 'FormatPrice':'Round to retrieved price decimals or two-decimal fallback.',
'getXYZDexBalance':'POST mainnet XYZ clearinghouse state and sum equity/unrealized/positions.', 'getXyzMarketPrice':'POST mainnet XYZ allMids and parse prefixed coin price.',
'GetRecentTrades':'Read recent KuCoin fills and convert quantity/action with same fallbacks as history.', 'ToTradeRecord':'Copy KuCoinTrade to shared TradeRecord and infer position side from action.',
'NewKuCoinTrader':'Build signed timeout client/caches and synchronize server clock.', 'syncServerTime':'Fetch timestamp and store local-minus-server offset.', 'getTimestamp':'Subtract synchronized offset from current milliseconds.',
'signPassphrase':'HMAC/base64 passphrase using account secret.', 'signPartner':'HMAC/base64 timestamp+partner+API key using static partner integration key.',
'quantityToLots':'Divide base quantity by multiplier, round to integer, cap maximum.', 'GetActiveOrders':'Ensure auth, resolve market, GET active account orders and validate application code.',
'getOrderIndexByTxHash':'Search active orders for exact OrderID match and return numeric index.',
'CreateOrder':'Resolve market/precision, sign market-or-limit transaction, submit multipart and optionally resolve index.', 'submitOrder':'Send signed transaction multipart; check application code; return submitted tx hash.',
'pollForOrderIndex':'Sleep 500ms and return highest active order index; txHash is logged but never matched.', 'normalizeSymbol':'Strip hardcoded suffixes then uppercase symbol.',
'getMarketInfo':'Find normalized symbol in fetched market list.', 'getMarketIndex':'Return dynamic uint16 market index or hardcoded fallback.',
'fetchMarketList':'Fetch active orderBooks and cache symbol/index/precision for one hour.', 'getFallbackMarketIndex':'Resolve fixed table of nine crypto market indices.',
'CreateStopOrder':'Sign reduce-only triggered IOC order with 30-day expiry and 5% execution band.', 'boolToUint8':'Map bool to 0/1 wire byte.', 'pow10':'Multiply int64 accumulator n times for fixed-point scaling.',
'parseFloat':'Parse float using Sscanf; empty is zero without error.', 'ToChecksumAddress':'Apply Keccak EIP-55 letter casing to length-40 address text.'
}
functions=[]
for r in rows:
 if r['path'] not in paths:continue
 name=r['name']; fileNote=notes[r['path'][7:]]; start=int(r['start_line']);end=int(r['end_line']); body='\n'.join((root/r['path']).read_text().splitlines()[start-1:end]); con=[]
 if name.startswith('SyncOrdersFrom'):purpose='Fetch rolling 24-hour fills, sort oldest-first, deduplicate by exchange account/trade ID, then independently create order, fill and PositionBuilder updates.'
 elif name=='StartOrderSync':purpose='Start unbounded periodic goroutine; no stop channel, cancellation handle or ticker.Stop.'
 elif name=='<anonymous>':purpose='Nested callback: chronological sort comparator or ticker-driven synchronization goroutine; owned by enclosing named function.'
 else:purpose=basePurpose[name]
 for call in ['doRequest','request','GetPositions','GetBalance','FormatQuantity','SetLeverage','CancelAllOrders','getContract','getInstrument','getMarketInfo','CreateOrder','CreateStopOrder','submitOrder','GetActiveOrders','CancelOrder','getTradesViaHTTP','parseTradesResult','GetTrades','getXYZDexBalance','getXyzMarketPrice','InvalidatePositionCache','getOrderIndexByTxHash','pollForOrderIndex','fetchMarketList','getFallbackMarketIndex','getQtyStep','sign','getTimestamp','syncServerTime','marginMode','ProcessTrade','CreateFill','GetOrderByExchangeID']:
  if re.search(r'\.'+call+r'\s*\(',body):con.append('Direct call expression: .'+call+' (receiver as in source; no inferred dynamic caller resolution).')
 if not con:con=['Boundary: '+purpose]
 functions.append({'path':r['path'],'name':name,'receiver':r['receiver'],'start_line':start,'end_line':end,'purpose':purpose,'connections':con,'invariants_or_risks':fileNote,'evidence':'A: manual source read; AST census only supplies source coordinates.'})
reads=[]
for f in a['files']:
 reads.append({'path':f['path'],'mode':'full/manual','ranges':[[1,f['lines']]],'sha256':hashlib.sha256((root/f['path']).read_bytes()).hexdigest(),'notes':notes[f['path'][7:]],'assigned':True})
extra=[('trader/types/interface.go',[[1,248]],'Shared 19-method and GridTrader contracts; selective cancellation semantics and numeric map consumers.'),('trader/okx/trader.go',[[148,158],[207,310]],'Data unwrapping, account simulated flag, naming and decimal formatting; relevant dependency excerpts only.'),('trader/auto_trader.go',[[625,705],[852,940]],'Config exchange constructor selection and exchange-specific sync startup; NT8 is separate branch.'),('trader/auto_trader_decision.go',[[120,149],[346,380]],'Equity fallback and status float64 consumers; NT close event separate.'),('store/position_builder.go',[[1,190]],'ProcessTrade action routing and close mutation show no per-trade dedup in observed path.'),('trader/okx/trader_margin_mode_test.go',[[1,247]],'Full offline recording transport tests exercise real request sites and margin mode.'),('trader/lighter/orders_test.go',[[1,421]],'Full tests: DTO and duplicated conversion logic; mock HTTP test bypasses production method.'),('trader/kucoin/order_sync_test.go',[[1,125]],'Credential-gated network test constructors; deliberately not run.'),('trader/binance/futures_test.go',[[1,95]],'Mock SDK suite setup excerpt; not full suite review.'),('docs/superpowers/CLAUDE-canon.md',[[1,128]],'Full tracked canon: keeper ownership, no manual beating, verified worktrees.'),('docs/superpowers/AUDIT-CHECKLIST.md',[[1,190],[2281,2320]],'Initial bug classes and R1-R10 pre-audit rules; excerpts, not full checklist.'),('docs/superpowers/SYSTEM-MAP.md',[[245,267]],'Executor and SIM boundary; historical line citations remain hypotheses.'),('docs/superpowers/VL-TRADING-RULEBOOK-v1.md',[[215,227]],'Owner policy separated from current enforcement; daily loss choice preserved.')]
for path,ranges,note in extra:
 n=len((root/path).read_text().splitlines()); ranges=[[s,min(e,n)] for s,e in ranges]; full=ranges==[[1,n]]
 reads.append({'path':path,'mode':'full/manual' if full else 'excerpts/manual','ranges':ranges,'sha256':hashlib.sha256((root/path).read_bytes()).hexdigest(),'notes':note,'assigned':False})
json.dump({'assignment':7,'base':'63968be62e44db2fb07a92883e02127b9064b0be','files':reads,'unread':[],'coverage_note':'25 assigned source files fully read. Additional dependency excerpts do not imply whole-file coverage. AGENTS instruction read separately; historical graph inspected as structured subset.'},open(out/'reads.json','w'),indent=2)
json.dump(functions,open(out/'functions.json','w'),indent=2)
g=json.load(open('/home/hoang/nofx-untracked-stash-20260816/.understand-anything/knowledge-graph.json'));ns=[n for n in g['nodes'] if n.get('filePath') in paths]; ids={n['id'] for n in ns};es=[e for e in g['edges'] if e['source'] in ids and e['type'] not in ['contains','exports']]
json.dump({'base':a.get('base','63968be62e44db2fb07a92883e02127b9064b0be'),'historical_source':'July 10 @ 7a8adce0; stash knowledge-graph.json','historical_subset_counts':{'nodes':len(ns),'outgoing_noncontainment_edges':len(es)},'inspection':'All 25 historic file summaries and first 20 outgoing dependency/testing edges read; whole graph not manually certified. Current source is authority.','corrections':[{'path':'trader/bybit/trader.go','old':'API-key-injecting round-tripper','current':'RoundTrip sets Referer only; SDK owns auth.'},{'path':'trader/indodax/trader_account.go','old':'closed PnL reconstruction','current':'BTCIDR history rows lack realized PnL and quantity and include buys; not PnL reconstruction.'},{'path':'trader/lighter/orders_test.go','old':'tested_by graph implies coverage','current':'Tests mostly decode DTOs/copy conversion logic; mock-server test does not call GetActiveOrders.'}], 'evidenced_edges':[{'source':'trader/auto_trader.go:632','target':'trader/{binance,bybit,okx,bitget,gate,kucoin,hyperliquid,aster,lighter,indodax}','relation':'exchange-selected alternative constructors; distinct from ninjatrader branch'},{'source':'trader/{bybit,gate,kucoin,hyperliquid}/order_sync.go','target':'store/position_builder.go:29','relation':'Direct ProcessTrade call after separate CreateOrder/CreateFill writes'},{'source':'trader/okx/trader_account.go:168','target':'trader/okx/trader.go:256','relation':'GetClosedPnL expects envelope but doRequest returns Data'},{'source':'trader/lighter/trading.go:443','target':'trader/lighter/orders.go:204','relation':'pollForOrderIndex picks highest returned active index without matching txHash'}]},open(out/'graph.json','w'),indent=2)
print(len(reads),'reads;',len(functions),'function/callback records;',sum(1 for f in functions if f['name']!='<anonymous>'),'named functions')
