#!/bin/bash
# q02: trader_positions era premise re-measure (entry_time is epoch ms)
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
E="strftime('%s','2026-08-15')*1000"
echo "--- all-time / era counts"
sqlite3 "$DB" "select count(*) all_time, sum(entry_time>=$E) era, sum(entry_time>=$E and pnl_corrected is not null) era_pnl_nn, sum(entry_time>=$E and plan_id is not null) era_plan, sum(entry_time>=$E and cited_scenario_id is not null and cited_scenario_id<>'') era_cited, sum(pnl_corrected is null) alltime_pnl_null, sum(entry_time>=$E and mae is not null) era_mae_nn, sum(entry_time>=$E and mfe is not null) era_mfe_nn, sum(entry_time>=$E and mae is not null and mae<>0) era_mae_nonzero from trader_positions"
echo "--- source"
sqlite3 "$DB" "select source, count(*) from trader_positions group by 1"
echo "--- plan_session"
sqlite3 "$DB" "select coalesce(plan_session,'NULL'), count(*) from trader_positions group by 1"
echo "--- status"
sqlite3 "$DB" "select status, count(*) from trader_positions group by 1"
echo "--- era usable (source<>'e7_farside_test', pnl_corrected not null, not UNRESOLVABLE note)"
sqlite3 "$DB" "select count(*), sum(pnl_corrected), round(avg(pnl_corrected),2), sum(pnl_corrected>0) wins, sum(pnl_corrected<0) losses, sum(pnl_corrected=0) flat from trader_positions where entry_time>=$E and source<>'e7_farside_test' and pnl_corrected is not null and coalesce(pnl_correction_note,'') not like '%UNRESOLVABLE%'"
echo "--- era by close_reason"
sqlite3 "$DB" "select coalesce(close_reason,'NULL'), count(*), round(sum(pnl_corrected),2) from trader_positions where entry_time>=$E and source<>'e7_farside_test' and pnl_corrected is not null group by 1 order by 2 desc"
echo "--- era pnl_correction_note distinct prefixes"
sqlite3 "$DB" "select substr(coalesce(pnl_correction_note,'NULL'),1,40), count(*) from trader_positions where entry_time>=$E group by 1 order by 2 desc limit 15"
echo "--- era by trade day CT"
sqlite3 "$DB" "select date(entry_time/1000,'unixepoch','-5 hours') d, count(*), round(sum(pnl_corrected),2), sum(pnl_corrected>0) from trader_positions where entry_time>=$E and source<>'e7_farside_test' and pnl_corrected is not null group by 1 order by 1"
