#!/bin/bash
# q04: first-pass store summaries — arms, ab_confirm_log, touch_outcomes, plans
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "--- armed_orders by state / scenario / kind"
sqlite3 "$DB" "select state, count(*) from armed_orders group by 1 order by 2 desc"
sqlite3 "$DB" "select scenario, state, count(*) from armed_orders group by 1,2 order by 1,3 desc"
sqlite3 "$DB" "select coalesce(kind,'NULL') kind, coalesce(entry_class,'NULL') ec, count(*) from armed_orders group by 1,2"
echo "--- armed_orders filled rows (state like fill)"
sqlite3 "$DB" "select id, plan_id, session, scenario, side, entry_px, stop_px, target_px, state, state_reason, fill_price, datetime(strftime('%s',created_at),'unixepoch','-5 hours') created_ct from armed_orders where state like '%fill%' or fill_price is not null order by id"
echo "--- ab_confirm_log by condition/rule (real vs counterfactual)"
sqlite3 "$DB" "select condition, rule, is_counterfactual, count(*) n, round(avg(net_pnl),2) avg_net, round(sum(net_pnl),2) sum_net, sum(net_pnl>0) wins, round(avg(mfe_r),2) mfe_r, round(avg(mae_r),2) mae_r from ab_confirm_log group by 1,2,3 order by 1,2,3"
echo "--- ab_confirm_log outcome distribution"
sqlite3 "$DB" "select outcome, is_counterfactual, count(*) from ab_confirm_log group by 1,2"
echo "--- touch_outcomes by level_kind"
sqlite3 "$DB" "select level_kind, sum(outcome='hold') h, sum(outcome='break') b, sum(outcome='ambiguous_horizon') amb, count(*) n, round(1.0*sum(outcome='hold')/nullif(sum(outcome in ('hold','break')),0),3) p_hold from touch_outcomes group by 1 order by n desc"
echo "--- touch_outcomes by session"
sqlite3 "$DB" "select session, sum(outcome='hold') h, sum(outcome='break') b, sum(outcome='ambiguous_horizon') amb, count(*) n from touch_outcomes group by 1"
echo "--- touch_outcomes by session x kind (RTH-L premise: breaks 68% n=63)"
sqlite3 "$DB" "select session, level_kind, sum(outcome='hold') h, sum(outcome='break') b, count(*) n from touch_outcomes group by 1,2 having n>=15 order by 1, n desc"
echo "--- touch_outcomes date range"
sqlite3 "$DB" "select min(datetime(opened_at_ms/1000,'unixepoch','-5 hours')), max(datetime(opened_at_ms/1000,'unixepoch','-5 hours')), count(distinct date(opened_at_ms/1000,'unixepoch','-5 hours')) from touch_outcomes"
echo "--- plans lifecycle / session / trigger_reason"
sqlite3 "$DB" "select lifecycle, count(*) from plans group by 1"
sqlite3 "$DB" "select session, count(*), min(trade_date), max(trade_date) from plans group by 1"
sqlite3 "$DB" "select trigger_reason, count(*) from plans group by 1 order by 2 desc limit 10"
echo "--- plans per trade_date (era)"
sqlite3 "$DB" "select trade_date, count(*), group_concat(session||':'||version) from plans where trade_date>='2026-08-15' group by 1 order by 1"
