#!/bin/bash
# q06: planner facts, rejected prompts, decision_records cadence + refusals
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "--- planner_read_facts: bias ai vs tree vs regime, tokens_in"
sqlite3 -header "$DB" "select trade_date, session, version, bias_ai, bias_tree, bias_regime, tokens_in, void_count, round(stop_floor_pts,1) sf, round(atr5m,1) atr, scope_bars from planner_read_facts order by trade_date, session"
echo "--- agreement counts"
sqlite3 "$DB" "select sum(bias_ai=bias_tree) ai_eq_tree, sum(bias_ai=bias_regime) ai_eq_regime, sum(bias_tree=bias_regime) tree_eq_regime, count(*) from planner_read_facts"
echo "--- planner_rejected_prompts reasons"
sqlite3 "$DB" "select substr(reject_reason,1,70), count(*) from planner_rejected_prompts group by 1 order by 2 desc limit 20"
sqlite3 "$DB" "select trade_date, session, count(*), max(attempt) from planner_rejected_prompts group by 1,2 order by 1,2"
echo "--- decision_records era: by cycle_type and CT day count"
sqlite3 "$DB" "select coalesce(cycle_type,'NULL'), count(*), min(date(timestamp,'-5 hours')), max(date(timestamp,'-5 hours')) from decision_records where date(timestamp,'-5 hours')>='2026-08-15' group by 1 order by 2 desc"
echo "--- decision_records era: per-day count and median gap (cadence) for last 5 trading days"
sqlite3 "$DB" "select date(timestamp,'-5 hours') d, count(*) n, round((strftime('%s',max(timestamp))-strftime('%s',min(timestamp)))/60.0/nullif(count(*)-1,0),1) avg_gap_min from decision_records where date(timestamp,'-5 hours')>='2026-08-31' group by 1 order by 1"
echo "--- decision_records era: entry_gate refusals in execution_log (decision path) by day"
sqlite3 "$DB" "select date(timestamp,'-5 hours') d, count(*) from decision_records where date(timestamp,'-5 hours')>='2026-08-15' and execution_log like '%entry_gate%' group by 1 order by 1"
echo "--- decision_records era: decisions json action distribution (open_long/open_short/wait/hold/close)"
sqlite3 "$DB" "select date(timestamp,'-5 hours')>='2026-09-02' post0b, case when decision_json like '%\"action\":\"open_long\"%' or decision_json like '%\"action\": \"open_long\"%' then 'open_long' when decision_json like '%\"action\":\"open_short\"%' or decision_json like '%\"action\": \"open_short\"%' then 'open_short' when decision_json like '%\"action\":\"wait\"%' or decision_json like '%\"action\": \"wait\"%' then 'wait' when decision_json like '%\"action\":\"hold\"%' or decision_json like '%\"action\": \"hold\"%' then 'hold' when decision_json like '%close%' then 'close' else 'other' end act, count(*) from decision_records where date(timestamp,'-5 hours')>='2026-08-15' group by 1,2 order by 1,3 desc"
echo "--- ai latency era"
sqlite3 "$DB" "select round(avg(ai_latency_ms)/1000.0,1) avg_s, max(ai_latency_ms)/1000 max_s, count(*) from decision_records where date(timestamp,'-5 hours')>='2026-08-15' and ai_latency_ms>0"
echo "--- system_config counters"
sqlite3 "$DB" "select key, value from system_config where key like 'arm_refusals%' or key like 'dayplan_replans%' or key like '%gate%' order by key limit 40"
