#!/bin/bash
# q08: 09-04 arm churn, 09-03 silence gaps, level_stats/touch_episodes shape, decision cadence gaps era-wide
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "--- 09-04 NY S2 SHORT arm rows: count, distinct reasons, first/last"
sqlite3 "$DB" "select count(*), min(id), max(id), min(datetime(strftime('%s',created_at),'unixepoch','-5 hours')), max(datetime(strftime('%s',created_at),'unixepoch','-5 hours')) from armed_orders where plan_id like '2026-09-04:NY:%' and scenario='S2'"
sqlite3 "$DB" "select state, substr(state_reason,1,50), count(*) from armed_orders where plan_id like '2026-09-04:NY:%' and scenario='S2' group by 1,2 order by 3 desc"
sqlite3 "$DB" "select id, armed_under_version, placement_seq, signal_id is not null and signal_id<>'' has_sig, boot_id, datetime(strftime('%s',created_at),'unixepoch','-5 hours') c, datetime(strftime('%s',updated_at),'unixepoch','-5 hours') u from armed_orders where plan_id like '2026-09-04:NY:%' and scenario='S2' order by id"
echo "--- nt8_order_snapshots on 09-04 10:00-11:00 CT: working_count over time"
sqlite3 "$DB" "select datetime(received_at_ms/1000,'unixepoch','-5 hours') t, working_count, order_count, reason from nt8_order_snapshots where received_at_ms between strftime('%s','2026-09-04 15:00:00')*1000 and strftime('%s','2026-09-04 16:00:00')*1000 order by 1 limit 60"
echo "--- decision_records: gaps > 10 min inside NY session (08:30-14:45 CT), era, per day"
sqlite3 "$DB" "with t as (select timestamp, date(timestamp,'-5 hours') d, time(timestamp,'-5 hours') tm, lag(timestamp) over (order by timestamp) prev from decision_records where date(timestamp,'-5 hours')>='2026-08-15') select d, tm, round((strftime('%s',timestamp)-strftime('%s',prev))/60.0,1) gap_min from t where tm between '08:30' and '14:45' and (strftime('%s',timestamp)-strftime('%s',prev))/60.0>10 order by d, tm"
echo "--- 09-03 decision timeline 09:00-12:30 CT (count per 10-min bucket)"
sqlite3 "$DB" "select substr(time(timestamp,'-5 hours'),1,4)||'0' b, count(*), sum(cycle_type='watch') w from decision_records where date(timestamp,'-5 hours')='2026-09-03' and time(timestamp,'-5 hours') between '08:30' and '13:00' group by 1 order by 1"
echo "--- level_stats / touch_episodes shape"
sqlite3 "$DB" "select min(session_day), max(session_day), count(*), count(distinct session_day) from level_stats"
sqlite3 "$DB" "select kind, sum(touched), sum(reacted), sum(broke_clean), sum(chopped), count(*) from level_stats group by 1 order by 2 desc limit 12"
sqlite3 "$DB" "select min(session_day), max(session_day), count(*), count(distinct session_day), count(distinct label) from touch_episodes"
sqlite3 "$DB" "select shape, count(*) from touch_episodes group by 1 order by 2 desc"
echo "--- touch_episodes by label top"
sqlite3 "$DB" "select label, count(*), round(avg(penetration_pts),1), round(avg(vol_ratio),2) from touch_episodes group by 1 order by 2 desc limit 15"
