#!/bin/bash
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "--- armed_orders kind x condition x state (non-test)"
sqlite3 "$DB" "select coalesce(kind,'NULL') kind, coalesce(condition,'NULL') cond, state, count(*) from armed_orders where session not like 'TEST%' group by 1,2,3 order by 1,2,3"
echo "--- arms in ASIA/LONDON after 0B (09-02 07:49 CT), by state"
sqlite3 "$DB" "select session, state, substr(state_reason,1,45), count(*), min(datetime(strftime('%s',created_at),'unixepoch','-5 hours')) from armed_orders where session in ('ASIA','LONDON') and datetime(strftime('%s',created_at),'unixepoch','-5 hours')>='2026-09-02 07:49' group by 1,2,3"
echo "--- distinct arms (plan_id, scenario, entry_px) non-test: count and fill count"
sqlite3 "$DB" "with d as (select plan_id, scenario, round(entry_px,2) e, max(state='filled') f, max(state_reason like 'level accepted through%') mk from armed_orders where session not like 'TEST%' group by 1,2,3) select count(*) distinct_arms, sum(f) filled, sum(mk) marketable_killed from d"
echo "--- era arms funnel per session (distinct arms)"
sqlite3 "$DB" "with d as (select session, plan_id, scenario, round(entry_px,2) e, max(state='filled') f, max(state_reason like 'level accepted through%') mk, max(state_reason like 'no order_update%') stale, max(state_reason like 'gate changed%') gate from armed_orders where session not like 'TEST%' group by 1,2,3,4) select session, count(*), sum(f), sum(mk), sum(stale), sum(gate) from d group by 1"
echo "--- decision_records 09-03 12:00-14:45 CT: per 10-min bucket, and open intents that day"
sqlite3 "$DB" "select substr(time(timestamp,'-5 hours'),1,4)||'0' b, count(*) from decision_records where date(timestamp,'-5 hours')='2026-09-03' and time(timestamp,'-5 hours') between '12:00' and '14:45' group by 1 order by 1"
sqlite3 "$DB" "select time(timestamp,'-5 hours'), substr(decision_json,1,160) from decision_records where date(timestamp,'-5 hours')='2026-09-03' and time(timestamp,'-5 hours') between '08:30' and '14:45' and (decision_json like '%open_long%' or decision_json like '%open_short%') order by 1"
echo "--- 09-03 NY count of decisions & waits 08:30-14:45"
sqlite3 "$DB" "select count(*), sum(decision_json like '%\"wait\"%'), sum(decision_json like '%open_long%'), sum(decision_json like '%open_short%') from decision_records where date(timestamp,'-5 hours')='2026-09-03' and time(timestamp,'-5 hours') between '08:30' and '14:45'"
echo "--- touch_outcomes: ordinal=1 hold rate, all and by kind; RTH-L pooled; ambiguous share per kind"
sqlite3 "$DB" "select ordinal, sum(outcome='hold') h, sum(outcome='break') b, sum(outcome='ambiguous_horizon') amb from touch_outcomes group by 1 order by 1 limit 6"
sqlite3 "$DB" "select level_kind, sum(outcome='hold') h, sum(outcome='break') b, sum(outcome='ambiguous_horizon') amb from touch_outcomes where ordinal=1 group by 1 having h+b>=10 order by h+b desc"
sqlite3 "$DB" "select candidate_seated, sum(outcome='hold') h, sum(outcome='break') b, sum(outcome='ambiguous_horizon') amb from touch_outcomes group by 1"
sqlite3 "$DB" "select horizon, k, band_pts, count(*) from touch_outcomes group by 1,2,3 order by 4 desc limit 5"
echo "--- touch_outcomes mfe/mae after touch by outcome (pts)"
sqlite3 "$DB" "select outcome, count(*), round(avg(mfe_pts),1), round(avg(mae_pts),1), round(avg(bars_to_exit),1) from touch_outcomes group by 1"
