#!/bin/bash
DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "--- 09-03 outage bounds: last decision before 13:00 and first after 13:00 CT"
sqlite3 "$DB" "select max(datetime(timestamp,'-5 hours')) from decision_records where date(timestamp,'-5 hours')='2026-09-03' and time(timestamp,'-5 hours')<'13:00'"
sqlite3 "$DB" "select min(datetime(timestamp,'-5 hours')) from decision_records where date(timestamp,'-5 hours')='2026-09-03' and time(timestamp,'-5 hours')>='13:00'"
echo "--- post-0B executor totals (>= 2026-09-02 07:49 CT): cycles, watch, open intents, closes, entry_gate refusals, model-seconds"
sqlite3 "$DB" "select count(*), sum(cycle_type='watch'), sum(decision_json like '%open_long%' or decision_json like '%open_short%'), sum(decision_json like '%close_long%' or decision_json like '%close_short%'), sum(execution_log like '%entry_gate%'), round(sum(ai_latency_ms)/1000.0/3600,2) model_hours, round(avg(ai_latency_ms)/1000.0,1) avg_s from decision_records where datetime(timestamp,'-5 hours')>='2026-09-02 07:49:06'"
echo "--- era executor totals (>= 2026-08-15)"
sqlite3 "$DB" "select count(*), sum(decision_json like '%open_long%' or decision_json like '%open_short%'), sum(decision_json like '%close_long%' or decision_json like '%close_short%'), round(sum(ai_latency_ms)/1000.0/3600,2) model_hours from decision_records where date(timestamp,'-5 hours')>='2026-08-15'"
echo "--- open intents post-0B: what happened (execution_log head)"
sqlite3 "$DB" "select datetime(timestamp,'-5 hours'), substr(replace(execution_log,char(10),' | '),1,150) from decision_records where datetime(timestamp,'-5 hours')>='2026-09-02 07:49:06' and (decision_json like '%open_long%' or decision_json like '%open_short%') order by 1"
echo "--- ab_confirm_log open rows: created range vs resolved rows"
sqlite3 "$DB" "select outcome, count(*), min(datetime(strftime('%s',created_at),'unixepoch','-5 hours')), max(datetime(strftime('%s',created_at),'unixepoch','-5 hours')), sum(is_counterfactual), sum(normalized) from ab_confirm_log group by 1"
sqlite3 "$DB" "select date(strftime('%s',created_at),'unixepoch','-5 hours') d, sum(outcome='open'), sum(outcome<>'open') from ab_confirm_log group by 1 order by 1"
echo "--- e8 recompute / price-scale flags"
sqlite3 "$DB" "select recompute, count(*), sum(abs(net_pnl)>2000) big from ab_confirm_log group by 1"
echo "--- planner authoring latency proxy: plans per session-read attempt; plan created_at minus scheduled read time for NY (08:00 CT) scheduled reads"
sqlite3 "$DB" "select trade_date, session, version, trigger_reason, datetime(strftime('%s',created_at),'unixepoch','-5 hours') created_ct from plans where trigger_reason like '%scheduled_read%' and trade_date>='2026-08-31' order by 1,2"
