DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "== era rows by plan_id UNRESOLVABLE =="
sqlite3 "$DB" "select id, plan_id, source, plan_session, pnl_corrected, side from trader_positions where entry_time >= strftime('%s','2026-08-15 00:00:00')*1000 and plan_id='UNRESOLVABLE' order by id;"
echo "== count era, era non-test, non-null pnl =="
sqlite3 "$DB" "select count(*) from trader_positions where entry_time >= strftime('%s','2026-08-15 00:00:00')*1000;"
sqlite3 "$DB" "select source, count(*) from trader_positions where entry_time >= strftime('%s','2026-08-15 00:00:00')*1000 group by 1;"
echo "== compliant population: era, non-test, pnl non-null, plan_id != UNRESOLVABLE =="
sqlite3 "$DB" "select count(*), round(sum(pnl_corrected),2), round(avg(pnl_corrected),4), sum(pnl_corrected>0), sum(pnl_corrected<0), sum(pnl_corrected=0) from trader_positions where entry_time >= strftime('%s','2026-08-15 00:00:00')*1000 and source!='e7_farside_test' and pnl_corrected is not null and plan_id!='UNRESOLVABLE';"
echo "== the 65-set (includes UNRESOLVABLE) =="
sqlite3 "$DB" "select count(*), round(sum(pnl_corrected),2), sum(pnl_corrected>0), sum(pnl_corrected<0), sum(pnl_corrected=0) from trader_positions where entry_time >= strftime('%s','2026-08-15 00:00:00')*1000 and source!='e7_farside_test' and pnl_corrected is not null;"
echo "== ids in compliant set =="
sqlite3 "$DB" "select group_concat(id,',') from trader_positions where entry_time >= strftime('%s','2026-08-15 00:00:00')*1000 and source!='e7_farside_test' and pnl_corrected is not null and plan_id!='UNRESOLVABLE';"
