DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "== detector barrier params =="
sqlite3 "$DB" "select horizon, k, exit_on, count(*), min(delta), max(delta), min(band_pts), max(band_pts) from touch_outcomes group by 1,2,3;"
echo "== outcome vs bars_to_exit and wallclock minutes =="
sqlite3 "$DB" "select outcome, count(*), round(avg(bars_to_exit),2), round(avg((closed_at_ms-opened_at_ms)/60000.0),2), round(max((closed_at_ms-opened_at_ms)/60000.0),2) from touch_outcomes group by 1;"
echo "== excursion mins by outcome (barrier artefact test) =="
sqlite3 "$DB" "select outcome, count(*), round(min(mfe_pts),2), round(max(mfe_pts),2), round(min(abs(mae_pts)),2), round(max(abs(mae_pts)),2) from touch_outcomes group by 1;"
echo "== hold |mae| median overall and RTH-L/NY and VWAP/NY =="
for q in "1=1" "level_kind='RTH-L' and session='NY'" "level_kind='VWAP' and session='NY'"; do
echo "-- $q hold |mae| p50:"; sqlite3 "$DB" "select count(*), round(avg(abs(mae_pts)),2) from touch_outcomes where outcome='hold' and $q;"
sqlite3 "$DB" "select round(abs(mae_pts),2) from touch_outcomes where outcome='hold' and $q order by abs(mae_pts) limit 1 offset (select count(*)/2 from touch_outcomes where outcome='hold' and $q);"
echo "-- $q break mfe p50:"; sqlite3 "$DB" "select round(mfe_pts,2) from touch_outcomes where outcome='break' and $q order by mfe_pts limit 1 offset (select count(*)/2 from touch_outcomes where outcome='break' and $q);"
done
echo "== stop_floor_pts distribution (planner_read_facts) =="
sqlite3 "$DB" "select count(*), round(min(stop_floor_pts),2), round(avg(stop_floor_pts),2), round(max(stop_floor_pts),2), sum(stop_floor_pts>22.0), sum(stop_floor_pts>20.5) from planner_read_facts;"
echo "== kinds: n, ambiguous share =="
sqlite3 "$DB" "select level_kind, count(*) n, sum(outcome='ambiguous_horizon') amb, round(100.0*sum(outcome='ambiguous_horizon')/count(*),1) pct from touch_outcomes group by 1 having n>=10 order by n desc;"
echo "== VWAP NY ambiguity =="
sqlite3 "$DB" "select session, count(*), sum(outcome='ambiguous_horizon'), sum(outcome='hold'), sum(outcome='break') from touch_outcomes where level_kind='VWAP' group by 1;"
echo "== cells with resolved>50 =="
sqlite3 "$DB" "select level_kind, session, sum(outcome in ('hold','break')) res, sum(outcome='hold') hold, count(*) tot, sum(outcome='ambiguous_horizon') amb from touch_outcomes group by 1,2 having res>50;"
echo "== first touch (ordinal=1) =="
sqlite3 "$DB" "select count(*), sum(outcome='hold'), sum(outcome='break'), sum(outcome='ambiguous_horizon') from touch_outcomes where ordinal=1;"
echo "== RTH-L NY ordinal split and ambiguity =="
sqlite3 "$DB" "select ordinal, count(*), sum(outcome='hold'), sum(outcome='break'), sum(outcome='ambiguous_horizon') from touch_outcomes where level_kind='RTH-L' and session='NY' group by 1;"
echo "== touch_episodes session_day / label vocab =="
sqlite3 "$DB" "select session_day, count(*) from touch_episodes group by 1;"
sqlite3 "$DB" "select count(distinct label) from touch_episodes; select count(distinct level_kind) from touch_outcomes;"
