DB="file:/home/hoang/nofx/data/data.db?mode=ro"
echo "== RTH-L touches by CT day and session =="
sqlite3 "$DB" "select date(opened_at_ms/1000,'unixepoch','-5 hours') d, session, count(*), sum(outcome in ('hold','break')) res, sum(outcome='break') brk from touch_outcomes where level_kind='RTH-L' group by 1,2 order by 1;"
echo "== all touch_outcomes by CT day =="
sqlite3 "$DB" "select date(opened_at_ms/1000,'unixepoch','-5 hours') d, count(*) from touch_outcomes group by 1 order by 1;"
echo "== NY kinds touched 09-04 =="
sqlite3 "$DB" "select level_kind, count(*) from touch_outcomes where date(opened_at_ms/1000,'unixepoch','-5 hours')='2026-09-04' and session='NY' group by 1 order by 2 desc;"
echo "== episode<->outcome join rate (tight) =="
sqlite3 "$DB" "select count(*) from touch_outcomes t where exists (select 1 from touch_episodes e where e.trader_id=t.trader_id and abs(e.level_price-t.level_price)<0.01 and abs(e.opened_at_ms-t.opened_at_ms)<60000);"
echo "== loose join (same trader, price +-0.26, same CT day) =="
sqlite3 "$DB" "select count(*) from touch_outcomes t where exists (select 1 from touch_episodes e where e.trader_id=t.trader_id and abs(e.level_price-t.level_price)<=0.26 and date(e.opened_at_ms/1000,'unixepoch','-5 hours')=date(t.opened_at_ms/1000,'unixepoch','-5 hours'));"
echo "== episodes day range from opened_at_ms =="
sqlite3 "$DB" "select min(date(opened_at_ms/1000,'unixepoch','-5 hours')), max(date(opened_at_ms/1000,'unixepoch','-5 hours')), count(*) from touch_episodes;"
echo "== does session_day match opened_at_ms day? =="
sqlite3 "$DB" "select sum(session_day=date(opened_at_ms/1000,'unixepoch','-5 hours')), count(*) from touch_episodes;"
echo "== approach_atr populated? =="
sqlite3 "$DB" "select count(*), sum(approach_atr is null), round(min(approach_atr),3), round(max(approach_atr),3) from touch_episodes;"
echo "== armed_entry rows =="
sqlite3 "$DB" "select id, source, pnl_corrected, plan_id, plan_session, entry_price, exit_price from trader_positions where source='armed_entry';"
echo "== entry hours CT, era non-test =="
sqlite3 "$DB" "select strftime('%H', datetime(entry_time/1000,'unixepoch','-5 hours')) h, count(*) from trader_positions where entry_time >= strftime('%s','2026-08-15')*1000 and source!='e7_farside_test' group by 1 order by 1;"
