package trader

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"nofx/kernel"
	"nofx/market"
	"nofx/store"
)

// ── ONE SETUP — THE ARM-PATH GOLDEN FIXTURE ─────────────────────────────────
//
// Drives the REAL arm path (maybeManageArmedOrdersAt) on a three-scenario plan
// and a fixed tape, then snapshots what the path DID: the ledger rows it wrote
// and the refusal counters it recorded. The snapshot is the "arm-path golden".
//
// This file references NO one-setup symbol on purpose: the golden
// testdata/one_setup_arm_path.golden was generated by THIS file at dev
// 499e4f83 (before the wave existed), so E2 ("OFF restores today
// byte-identically") is a comparison against yesterday's tree, not against a
// number this tree produced for itself. Regenerate ONLY at a base commit:
// ONE_SETUP_GOLDEN_WRITE=1 go test ./trader -run TestOneSetupArmPathGoldenFixture
//
// Same clock discipline as TestSplitArmWritesTwoLedgerRows: the plan provider
// resolves the session from time.Now(), so the fixture uses the wall clock
// through the seam and SKIPS inside the no-trade bands where the path refuses
// by design.

const oneSetupGoldenPath = "testdata/one_setup_arm_path.golden"

// oneSetupFixtureDocOverride lets a seam test author a different plan through
// the same fixture; "" is the golden's doc. Reset by the fixture's cleanup.
var oneSetupFixtureDocOverride string

// oneSetupFixtureDoc: S1 reject long at 29490 · S2 reject short at 29500 ·
// S3 sweep_reclaim short at 29498 on wait_confirm (its confirm is never met on
// this tape, so it stays dormant before every gate). Both rejects clear the
// R:R floor of 2.0. Economics carry a first obstacle for S1 and S2.
func oneSetupFixtureDoc() string {
	o1, o2 := 29520.0, 29470.0
	d := kernel.PlanDoc{Bias: kernel.PlanBias{Direction: "long", Conviction: "low", FlipCondition: "n/a"},
		Levels: []kernel.PlanLevel{
			{Price: 29490, Label: "PDL", Grade: "A", Instruction: "fade"},
			{Price: 29500, Label: "ONH", Grade: "B", Instruction: "fade"},
		},
		Scenarios: []kernel.PlanScenario{
			{ID: "S1", Trigger: "reject at 29490", Condition: "reject", Direction: "long", TargetChain: []float64{29520}, Invalid: "below 29480", Quality: "A",
				Confirm:   &kernel.PlanConfirm{Rule: "touch", RefPrice: 29490, Side: "above"},
				Economics: &kernel.ScenarioEconomics{Version: 1, FirstObstacle: &kernel.ScenarioObstacle{Price: &o1, Level: "OB", Family: "Order Block", Response: "reduce"}},
				Arm:       &kernel.PlanArmSpec{Enabled: true, Entry: 29490, Stop: 29480, Target: 29530}},
			{ID: "S2", Trigger: "reject at 29500", Condition: "reject", Direction: "short", TargetChain: []float64{29470}, Invalid: "above 29510", Quality: "B",
				Confirm:   &kernel.PlanConfirm{Rule: "touch", RefPrice: 29500, Side: "below"},
				Economics: &kernel.ScenarioEconomics{Version: 1, FirstObstacle: &kernel.ScenarioObstacle{Price: &o2, Level: "SWG-L", Family: "Swing Low", Response: "reduce"}},
				Arm:       &kernel.PlanArmSpec{Enabled: true, Entry: 29500, Stop: 29510, Target: 29460}},
			{ID: "S3", Trigger: "sweep 29498 reclaim fails", Condition: "sweep_reclaim", Direction: "short", TargetChain: []float64{29450}, Invalid: "above 29510", Quality: "B",
				Confirm:  &kernel.PlanConfirm{Rule: "touch", RefPrice: 29498, Side: "below"},
				Confirm2: &kernel.PlanConfirm{Rule: "1x5m_close", RefPrice: 29498, Side: "below"},
				Arm:      &kernel.PlanArmSpec{Enabled: true, Entry: 29498, Stop: 29512, Target: 29450, WaitConfirm: true}},
		},
		NoTrade: []string{}, DeathCondition: "n/a",
	}
	structuralTestMap(&d, structuralTestZone{29490, 29485, 29495, "PDL"}, structuralTestZone{29500, 29495, 29505, "ONH"}, structuralTestZone{29520, 29520, 29522, "target-high"}, structuralTestZone{29470, 29468, 29470, "target-low"})
	blob, _ := json.Marshal(d)
	return string(blob)
}

// oneSetupFixtureTape: 80 quiet minutes at 29495 ending in the past — every
// bucket closed, no confirm met, ATR small and deterministic.
func oneSetupFixtureTape(now time.Time) []market.Kline {
	base := now.Add(-80 * time.Minute).Truncate(time.Minute).UnixMilli()
	out := make([]market.Kline, 0, 80)
	for i := 0; i < 80; i++ {
		cl := 29495.0
		o := base + int64(i)*60_000
		out = append(out, market.Kline{OpenTime: o, CloseTime: o + 59_999, Open: cl, High: cl + 1, Low: cl - 1, Close: cl})
	}
	return out
}

type armPathGolden struct {
	Rows     []map[string]any  `json:"rows"`
	Counters map[string]string `json:"counters"`
}

// driveOneSetupArmPath builds the trader, the plan and the tape, runs ONE arm
// cycle, and returns the golden. mutate lets a caller set knobs on the config
// before the trader is built; hook lets it touch the trader before the cycle.
func driveOneSetupArmPath(t *testing.T, mutate func(*store.StrategyConfig), hook func(*AutoTrader, *store.Store, string)) (armPathGolden, *AutoTrader, *store.Store, time.Time) {
	t.Helper()
	cfg := store.StrategyConfig{DayPlan: &store.DayPlanConfig{PlanEnabled: true}}
	cfg.RiskControl.MinRiskRewardRatio = 2
	structuralTestPolicy(&cfg, 5)
	if mutate != nil {
		mutate(&cfg)
	}
	at, st := resetTrader(t, cfg)
	now := time.Now()
	sess, ok := at.sessionRegistry(now).ActiveSession(now)
	if !ok {
		t.Skip("no active session right now")
	}
	if kernel.InLunchNoTrade(now) {
		ls, le := kernel.LunchWindowCT()
		t.Skipf("inside the lunch no-trade window (%s–%s CT)", ls, le)
	}
	cfg.DayPlan.SessionsEnabled = []string{sess.Name}
	trueV := true
	cfg.DayPlan.Sessions = []store.DayPlanSessionOverride{{Session: sess.Name, Enable: &trueV}}
	if runnable, why := at.sessionRunnable(sess); !runnable {
		t.Skipf("%s did not become runnable (%s)", sess.Name, why)
	}
	// Checked AFTER the fixture declared its session (the split test's lesson):
	// a band read before the enablement it depends on is a finding about the
	// reader, not the system.
	if why, blocked := at.sessionEntryBlockedAt(now); blocked {
		t.Skipf("inside a no-trade band right now (%s) — the arm path refuses by design", why)
	}
	td, _ := kernel.PlanChainTradeDate(sess, now)
	pid := store.MakePlanIDForTrader(at.id, td, sess.Name)
	doc := oneSetupFixtureDoc()
	if oneSetupFixtureDocOverride != "" {
		doc = oneSetupFixtureDocOverride
	}
	t.Cleanup(func() { oneSetupFixtureDocOverride = "" })
	if _, err := st.Plan().AppendPlan(&store.PlanDB{PlanID: pid, TradeDate: td, Session: sess.Name, StrategyID: at.id, Lifecycle: "active", Doc: doc, CreatedAt: now.Add(-30 * time.Minute)}); err != nil {
		t.Fatal(err)
	}
	installActivePlanProvider(at, st)
	prev := market.FuturesBarsProvider
	market.FuturesBarsProvider = func(symbol string, tf string, n int) []market.Kline { return oneSetupFixtureTape(now) }
	t.Cleanup(func() { market.FuturesBarsProvider = prev })
	if hook != nil {
		hook(at, st, pid)
	}
	at.maybeManageArmedOrdersAt(nil, now)
	return snapshotArmPath(t, at, st, td, sess.Name), at, st, now
}

func snapshotArmPath(t *testing.T, at *AutoTrader, st *store.Store, tradeDate, session string) armPathGolden {
	t.Helper()
	g := armPathGolden{Counters: map[string]string{}}
	rows, err := st.ArmedOrders().ListNonTerminal(at.id)
	if err != nil {
		t.Fatal(err)
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].Scenario != rows[j].Scenario {
			return rows[i].Scenario < rows[j].Scenario
		}
		return rows[i].LegIndex < rows[j].LegIndex
	})
	for _, r := range rows {
		g.Rows = append(g.Rows, map[string]any{
			"scenario": r.Scenario, "leg": r.LegIndex, "side": r.Side, "entry": r.EntryPx, "stop": r.StopPx, "target": r.TargetPx,
			"state": r.State, "condition": r.Condition, "kind": r.Kind,
		})
	}
	var kv []struct{ Key, Value string }
	prefix := "arm_refusals_0b:" + at.id + ":" + tradeDate + ":" + session + ":"
	if err := st.GormDB().Raw("SELECT key, value FROM system_config WHERE key LIKE ?", prefix+"%").Scan(&kv).Error; err != nil {
		t.Fatal(err)
	}
	for _, r := range kv {
		g.Counters[strings.TrimPrefix(r.Key, prefix)] = r.Value
	}
	return g
}

func goldenBytes(t *testing.T, g armPathGolden) []byte {
	t.Helper()
	b, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return append(b, '\n')
}

// TestOneSetupArmPathGoldenFixture — the unmodified path on the fixture equals
// the pinned golden. At the base commit it WRITES the golden when asked.
func TestOneSetupArmPathGoldenFixture(t *testing.T) {
	g, _, _, _ := driveOneSetupArmPath(t, nil, nil)
	got := goldenBytes(t, g)
	if os.Getenv("ONE_SETUP_GOLDEN_WRITE") == "1" {
		if err := os.MkdirAll(filepath.Dir(oneSetupGoldenPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(oneSetupGoldenPath, got, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("golden written: %s (%d bytes)", oneSetupGoldenPath, len(got))
		return
	}
	// The byte comparison against the base golden is E2's, under the OFF
	// knob (one_setup_seam_test.go): this tree's DEFAULT is the wave, so the
	// unmodified path is expected to differ from the base. Here the fixture
	// only proves it still runs and snapshots.
	if len(got) == 0 {
		t.Fatal("empty snapshot")
	}
}
